[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "Filament"

[build]
create-missing = false

[output.html]
mathjax-support = true
default-theme = "ayu"
preferred-dark-theme = "ayu"

[output.html.print]
enable = false

[output.html.fold]
enable = false
