/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.

package com.google.android.filament;

import java.lang.IllegalStateException;

import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.RestrictTo;

public class Foo {
    private long mNativeObject;

    public int c;
    @IntRange(from = 0)
    public int uc;
    public int s;
    @IntRange(from = 0)
    public int us;
    public int i;
    @IntRange(from = 0)
    public int ui;
    public long l;
    @IntRange(from = 0)
    public long ul;
    public float f;
    public double d;
    public boolean b;
    public int i8;
    @IntRange(from = 0)
    public int ui8;
    public int i16;
    @IntRange(from = 0)
    public int ui16;
    public int i32;
    @IntRange(from = 0)
    public int ui32;
    public long i64;
    @IntRange(from = 0)
    public long ui64;
    @IntRange(from = 0)
    public int st;

    Foo(long nativeObject) {
        mNativeObject = nativeObject;
    }

    @NonNull
    @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
    public static Foo wrap(long nativeObject) {
        return new Foo(nativeObject);
    }

    @IntRange(from = 0)
    public int method(int c, @IntRange(from = 0) int uc) {
        return nMethod(getNativeObject(), c, uc);
    }

    public long getNativeObject() {
        if (mNativeObject == 0) {
            throw new IllegalStateException("Calling method on destroyed Foo");
        }
        return mNativeObject;
    }

    void clearNativeObject() {
        mNativeObject = 0;
    }

    @IntRange(from = 0)
    private static native int nMethod(long nativeFoo, int c, @IntRange(from = 0) int uc);
}

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.
