/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.

package com.google.android.filament;

import java.lang.IllegalStateException;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.RestrictTo;
import androidx.annotation.Size;

public class ExceptionsTest {
    private long mNativeObject;

    ExceptionsTest(long nativeObject) {
        mNativeObject = nativeObject;
    }

    @NonNull
    @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
    public static ExceptionsTest wrap(long nativeObject) {
        return new ExceptionsTest(nativeObject);
    }

    public void doNoexcept(int a) {
        nDoNoexcept(getNativeObject(), a);
    }

    public int getNoexcept(int a) {
        return nGetNoexcept(getNativeObject(), a);
    }

    public void doThrow(int a) {
        nDoThrow(getNativeObject(), a);
    }

    public int getThrow(int a) {
        return nGetThrow(getNativeObject(), a);
    }

    @NonNull @Size(min = 3)
    public float[] getVectorNoexcept(int a, @Nullable @Size(min = 3) float[] out) {
        out = Asserts.assertFloat3(out);
        nGetVectorNoexcept(getNativeObject(), a, out);
        return out;
    }

    @NonNull @Size(min = 3)
    public float[] getVectorThrow(int a, @Nullable @Size(min = 3) float[] out) {
        out = Asserts.assertFloat3(out);
        nGetVectorThrow(getNativeObject(), a, out);
        return out;
    }

    public long getNativeObject() {
        if (mNativeObject == 0) {
            throw new IllegalStateException("Calling method on destroyed ExceptionsTest");
        }
        return mNativeObject;
    }

    void clearNativeObject() {
        mNativeObject = 0;
    }

    private static native void nDoNoexcept(long nativeExceptionsTest, int a);
    private static native int nGetNoexcept(long nativeExceptionsTest, int a);
    private static native void nDoThrow(long nativeExceptionsTest, int a);
    private static native int nGetThrow(long nativeExceptionsTest, int a);
    private static native void nGetVectorNoexcept(long nativeExceptionsTest, int a, @Size(min = 3) float[] out);
    private static native void nGetVectorThrow(long nativeExceptionsTest, int a, @Size(min = 3) float[] out);
}

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.
