/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.

#include <filament/Engine.h>

#include <common/JniUtils.h>
#include <jni.h>
#include <tools/apigen/tests/java/17_builder_pattern.h>

using namespace filament;
using namespace filament::android;
using namespace utils;

extern "C" JNIEXPORT jfloat JNICALL
Java_com_google_android_filament_BuilderTest_nGetIntensity(JNIEnv *env, jclass clazz, jlong nativeBuilderTest) {
    BuilderTest const * const that = (BuilderTest const *) nativeBuilderTest;
    return (jfloat)that->getIntensity();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_BuilderTest_nSetIntensity(JNIEnv *env, jclass clazz, jlong nativeBuilderTest, jfloat intensity) {
    BuilderTest* const that = (BuilderTest*) nativeBuilderTest;
    that->setIntensity(intensity);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_BuilderTest_nCreateBuilder(JNIEnv *env, jclass clazz) {
    return (jlong) new BuilderTest::Builder{};
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_BuilderTest_nDestroyBuilder(JNIEnv *env, jclass clazz, jlong nativeBuilder) {
    BuilderTest::Builder* builder = (BuilderTest::Builder*) nativeBuilder;
    delete builder;
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_BuilderTest_nBuilderIntensity(JNIEnv *env, jclass clazz, jlong nativeBuilder, jfloat intensity) {
    BuilderTest::Builder* builder = (BuilderTest::Builder*) nativeBuilder;
    builder->intensity(intensity);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_BuilderTest_nBuilderMode(JNIEnv *env, jclass clazz, jlong nativeBuilder, jint mode) {
    BuilderTest::Builder* builder = (BuilderTest::Builder*) nativeBuilder;
    builder->mode((BuilderTest::Mode)mode);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_BuilderTest_nBuilderParent(JNIEnv *env, jclass clazz, jlong nativeBuilder, jlong parent) {
    BuilderTest::Builder* builder = (BuilderTest::Builder*) nativeBuilder;
    builder->parent((const BuilderTest*)parent);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_BuilderTest_nBuilderBuild(JNIEnv *env, jclass clazz, jlong nativeBuilder, jlong nativeEngine) {
    BuilderTest::Builder* builder = (BuilderTest::Builder*) nativeBuilder;
    Engine* engine = (Engine*) nativeEngine;
    return filament::android::wrapJni<jlong>(env, [=]() {
        return (jlong) builder->build(*engine);
    });
}


// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.
