/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.

package com.google.android.filament;

import java.lang.IllegalStateException;

import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.RestrictTo;
import androidx.annotation.Size;

public class TaggedArrayBuffersTest {
    private long mNativeObject;

    /** Element types for float tagged array buffers. */
    public enum FloatElement {
        FLOAT,
        FLOAT2,
        FLOAT4,
        MAT4;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /** Element types for int tagged array buffers. */
    public enum IntElement {
        INT,
        INT4;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /** Element types for boolean tagged array buffers. */
    public enum BooleanElement {
        BOOL,
        BOOL4;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    TaggedArrayBuffersTest(long nativeObject) {
        mNativeObject = nativeObject;
    }

    @NonNull
    @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
    public static TaggedArrayBuffersTest wrap(long nativeObject) {
        return new TaggedArrayBuffersTest(nativeObject);
    }

    /**
     * Set a uniform buffer parameter array by name.
     *
     * @param name Name of the parameter.
     * @param type the number of components for each individual parameter
     * @param values Array of values to set.
     * @param offset the number of elements in <code>values</code> to skip
     */
    public void setBuffer(@NonNull String name, @NonNull FloatElement type, @NonNull float[] values, @IntRange(from = 0) int offset, @IntRange(from = 1) int count) {
        nSetBufferFloatArray(getNativeObject(), name, type.ordinal(), values, offset, count);
    }

    /**
     * Set a uniform buffer parameter array by name.
     *
     * @param name Name of the parameter.
     * @param type the number of components for each individual parameter
     * @param values Array of values to set.
     */
    public void setBuffer(@NonNull String name, @NonNull FloatElement type, @NonNull float[] values, @IntRange(from = 1) int count) {
        setBuffer(name, type, values, 0, count);
    }

    /**
     * Set a uniform buffer parameter array by name.
     *
     * @param name Name of the parameter.
     * @param type the number of components for each individual parameter
     * @param values Array of values to set.
     * @param offset the number of elements in <code>values</code> to skip
     */
    public void setBuffer(@NonNull String name, @NonNull IntElement type, @NonNull int[] values, @IntRange(from = 0) int offset, @IntRange(from = 1) int count) {
        nSetBufferIntArray(getNativeObject(), name, type.ordinal(), values, offset, count);
    }

    /**
     * Set a uniform buffer parameter array by name.
     *
     * @param name Name of the parameter.
     * @param type the number of components for each individual parameter
     * @param values Array of values to set.
     */
    public void setBuffer(@NonNull String name, @NonNull IntElement type, @NonNull int[] values, @IntRange(from = 1) int count) {
        setBuffer(name, type, values, 0, count);
    }

    /**
     * Set a uniform buffer parameter array by name.
     *
     * @param name Name of the parameter.
     * @param type the number of components for each individual parameter
     * @param values Array of values to set.
     * @param offset the number of elements in <code>values</code> to skip
     */
    public void setBuffer(@NonNull String name, @NonNull BooleanElement type, @NonNull boolean[] values, @IntRange(from = 0) int offset, @IntRange(from = 1) int count) {
        nSetBufferBooleanArray(getNativeObject(), name, type.ordinal(), values, offset, count);
    }

    /**
     * Set a uniform buffer parameter array by name.
     *
     * @param name Name of the parameter.
     * @param type the number of components for each individual parameter
     * @param values Array of values to set.
     */
    public void setBuffer(@NonNull String name, @NonNull BooleanElement type, @NonNull boolean[] values, @IntRange(from = 1) int count) {
        setBuffer(name, type, values, 0, count);
    }

    public long getNativeObject() {
        if (mNativeObject == 0) {
            throw new IllegalStateException("Calling method on destroyed TaggedArrayBuffersTest");
        }
        return mNativeObject;
    }

    void clearNativeObject() {
        mNativeObject = 0;
    }

    private static native void nSetBufferFloatArray(long nativeTaggedArrayBuffersTest, @NonNull String name, int type, @NonNull @Size(min = 1) float[] values, @IntRange(from = 0) int offset, @IntRange(from = 1) int count);
    private static native void nSetBufferIntArray(long nativeTaggedArrayBuffersTest, @NonNull String name, int type, @NonNull @Size(min = 1) int[] values, @IntRange(from = 0) int offset, @IntRange(from = 1) int count);
    private static native void nSetBufferBooleanArray(long nativeTaggedArrayBuffersTest, @NonNull String name, int type, @NonNull @Size(min = 1) boolean[] values, @IntRange(from = 0) int offset, @IntRange(from = 1) int count);
}

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.
