name: 'Mac Preqrequisites'
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/dep-versions
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
      with:
        python-version: '3.x'
    - name: Cache Brew
      id: brew-cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: ~/Library/Caches/Homebrew
        key: ${{ runner.os }}-brew-20251211
    - name: Install Mac Prerequisites
      shell: bash
      run: |
        # Install brew prereqs
        brew install coreutils
        # Install ninja
        source ./build/common/get-ninja.sh
