name: hello-ar
options:
    bundleIdPrefix: ${SAMPLE_CODE_DISAMBIGUATOR}.google.filament
include: ../app-template.yml
targets:
    hello-ar:
        templates:
            - FilamentApp
        dependencies:
            - sdk: ARKit.framework
        settings:
            base:
                OTHER_LDFLAGS: ["-lfilameshio", "-lmeshoptimizer", "-limage"]
        preBuildScripts:
            - path: build-resources.sh
              name: Build Resources
