name: 'Checkout Filament'
description: 'Checkout the Filament repository.'
runs: |
  git version
  git init $GITHUB_WORKSPACE
  cd $GITHUB_WORKSPACE
  git remote add origin https://github.com/google/filament
  git config gc.auto 0
  git fetch --tags --prune --progress --no-recurse-submodules origin +${GITHUB_REF}:${GITHUB_REF/refs\//refs\/remote\/}
  git checkout --progress --force ${GITHUB_REF/refs\//refs\/remote\/}
