/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.

#include <filament/Fence.h>

#include <common/JniUtils.h>
#include <jni.h>

using namespace filament;
using namespace filament::android;
using namespace utils;

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Fence_nWait(JNIEnv *env, jclass clazz, jlong nativeFence, jint mode, jlong timeout) {
    Fence* const that = (Fence*) nativeFence;
    return wrapJni<jint>(env, [=]() {
        return (jint)that->wait((Fence::Mode)mode, (uint64_t)timeout);
    });
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_Fence_nWaitAndDestroy(JNIEnv *env, jclass clazz, jlong nativeFence, jint mode) {
    Fence* const fence = (Fence*) nativeFence;
    return wrapJni<jint>(env, [=]() {
        return (jint)Fence::waitAndDestroy(fence, (Fence::Mode)mode);
    });
}

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.
