/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.

#include <filament/Engine.h>
#include <filament/LightManager.h>

#include <utils/Entity.h>
#include <utils/EntityInstance.h>
#include <utils/Slice.h>

#include <math/vec4.h>

#include <common/JniUtils.h>
#include <jni.h>

using namespace filament;
using namespace filament::android;
using namespace filament::math;
using namespace utils;

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_LightManager_nGetComponentCount(JNIEnv *env, jclass clazz, jlong nativeLightManager) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jint)that->getComponentCount();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_LightManager_nHasComponent(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint e) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jboolean)that->hasComponent(Entity::import(e));
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_LightManager_nEmpty(JNIEnv *env, jclass clazz, jlong nativeLightManager) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jboolean)that->empty();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_LightManager_nGetEntity(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jint)Entity::smuggle(that->getEntity(EntityInstance<LightManager>(i)));
}

extern "C" JNIEXPORT jintArray JNICALL
Java_com_google_android_filament_LightManager_nGetAllEntities(JNIEnv *env, jclass clazz, jlong nativeLightManager, jintArray out_) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    auto const slice = that->getAllEntities();
    jsize const count = static_cast<jsize>(slice.size());
    if (out_ == nullptr || env->GetArrayLength(out_) < count) {
        out_ = env->NewIntArray(count);
    }
    if (count > 0) {
        env->SetIntArrayRegion(out_, 0, count, reinterpret_cast<const jint*>(slice.data()));
    }
    return out_;
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_LightManager_nGetInstance(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint e) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jint)that->getInstance(Entity::import(e)).asValue();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nDestroy(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint e) {
    LightManager* const that = (LightManager*) nativeLightManager;
    that->destroy(Entity::import(e));
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_LightManager_nGetType(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jint)that->getType(EntityInstance<LightManager>(i));
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_LightManager_nIsDirectional(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jboolean)that->isDirectional(EntityInstance<LightManager>(i));
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_LightManager_nIsPointLight(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jboolean)that->isPointLight(EntityInstance<LightManager>(i));
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_LightManager_nIsSpotLight(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jboolean)that->isSpotLight(EntityInstance<LightManager>(i));
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nSetLightChannel(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jint channel, jboolean enable) {
    LightManager* const that = (LightManager*) nativeLightManager;
    that->setLightChannel(EntityInstance<LightManager>(i), (unsigned int)channel, (bool)enable);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_LightManager_nGetLightChannel(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jint channel) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jboolean)that->getLightChannel(EntityInstance<LightManager>(i), (unsigned int)channel);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nSetPosition(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jfloat positionx, jfloat positiony, jfloat positionz) {
    LightManager* const that = (LightManager*) nativeLightManager;
    that->setPosition(EntityInstance<LightManager>(i), float3{positionx, positiony, positionz});
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nGetPosition(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jfloatArray out_) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    jfloat *out = env->GetFloatArrayElements(out_, nullptr);
    *reinterpret_cast<float3 *>(out) = that->getPosition(EntityInstance<LightManager>(i));
    env->ReleaseFloatArrayElements(out_, out, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nSetDirection(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jfloat directionx, jfloat directiony, jfloat directionz) {
    LightManager* const that = (LightManager*) nativeLightManager;
    that->setDirection(EntityInstance<LightManager>(i), float3{directionx, directiony, directionz});
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nGetDirection(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jfloatArray out_) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    jfloat *out = env->GetFloatArrayElements(out_, nullptr);
    *reinterpret_cast<float3 *>(out) = that->getDirection(EntityInstance<LightManager>(i));
    env->ReleaseFloatArrayElements(out_, out, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nSetColor(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jfloat colorx, jfloat colory, jfloat colorz) {
    LightManager* const that = (LightManager*) nativeLightManager;
    that->setColor(EntityInstance<LightManager>(i), float3{colorx, colory, colorz});
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nGetColor(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jfloatArray out_) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    jfloat *out = env->GetFloatArrayElements(out_, nullptr);
    *reinterpret_cast<float3 *>(out) = that->getColor(EntityInstance<LightManager>(i));
    env->ReleaseFloatArrayElements(out_, out, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nSetIntensity__JIF(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jfloat intensity) {
    LightManager* const that = (LightManager*) nativeLightManager;
    that->setIntensity(EntityInstance<LightManager>(i), intensity);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nSetIntensity__JIFF(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jfloat watts, jfloat efficiency) {
    LightManager* const that = (LightManager*) nativeLightManager;
    that->setIntensity(EntityInstance<LightManager>(i), watts, efficiency);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nSetIntensityCandela(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jfloat intensity) {
    LightManager* const that = (LightManager*) nativeLightManager;
    that->setIntensityCandela(EntityInstance<LightManager>(i), intensity);
}

extern "C" JNIEXPORT jfloat JNICALL
Java_com_google_android_filament_LightManager_nGetIntensity(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jfloat)that->getIntensity(EntityInstance<LightManager>(i));
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nSetFalloff(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jfloat radius) {
    LightManager* const that = (LightManager*) nativeLightManager;
    that->setFalloff(EntityInstance<LightManager>(i), radius);
}

extern "C" JNIEXPORT jfloat JNICALL
Java_com_google_android_filament_LightManager_nGetFalloff(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jfloat)that->getFalloff(EntityInstance<LightManager>(i));
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nSetSpotLightCone(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jfloat inner, jfloat outer) {
    LightManager* const that = (LightManager*) nativeLightManager;
    that->setSpotLightCone(EntityInstance<LightManager>(i), inner, outer);
}

extern "C" JNIEXPORT jfloat JNICALL
Java_com_google_android_filament_LightManager_nGetSpotLightOuterCone(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jfloat)that->getSpotLightOuterCone(EntityInstance<LightManager>(i));
}

extern "C" JNIEXPORT jfloat JNICALL
Java_com_google_android_filament_LightManager_nGetSpotLightInnerCone(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jfloat)that->getSpotLightInnerCone(EntityInstance<LightManager>(i));
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nSetSunAngularRadius(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jfloat angularRadius) {
    LightManager* const that = (LightManager*) nativeLightManager;
    that->setSunAngularRadius(EntityInstance<LightManager>(i), angularRadius);
}

extern "C" JNIEXPORT jfloat JNICALL
Java_com_google_android_filament_LightManager_nGetSunAngularRadius(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jfloat)that->getSunAngularRadius(EntityInstance<LightManager>(i));
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nSetSunHaloSize(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jfloat haloSize) {
    LightManager* const that = (LightManager*) nativeLightManager;
    that->setSunHaloSize(EntityInstance<LightManager>(i), haloSize);
}

extern "C" JNIEXPORT jfloat JNICALL
Java_com_google_android_filament_LightManager_nGetSunHaloSize(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jfloat)that->getSunHaloSize(EntityInstance<LightManager>(i));
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nSetSunHaloFalloff(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jfloat haloFalloff) {
    LightManager* const that = (LightManager*) nativeLightManager;
    that->setSunHaloFalloff(EntityInstance<LightManager>(i), haloFalloff);
}

extern "C" JNIEXPORT jfloat JNICALL
Java_com_google_android_filament_LightManager_nGetSunHaloFalloff(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jfloat)that->getSunHaloFalloff(EntityInstance<LightManager>(i));
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nGetShadowOptions(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jobject out_) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    static const struct JniShadowOptionsState {
        jfieldID mapSize;
        jfieldID shadowCascades;
        jfieldID cascadeSplitPositions_0;
        jfieldID cascadeSplitPositions_1;
        jfieldID cascadeSplitPositions_2;
        jfieldID constantBias;
        jfieldID normalBias;
        jfieldID shadowFar;
        jfieldID shadowNearHint;
        jfieldID shadowFarHint;
        jfieldID stable;
        jfieldID lispsm;
        jfieldID polygonOffsetConstant;
        jfieldID polygonOffsetSlope;
        jfieldID screenSpaceContactShadows;
        jfieldID stepCount;
        jfieldID maxShadowDistance;
        jfieldID Vsmelvsm;
        jfieldID VsmblurWidth;
        jfieldID shadowBulbRadius;
        jfieldID transform_X;
        jfieldID transform_Y;
        jfieldID transform_Z;
        jfieldID transform_W;
        jfieldID penumbraScale;
        jfieldID penumbraRatioScale;
        jfieldID maxPenumbraRatio;
        jfieldID maxSearchRadius;
        explicit JniShadowOptionsState(JNIEnv* env) noexcept {
            jclass clazz = env->FindClass("com/google/android/filament/LightManager$ShadowOptions");
            mapSize = env->GetFieldID(clazz, "mapSize", "I");
            shadowCascades = env->GetFieldID(clazz, "shadowCascades", "I");
            cascadeSplitPositions_0 = env->GetFieldID(clazz, "mCascadeSplitPositions0", "F");
            cascadeSplitPositions_1 = env->GetFieldID(clazz, "mCascadeSplitPositions1", "F");
            cascadeSplitPositions_2 = env->GetFieldID(clazz, "mCascadeSplitPositions2", "F");
            constantBias = env->GetFieldID(clazz, "constantBias", "F");
            normalBias = env->GetFieldID(clazz, "normalBias", "F");
            shadowFar = env->GetFieldID(clazz, "shadowFar", "F");
            shadowNearHint = env->GetFieldID(clazz, "shadowNearHint", "F");
            shadowFarHint = env->GetFieldID(clazz, "shadowFarHint", "F");
            stable = env->GetFieldID(clazz, "stable", "Z");
            lispsm = env->GetFieldID(clazz, "lispsm", "Z");
            polygonOffsetConstant = env->GetFieldID(clazz, "polygonOffsetConstant", "F");
            polygonOffsetSlope = env->GetFieldID(clazz, "polygonOffsetSlope", "F");
            screenSpaceContactShadows = env->GetFieldID(clazz, "screenSpaceContactShadows", "Z");
            stepCount = env->GetFieldID(clazz, "stepCount", "I");
            maxShadowDistance = env->GetFieldID(clazz, "maxShadowDistance", "F");
            Vsmelvsm = env->GetFieldID(clazz, "mVsmElvsm", "Z");
            VsmblurWidth = env->GetFieldID(clazz, "mVsmBlurWidth", "F");
            shadowBulbRadius = env->GetFieldID(clazz, "shadowBulbRadius", "F");
            transform_X = env->GetFieldID(clazz, "mTransformX", "F");
            transform_Y = env->GetFieldID(clazz, "mTransformY", "F");
            transform_Z = env->GetFieldID(clazz, "mTransformZ", "F");
            transform_W = env->GetFieldID(clazz, "mTransformW", "F");
            penumbraScale = env->GetFieldID(clazz, "penumbraScale", "F");
            penumbraRatioScale = env->GetFieldID(clazz, "penumbraRatioScale", "F");
            maxPenumbraRatio = env->GetFieldID(clazz, "maxPenumbraRatio", "F");
            maxSearchRadius = env->GetFieldID(clazz, "maxSearchRadius", "F");
        }
    } jniState(env);

    auto const& res = that->getShadowOptions(EntityInstance<LightManager>(i));
    env->SetIntField(out_, jniState.mapSize, static_cast<jint>(res.mapSize));
    env->SetIntField(out_, jniState.shadowCascades, static_cast<jint>(res.shadowCascades));
    env->SetFloatField(out_, jniState.cascadeSplitPositions_0, (jfloat) res.cascadeSplitPositions[0]);
    env->SetFloatField(out_, jniState.cascadeSplitPositions_1, (jfloat) res.cascadeSplitPositions[1]);
    env->SetFloatField(out_, jniState.cascadeSplitPositions_2, (jfloat) res.cascadeSplitPositions[2]);
    env->SetFloatField(out_, jniState.constantBias, (jfloat) res.constantBias);
    env->SetFloatField(out_, jniState.normalBias, (jfloat) res.normalBias);
    env->SetFloatField(out_, jniState.shadowFar, (jfloat) res.shadowFar);
    env->SetFloatField(out_, jniState.shadowNearHint, (jfloat) res.shadowNearHint);
    env->SetFloatField(out_, jniState.shadowFarHint, (jfloat) res.shadowFarHint);
    env->SetBooleanField(out_, jniState.stable, (jboolean) res.stable);
    env->SetBooleanField(out_, jniState.lispsm, (jboolean) res.lispsm);
    env->SetFloatField(out_, jniState.polygonOffsetConstant, (jfloat) res.polygonOffsetConstant);
    env->SetFloatField(out_, jniState.polygonOffsetSlope, (jfloat) res.polygonOffsetSlope);
    env->SetBooleanField(out_, jniState.screenSpaceContactShadows, (jboolean) res.screenSpaceContactShadows);
    env->SetIntField(out_, jniState.stepCount, static_cast<jint>(res.stepCount));
    env->SetFloatField(out_, jniState.maxShadowDistance, (jfloat) res.maxShadowDistance);
    env->SetBooleanField(out_, jniState.Vsmelvsm, (jboolean) res.vsm.elvsm);
    env->SetFloatField(out_, jniState.VsmblurWidth, (jfloat) res.vsm.blurWidth);
    env->SetFloatField(out_, jniState.shadowBulbRadius, (jfloat) res.shadowBulbRadius);
    env->SetFloatField(out_, jniState.transform_X, (jfloat) res.transform.x);
    env->SetFloatField(out_, jniState.transform_Y, (jfloat) res.transform.y);
    env->SetFloatField(out_, jniState.transform_Z, (jfloat) res.transform.z);
    env->SetFloatField(out_, jniState.transform_W, (jfloat) res.transform.w);
    env->SetFloatField(out_, jniState.penumbraScale, (jfloat) res.penumbraScale);
    env->SetFloatField(out_, jniState.penumbraRatioScale, (jfloat) res.penumbraRatioScale);
    env->SetFloatField(out_, jniState.maxPenumbraRatio, (jfloat) res.maxPenumbraRatio);
    env->SetFloatField(out_, jniState.maxSearchRadius, (jfloat) res.maxSearchRadius);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nSetShadowOptions(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jint optionsMapSize, jint optionsShadowCascades, jfloat optionsCascadeSplitPositions0, jfloat optionsCascadeSplitPositions1, jfloat optionsCascadeSplitPositions2, jfloat optionsConstantBias, jfloat optionsNormalBias, jfloat optionsShadowFar, jfloat optionsShadowNearHint, jfloat optionsShadowFarHint, jboolean optionsStable, jboolean optionsLispsm, jfloat optionsPolygonOffsetConstant, jfloat optionsPolygonOffsetSlope, jboolean optionsScreenSpaceContactShadows, jint optionsStepCount, jfloat optionsMaxShadowDistance, jboolean optionsVsmElvsm, jfloat optionsVsmBlurWidth, jfloat optionsShadowBulbRadius, jfloat optionsTransformX, jfloat optionsTransformY, jfloat optionsTransformZ, jfloat optionsTransformW, jfloat optionsPenumbraScale, jfloat optionsPenumbraRatioScale, jfloat optionsMaxPenumbraRatio, jfloat optionsMaxSearchRadius) {
    LightManager* const that = (LightManager*) nativeLightManager;
    LightManager::ShadowOptions options;
    options.mapSize = optionsMapSize;
    options.shadowCascades = optionsShadowCascades;
    options.cascadeSplitPositions[0] = optionsCascadeSplitPositions0;
    options.cascadeSplitPositions[1] = optionsCascadeSplitPositions1;
    options.cascadeSplitPositions[2] = optionsCascadeSplitPositions2;
    options.constantBias = optionsConstantBias;
    options.normalBias = optionsNormalBias;
    options.shadowFar = optionsShadowFar;
    options.shadowNearHint = optionsShadowNearHint;
    options.shadowFarHint = optionsShadowFarHint;
    options.stable = optionsStable;
    options.lispsm = optionsLispsm;
    options.polygonOffsetConstant = optionsPolygonOffsetConstant;
    options.polygonOffsetSlope = optionsPolygonOffsetSlope;
    options.screenSpaceContactShadows = optionsScreenSpaceContactShadows;
    options.stepCount = optionsStepCount;
    options.maxShadowDistance = optionsMaxShadowDistance;
    options.vsm.elvsm = optionsVsmElvsm;
    options.vsm.blurWidth = optionsVsmBlurWidth;
    options.shadowBulbRadius = optionsShadowBulbRadius;
    options.transform = { optionsTransformX, optionsTransformY, optionsTransformZ, optionsTransformW };
    options.penumbraScale = optionsPenumbraScale;
    options.penumbraRatioScale = optionsPenumbraRatioScale;
    options.maxPenumbraRatio = optionsMaxPenumbraRatio;
    options.maxSearchRadius = optionsMaxSearchRadius;
    that->setShadowOptions(EntityInstance<LightManager>(i), options);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nSetShadowCaster(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i, jboolean shadowCaster) {
    LightManager* const that = (LightManager*) nativeLightManager;
    that->setShadowCaster(EntityInstance<LightManager>(i), (bool)shadowCaster);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_LightManager_nIsShadowCaster(JNIEnv *env, jclass clazz, jlong nativeLightManager, jint i) {
    LightManager const * const that = (LightManager const *) nativeLightManager;
    return (jboolean)that->isShadowCaster(EntityInstance<LightManager>(i));
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_LightManager_nCreateBuilder(JNIEnv *env, jclass clazz, jint type) {
    return (jlong) new LightManager::Builder((LightManager::Type)type);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nDestroyBuilder(JNIEnv *env, jclass clazz, jlong nativeBuilder) {
    LightManager::Builder* builder = (LightManager::Builder*) nativeBuilder;
    delete builder;
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nBuilderLightChannel(JNIEnv *env, jclass clazz, jlong nativeBuilder, jint channel, jboolean enable) {
    LightManager::Builder* builder = (LightManager::Builder*) nativeBuilder;
    builder->lightChannel((unsigned int)channel, (bool)enable);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nBuilderCastShadows(JNIEnv *env, jclass clazz, jlong nativeBuilder, jboolean enable) {
    LightManager::Builder* builder = (LightManager::Builder*) nativeBuilder;
    builder->castShadows((bool)enable);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nBuilderShadowOptions(JNIEnv *env, jclass clazz, jlong nativeBuilder, jint mapSize, jint shadowCascades, jfloat cascadeSplitPositions0, jfloat cascadeSplitPositions1, jfloat cascadeSplitPositions2, jfloat constantBias, jfloat normalBias, jfloat shadowFar, jfloat shadowNearHint, jfloat shadowFarHint, jboolean stable, jboolean lispsm, jfloat polygonOffsetConstant, jfloat polygonOffsetSlope, jboolean screenSpaceContactShadows, jint stepCount, jfloat maxShadowDistance, jboolean vsmElvsm, jfloat vsmBlurWidth, jfloat shadowBulbRadius, jfloat transformX, jfloat transformY, jfloat transformZ, jfloat transformW, jfloat penumbraScale, jfloat penumbraRatioScale, jfloat maxPenumbraRatio, jfloat maxSearchRadius) {
    LightManager::Builder* builder = (LightManager::Builder*) nativeBuilder;
    LightManager::ShadowOptions optionsCpp;
    optionsCpp.mapSize = mapSize;
    optionsCpp.shadowCascades = shadowCascades;
    optionsCpp.cascadeSplitPositions[0] = cascadeSplitPositions0;
    optionsCpp.cascadeSplitPositions[1] = cascadeSplitPositions1;
    optionsCpp.cascadeSplitPositions[2] = cascadeSplitPositions2;
    optionsCpp.constantBias = constantBias;
    optionsCpp.normalBias = normalBias;
    optionsCpp.shadowFar = shadowFar;
    optionsCpp.shadowNearHint = shadowNearHint;
    optionsCpp.shadowFarHint = shadowFarHint;
    optionsCpp.stable = stable;
    optionsCpp.lispsm = lispsm;
    optionsCpp.polygonOffsetConstant = polygonOffsetConstant;
    optionsCpp.polygonOffsetSlope = polygonOffsetSlope;
    optionsCpp.screenSpaceContactShadows = screenSpaceContactShadows;
    optionsCpp.stepCount = stepCount;
    optionsCpp.maxShadowDistance = maxShadowDistance;
    optionsCpp.vsm.elvsm = vsmElvsm;
    optionsCpp.vsm.blurWidth = vsmBlurWidth;
    optionsCpp.shadowBulbRadius = shadowBulbRadius;
    optionsCpp.transform = { transformX, transformY, transformZ, transformW };
    optionsCpp.penumbraScale = penumbraScale;
    optionsCpp.penumbraRatioScale = penumbraRatioScale;
    optionsCpp.maxPenumbraRatio = maxPenumbraRatio;
    optionsCpp.maxSearchRadius = maxSearchRadius;
    builder->shadowOptions(optionsCpp);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nBuilderCastLight(JNIEnv *env, jclass clazz, jlong nativeBuilder, jboolean enable) {
    LightManager::Builder* builder = (LightManager::Builder*) nativeBuilder;
    builder->castLight((bool)enable);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nBuilderPosition(JNIEnv *env, jclass clazz, jlong nativeBuilder, jfloat positionx, jfloat positiony, jfloat positionz) {
    LightManager::Builder* builder = (LightManager::Builder*) nativeBuilder;
    builder->position(float3{positionx, positiony, positionz});
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nBuilderDirection(JNIEnv *env, jclass clazz, jlong nativeBuilder, jfloat directionx, jfloat directiony, jfloat directionz) {
    LightManager::Builder* builder = (LightManager::Builder*) nativeBuilder;
    builder->direction(float3{directionx, directiony, directionz});
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nBuilderColor(JNIEnv *env, jclass clazz, jlong nativeBuilder, jfloat colorx, jfloat colory, jfloat colorz) {
    LightManager::Builder* builder = (LightManager::Builder*) nativeBuilder;
    builder->color(float3{colorx, colory, colorz});
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nBuilderIntensity__JF(JNIEnv *env, jclass clazz, jlong nativeBuilder, jfloat intensity) {
    LightManager::Builder* builder = (LightManager::Builder*) nativeBuilder;
    builder->intensity(intensity);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nBuilderIntensityCandela(JNIEnv *env, jclass clazz, jlong nativeBuilder, jfloat intensity) {
    LightManager::Builder* builder = (LightManager::Builder*) nativeBuilder;
    builder->intensityCandela(intensity);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nBuilderIntensity__JFF(JNIEnv *env, jclass clazz, jlong nativeBuilder, jfloat watts, jfloat efficiency) {
    LightManager::Builder* builder = (LightManager::Builder*) nativeBuilder;
    builder->intensity(watts, efficiency);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nBuilderFalloff(JNIEnv *env, jclass clazz, jlong nativeBuilder, jfloat radius) {
    LightManager::Builder* builder = (LightManager::Builder*) nativeBuilder;
    builder->falloff(radius);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nBuilderSpotLightCone(JNIEnv *env, jclass clazz, jlong nativeBuilder, jfloat inner, jfloat outer) {
    LightManager::Builder* builder = (LightManager::Builder*) nativeBuilder;
    builder->spotLightCone(inner, outer);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nBuilderSunAngularRadius(JNIEnv *env, jclass clazz, jlong nativeBuilder, jfloat angularRadiusDeg) {
    LightManager::Builder* builder = (LightManager::Builder*) nativeBuilder;
    builder->sunAngularRadius(angularRadiusDeg);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nBuilderSunHaloSize(JNIEnv *env, jclass clazz, jlong nativeBuilder, jfloat haloSize) {
    LightManager::Builder* builder = (LightManager::Builder*) nativeBuilder;
    builder->sunHaloSize(haloSize);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_LightManager_nBuilderSunHaloFalloff(JNIEnv *env, jclass clazz, jlong nativeBuilder, jfloat haloFalloff) {
    LightManager::Builder* builder = (LightManager::Builder*) nativeBuilder;
    builder->sunHaloFalloff(haloFalloff);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_LightManager_nBuilderBuild(JNIEnv *env, jclass clazz, jlong nativeBuilder, jlong nativeEngine, jint entity) {
    LightManager::Builder* builder = (LightManager::Builder*) nativeBuilder;
    Engine* engine = (Engine*) nativeEngine;
    return filament::android::wrapJni<jboolean>(env, [=]() {
        return (jboolean) (builder->build(*engine, utils::Entity::import(entity)) == LightManager::Builder::Result::Success);
    });
}


// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.
