/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.

#include <filament/Engine.h>
#include <filament/RenderTarget.h>

#include <common/JniUtils.h>
#include <jni.h>

using namespace filament;
using namespace filament::android;
using namespace utils;

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderTarget_nGetTexture(JNIEnv *env, jclass clazz, jlong nativeRenderTarget, jint attachment) {
    RenderTarget const * const that = (RenderTarget const *) nativeRenderTarget;
    return (jlong)that->getTexture((RenderTarget::AttachmentPoint)attachment);
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_RenderTarget_nGetMipLevel(JNIEnv *env, jclass clazz, jlong nativeRenderTarget, jint attachment) {
    RenderTarget const * const that = (RenderTarget const *) nativeRenderTarget;
    return (jint)that->getMipLevel((RenderTarget::AttachmentPoint)attachment);
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_RenderTarget_nGetFace(JNIEnv *env, jclass clazz, jlong nativeRenderTarget, jint attachment) {
    RenderTarget const * const that = (RenderTarget const *) nativeRenderTarget;
    return (jint)that->getFace((RenderTarget::AttachmentPoint)attachment);
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_RenderTarget_nGetLayer(JNIEnv *env, jclass clazz, jlong nativeRenderTarget, jint attachment) {
    RenderTarget const * const that = (RenderTarget const *) nativeRenderTarget;
    return (jint)that->getLayer((RenderTarget::AttachmentPoint)attachment);
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_RenderTarget_nGetSupportedColorAttachmentsCount(JNIEnv *env, jclass clazz, jlong nativeRenderTarget) {
    RenderTarget const * const that = (RenderTarget const *) nativeRenderTarget;
    return (jint)that->getSupportedColorAttachmentsCount();
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderTarget_nCreateBuilder(JNIEnv *env, jclass clazz) {
    return (jlong) new RenderTarget::Builder{};
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderTarget_nDestroyBuilder(JNIEnv *env, jclass clazz, jlong nativeBuilder) {
    RenderTarget::Builder* builder = (RenderTarget::Builder*) nativeBuilder;
    delete builder;
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderTarget_nBuilderTexture(JNIEnv *env, jclass clazz, jlong nativeBuilder, jint attachment, jlong texture) {
    RenderTarget::Builder* builder = (RenderTarget::Builder*) nativeBuilder;
    builder->texture((RenderTarget::AttachmentPoint)attachment, (Texture*)texture);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderTarget_nBuilderMipLevel(JNIEnv *env, jclass clazz, jlong nativeBuilder, jint attachment, jint level) {
    RenderTarget::Builder* builder = (RenderTarget::Builder*) nativeBuilder;
    builder->mipLevel((RenderTarget::AttachmentPoint)attachment, (uint8_t)level);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderTarget_nBuilderFace(JNIEnv *env, jclass clazz, jlong nativeBuilder, jint attachment, jint face) {
    RenderTarget::Builder* builder = (RenderTarget::Builder*) nativeBuilder;
    builder->face((RenderTarget::AttachmentPoint)attachment, (RenderTarget::CubemapFace)face);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderTarget_nBuilderLayer(JNIEnv *env, jclass clazz, jlong nativeBuilder, jint attachment, jint layer) {
    RenderTarget::Builder* builder = (RenderTarget::Builder*) nativeBuilder;
    builder->layer((RenderTarget::AttachmentPoint)attachment, (uint32_t)layer);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderTarget_nBuilderMultiview(JNIEnv *env, jclass clazz, jlong nativeBuilder, jint attachment, jint layerCount, jint baseLayer) {
    RenderTarget::Builder* builder = (RenderTarget::Builder*) nativeBuilder;
    builder->multiview((RenderTarget::AttachmentPoint)attachment, (uint8_t)layerCount, (uint8_t)baseLayer);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_RenderTarget_nBuilderSamples(JNIEnv *env, jclass clazz, jlong nativeBuilder, jint samples) {
    RenderTarget::Builder* builder = (RenderTarget::Builder*) nativeBuilder;
    builder->samples((uint8_t)samples);
}

extern "C" JNIEXPORT jlong JNICALL
Java_com_google_android_filament_RenderTarget_nBuilderBuild(JNIEnv *env, jclass clazz, jlong nativeBuilder, jlong nativeEngine) {
    RenderTarget::Builder* builder = (RenderTarget::Builder*) nativeBuilder;
    Engine* engine = (Engine*) nativeEngine;
    return filament::android::wrapJni<jlong>(env, [=]() {
        return (jlong) builder->build(*engine);
    });
}


// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.
