/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.

#include <filament/TransformManager.h>

#include <utils/Entity.h>
#include <utils/EntityInstance.h>
#include <utils/Slice.h>

#include <math/mat4.h>

#include <common/JniUtils.h>
#include <jni.h>

using namespace filament;
using namespace filament::android;
using namespace filament::math;
using namespace utils;

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_TransformManager_nHasComponent(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jint e) {
    TransformManager const * const that = (TransformManager const *) nativeTransformManager;
    return (jboolean)that->hasComponent(Entity::import(e));
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_TransformManager_nGetInstance(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jint e) {
    TransformManager const * const that = (TransformManager const *) nativeTransformManager;
    return (jint)that->getInstance(Entity::import(e)).asValue();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_TransformManager_nGetComponentCount(JNIEnv *env, jclass clazz, jlong nativeTransformManager) {
    TransformManager const * const that = (TransformManager const *) nativeTransformManager;
    return (jint)that->getComponentCount();
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_TransformManager_nEmpty(JNIEnv *env, jclass clazz, jlong nativeTransformManager) {
    TransformManager const * const that = (TransformManager const *) nativeTransformManager;
    return (jboolean)that->empty();
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_TransformManager_nGetEntity(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jint i) {
    TransformManager const * const that = (TransformManager const *) nativeTransformManager;
    return (jint)Entity::smuggle(that->getEntity(EntityInstance<TransformManager>(i)));
}

extern "C" JNIEXPORT jintArray JNICALL
Java_com_google_android_filament_TransformManager_nGetAllEntities(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jintArray out_) {
    TransformManager const * const that = (TransformManager const *) nativeTransformManager;
    auto const slice = that->getAllEntities();
    jsize const count = static_cast<jsize>(slice.size());
    if (out_ == nullptr || env->GetArrayLength(out_) < count) {
        out_ = env->NewIntArray(count);
    }
    if (count > 0) {
        env->SetIntArrayRegion(out_, 0, count, reinterpret_cast<const jint*>(slice.data()));
    }
    return out_;
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_TransformManager_nSetAccurateTranslationsEnabled(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jboolean enable) {
    TransformManager* const that = (TransformManager*) nativeTransformManager;
    that->setAccurateTranslationsEnabled((bool)enable);
}

extern "C" JNIEXPORT jboolean JNICALL
Java_com_google_android_filament_TransformManager_nIsAccurateTranslationsEnabled(JNIEnv *env, jclass clazz, jlong nativeTransformManager) {
    TransformManager const * const that = (TransformManager const *) nativeTransformManager;
    return (jboolean)that->isAccurateTranslationsEnabled();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_TransformManager_nCreate__JII_3F(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jint entity, jint parent, jfloatArray localTransform_) {
    TransformManager* const that = (TransformManager*) nativeTransformManager;
    jfloat const * const localTransform = env->GetFloatArrayElements(localTransform_, nullptr);
    wrapJni(env, [=]() {
        that->create(Entity::import(entity), EntityInstance<TransformManager>(parent), *reinterpret_cast<mat4f const *>(localTransform));
    });
    env->ReleaseFloatArrayElements(localTransform_, const_cast<jfloat *>(localTransform), JNI_ABORT);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_TransformManager_nCreate__JII_3D(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jint entity, jint parent, jdoubleArray localTransform_) {
    TransformManager* const that = (TransformManager*) nativeTransformManager;
    jdouble const * const localTransform = env->GetDoubleArrayElements(localTransform_, nullptr);
    wrapJni(env, [=]() {
        that->create(Entity::import(entity), EntityInstance<TransformManager>(parent), *reinterpret_cast<mat4 const *>(localTransform));
    });
    env->ReleaseDoubleArrayElements(localTransform_, const_cast<jdouble *>(localTransform), JNI_ABORT);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_TransformManager_nCreate__JII(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jint entity, jint parent) {
    TransformManager* const that = (TransformManager*) nativeTransformManager;
    wrapJni(env, [=]() {
        that->create(Entity::import(entity), EntityInstance<TransformManager>(parent));
    });
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_TransformManager_nDestroy(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jint e) {
    TransformManager* const that = (TransformManager*) nativeTransformManager;
    that->destroy(Entity::import(e));
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_TransformManager_nSetParent(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jint i, jint newParent) {
    TransformManager* const that = (TransformManager*) nativeTransformManager;
    that->setParent(EntityInstance<TransformManager>(i), EntityInstance<TransformManager>(newParent));
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_TransformManager_nGetParent(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jint i) {
    TransformManager const * const that = (TransformManager const *) nativeTransformManager;
    return (jint)Entity::smuggle(that->getParent(EntityInstance<TransformManager>(i)));
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_TransformManager_nGetChildCount(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jint i) {
    TransformManager const * const that = (TransformManager const *) nativeTransformManager;
    return (jint)that->getChildCount(EntityInstance<TransformManager>(i));
}

extern "C" JNIEXPORT jint JNICALL
Java_com_google_android_filament_TransformManager_nGetChildren(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jint i, jintArray children_, jint count) {
    TransformManager const * const that = (TransformManager const *) nativeTransformManager;
    jint * children = env->GetIntArrayElements(children_, nullptr);
    jint const result = (jint)that->getChildren(EntityInstance<TransformManager>(i), (Entity *)children, (size_t)count);
    env->ReleaseIntArrayElements(children_, children, 0);
    return result;
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_TransformManager_nSetTransform__JI_3F(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jint ci, jfloatArray localTransform_) {
    TransformManager* const that = (TransformManager*) nativeTransformManager;
    jfloat const * const localTransform = env->GetFloatArrayElements(localTransform_, nullptr);
    that->setTransform(EntityInstance<TransformManager>(ci), *reinterpret_cast<mat4f const *>(localTransform));
    env->ReleaseFloatArrayElements(localTransform_, const_cast<jfloat *>(localTransform), JNI_ABORT);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_TransformManager_nSetTransform__JI_3D(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jint ci, jdoubleArray localTransform_) {
    TransformManager* const that = (TransformManager*) nativeTransformManager;
    jdouble const * const localTransform = env->GetDoubleArrayElements(localTransform_, nullptr);
    that->setTransform(EntityInstance<TransformManager>(ci), *reinterpret_cast<mat4 const *>(localTransform));
    env->ReleaseDoubleArrayElements(localTransform_, const_cast<jdouble *>(localTransform), JNI_ABORT);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_TransformManager_nGetTransform(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jint ci, jfloatArray out_) {
    TransformManager const * const that = (TransformManager const *) nativeTransformManager;
    jfloat *out = env->GetFloatArrayElements(out_, nullptr);
    *reinterpret_cast<mat4f *>(out) = that->getTransform(EntityInstance<TransformManager>(ci));
    env->ReleaseFloatArrayElements(out_, out, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_TransformManager_nGetTransformAccurate(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jint ci, jdoubleArray out_) {
    TransformManager const * const that = (TransformManager const *) nativeTransformManager;
    jdouble *out = env->GetDoubleArrayElements(out_, nullptr);
    *reinterpret_cast<mat4 *>(out) = that->getTransformAccurate(EntityInstance<TransformManager>(ci));
    env->ReleaseDoubleArrayElements(out_, out, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_TransformManager_nGetWorldTransform(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jint ci, jfloatArray out_) {
    TransformManager const * const that = (TransformManager const *) nativeTransformManager;
    jfloat *out = env->GetFloatArrayElements(out_, nullptr);
    *reinterpret_cast<mat4f *>(out) = that->getWorldTransform(EntityInstance<TransformManager>(ci));
    env->ReleaseFloatArrayElements(out_, out, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_TransformManager_nGetWorldTransformAccurate(JNIEnv *env, jclass clazz, jlong nativeTransformManager, jint ci, jdoubleArray out_) {
    TransformManager const * const that = (TransformManager const *) nativeTransformManager;
    jdouble *out = env->GetDoubleArrayElements(out_, nullptr);
    *reinterpret_cast<mat4 *>(out) = that->getWorldTransformAccurate(EntityInstance<TransformManager>(ci));
    env->ReleaseDoubleArrayElements(out_, out, 0);
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_TransformManager_nOpenLocalTransformTransaction(JNIEnv *env, jclass clazz, jlong nativeTransformManager) {
    TransformManager* const that = (TransformManager*) nativeTransformManager;
    that->openLocalTransformTransaction();
}

extern "C" JNIEXPORT void JNICALL
Java_com_google_android_filament_TransformManager_nCommitLocalTransformTransaction(JNIEnv *env, jclass clazz, jlong nativeTransformManager) {
    TransformManager* const that = (TransformManager*) nativeTransformManager;
    that->commitLocalTransformTransaction();
}

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.
