baseURL = "https://google.github.io/filament/"
languageCode = "en-us"
title = "Filament"
theme = "hyde"
publishDir = "../docs"

[params]
themeColor = "theme-base-0d"
description = "lightweight PBR"
github = "https://github.com/google/filament"
mainImage = "https://google.github.io/filament/images/filament_logo_small.png"

[menu]

  [[menu.main]]
    identifier = "github"
    name = "GitHub Project"
    url = "https://github.com/google/filament"
    weight = -110
