name: hello-pbr
options:
    bundleIdPrefix: ${SAMPLE_CODE_DISAMBIGUATOR}.google.filament
include: ../app-template.yml
targets:
    hello-pbr:
        templates:
            - FilamentApp
        settings:
            base:
                OTHER_LDFLAGS: ["-lfilameshio", "-lmeshoptimizer", "-limage"]
        preBuildScripts:
            - path: build-resources.sh
              name: Build Resources
