name: hello-pbr
options:
    bundleIdPrefix: ${SAMPLE_CODE_DISAMBIGUATOR}.google.filament
include: ../app-template.yml
targets:
    hello-pbr:
        templates:
            - FilamentApp
        dependencies:
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libfilameshio.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libmeshoptimizer.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libimage.xcframework
        preBuildScripts:
            - path: build-resources.sh
              name: Build Resources
