name: 'Linux Preqrequisites'
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/dep-versions
    - name: Install Linux Prerequisites
      shell: bash
      run: |
        set -xe
        # See https://askubuntu.com/questions/272248/processing-triggers-for-man-db/1476024#1476024
        echo "set man-db/auto-update false" | sudo debconf-communicate
        sudo dpkg-reconfigure man-db

        cd ..

        sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install clang-$GITHUB_CLANG_VERSION libc++-$GITHUB_CLANG_VERSION-dev libc++abi-$GITHUB_CLANG_VERSION-dev
        sudo apt-get install mesa-common-dev libxi-dev libxxf86vm-dev
        sudo apt-get install cmake ninja-build

        # For dawn
        sudo apt-get install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libx11-xcb-dev

        sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-${GITHUB_CLANG_VERSION} 100
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-${GITHUB_CLANG_VERSION} 100
        set +xe
