name: hello-gltf
options:
    bundleIdPrefix: google.filament
include: ../app-template.yml
targets:
    hello-gltf:
        sources: hello-gltf/
        sources:
            - path: '../../../third_party/models/DamagedHelmet/DamagedHelmet.glb'
              buildPhase: resources
        templates:
            - FilamentApp
        settings:
            base:
                OTHER_LDFLAGS: ["-lgltfio_core", "-lgltfio_resources", "-limage", "-lgeometry", "-ldracodec"]
        preBuildScripts:
            - path: build-resources.sh
              name: Build Resources
