name: hello-gltf
options:
    bundleIdPrefix: ${SAMPLE_CODE_DISAMBIGUATOR}.google.filament
include: ../app-template.yml
targets:
    hello-gltf:
        sources: hello-gltf/
        sources:
            - path: '../../../third_party/models/DamagedHelmet/DamagedHelmet.glb'
              buildPhase: resources
        templates:
            - FilamentApp
        dependencies:
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libgltfio_core.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libuberarchive.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libimage.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libstb.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libbasis_transcoder.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libzstd.xcframework            
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libdracodec.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libmeshoptimizer.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libuberzlib.xcframework        
        preBuildScripts:
            - path: build-resources.sh
              name: Build Resources
