name: backend-test
options:
    bundleIdPrefix: ${SAMPLE_CODE_DISAMBIGUATOR}.google.filament
include: ../app-template.yml
targets:
    backend-test:
        templates:
            - FilamentApp
        dependencies:
            - framework: "$(FILAMENT_LIB_DIR)/libbackend_test.xcframework"
            - framework: "$(FILAMENT_LIB_DIR)/libfilamat.xcframework"
        settings:
            base:
                # Because each test case is a separate file, the -force_load flag is necessary to prevent the
                # linker from removing "unused" symbols.
                OTHER_LDFLAGS[sdk=iphoneos*]: ["-Wl,-force_load,$(FILAMENT_LIB_DIR)/libbackend_test.xcframework/ios-arm64/libbackend_test.a"]
                # When built with -s we generate a universal sim slice and xcodebuild names it like this.
                OTHER_LDFLAGS[sdk=iphonesimulator*]: ["-Wl,-force_load,$(FILAMENT_LIB_DIR)/libbackend_test.xcframework/ios-arm64_x86_64-simulator/libbackend_test.a"]
