name: backend-test
options:
    bundleIdPrefix: google.filament
include: ../app-template.yml
targets:
    backend-test:
        templates:
            - FilamentApp
        settings:
            base:
                # Because each test case is a separate file, the -force_load flag is necessary to prevent the
                # linker from removing "unused" symbols.
                OTHER_LDFLAGS: ["-force_load ../../../out/ios-debug/filament/lib/arm64/libbackend_test.a"]
