name: backend-test
options:
    bundleIdPrefix: ${SAMPLE_CODE_DISAMBIGUATOR}.google.filament
include: ../app-template.yml
targets:
    backend-test:
        templates:
            - FilamentApp
        dependencies:
            - framework: ../../../out/$(FILAMENT_OUT_NAME)/filament/lib/libfilamat.xcframework
        settings:
            base:
                # Because each test case is a separate file, the -force_load flag is necessary to prevent the
                # linker from removing "unused" symbols.
                OTHER_LDFLAGS: ["-force_load $(SRCROOT)/../../../out/$(FILAMENT_OUT_NAME)/filament/lib/$(CURRENT_ARCH)-$(PLATFORM_NAME)/libbackend_test.a"]
