name: gltf-viewer
options:
    bundleIdPrefix: ${SAMPLE_CODE_DISAMBIGUATOR}.google.filament
include: ../app-template.yml
targets:
    gltf-viewer:
        sources: gltf-viewer/
        sources:
            - path: '../../../third_party/models/BusterDrone'
              type: folder
              buildPhase: resources
            - path: 'generated/default_env/default_env_ibl.ktx'
              buildPhase: resources
              optional: true
            - path: 'generated/default_env/default_env_skybox.ktx'
              buildPhase: resources
              optional: true
        templates:
            - FilamentApp
        dependencies:
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libgltfio_core.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libuberarchive.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libimage.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libstb.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libbasis_transcoder.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libzstd.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libcamutils.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libdracodec.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libmeshoptimizer.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libviewer.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libcivetweb.xcframework
            - framework: $(SRCROOT)/../../../out/ios-release/filament/lib/libuberzlib.xcframework

        preBuildScripts:
            - path: build-resources.sh
              name: Build Resources
              inputFiles:
                - $(SRCROOT)/../../../third_party/environments/lightroom_14b.hdr
              outputFiles:
                - $(SRCROOT)/generated/default_env/default_env_ibl.ktx
                - $(SRCROOT)/generated/default_env/default_env_skybox.ktx
