name: gltf-viewer
options:
    bundleIdPrefix: ${SAMPLE_CODE_DISAMBIGUATOR}.google.filament
include: ../app-template.yml
targets:
    gltf-viewer:
        sources: gltf-viewer/
        sources:
            - path: '../../../third_party/models/BusterDrone'
              type: folder
              buildPhase: resources
            - path: 'generated/default_env/default_env_ibl.ktx'
              buildPhase: resources
              optional: true
            - path: 'generated/default_env/default_env_skybox.ktx'
              buildPhase: resources
              optional: true
        templates:
            - FilamentApp
        dependencies:
            - framework: "$(FILAMENT_LIB_DIR)/libgltfio_core.xcframework"
            - framework: "$(FILAMENT_LIB_DIR)/libuberarchive.xcframework"
            - framework: "$(FILAMENT_LIB_DIR)/libimage.xcframework"
            - framework: "$(FILAMENT_LIB_DIR)/libstb.xcframework"
            - framework: "$(FILAMENT_LIB_DIR)/libbasis_transcoder.xcframework"
            - framework: "$(FILAMENT_LIB_DIR)/libzstd.xcframework"
            - framework: "$(FILAMENT_LIB_DIR)/libcamutils.xcframework"
            - framework: "$(FILAMENT_LIB_DIR)/libdracodec.xcframework"
            - framework: "$(FILAMENT_LIB_DIR)/libmeshoptimizer.xcframework"
            - framework: "$(FILAMENT_LIB_DIR)/libviewer.xcframework"
            - framework: "$(FILAMENT_LIB_DIR)/libcivetweb.xcframework"
            - framework: "$(FILAMENT_LIB_DIR)/libuberzlib.xcframework"
        preBuildScripts:
            - path: build-resources.sh
              name: Build Resources
              inputFiles:
                - $(SRCROOT)/../../../third_party/environments/lightroom_14b.hdr
              outputFiles:
                - $(SRCROOT)/generated/default_env/default_env_ibl.ktx
                - $(SRCROOT)/generated/default_env/default_env_skybox.ktx
