/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.

package com.google.android.filament;

import java.lang.IllegalStateException;

import java.nio.Buffer;
import java.nio.BufferOverflowException;

import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.RestrictTo;

/**
 * A generic GPU buffer containing data.
 *
 * <p>Usage of this BufferObject is optional. For simple use cases it is not necessary. It is useful
 * only when you need to share data between multiple VertexBuffer instances. It also allows you to
 * efficiently swap-out the buffers in VertexBuffer.</p>
 *
 * <p>NOTE: For now this is only used for vertex data, but in the future we may use it for other things
 * (e.g. compute).</p>
 *
 * @see VertexBuffer
 */
public class BufferObject {
    private long mNativeObject;

    /** Buffer object binding type */
    public enum BindingType {
        VERTEX,
        UNIFORM,
        SHADER_STORAGE;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    BufferObject(long nativeObject) {
        mNativeObject = nativeObject;
    }

    @NonNull
    @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
    public static BufferObject wrap(long nativeObject) {
        return new BufferObject(nativeObject);
    }

    public static class Builder {
        @SuppressWarnings({"FieldCanBeLocal", "UnusedDeclaration"}) // Keep to finalize native resources
        private final BuilderFinalizer mFinalizer;
        private final long mNativeBuilder;

        public Builder() {
            mNativeBuilder = nCreateBuilder();
            mFinalizer = new BuilderFinalizer(mNativeBuilder);
        }

        long getNativeBuilder() {
            return mNativeBuilder;
        }

        /**
         * Size of the buffer in bytes.
         *
         * @param byteCount Maximum number of bytes the BufferObject can hold.
         *
         * @return A reference to this Builder for chaining calls.
         */
        @NonNull
        public Builder size(@IntRange(from = 0) int byteCount) {
            nBuilderSize(mNativeBuilder, byteCount);
            return this;
        }

        /**
         * The binding type for this buffer object. (defaults to VERTEX)
         *
         * @param bindingType Distinguishes between SSBO, VBO, etc. For now this must be VERTEX.
         *
         * @return A reference to this Builder for chaining calls.
         */
        @NonNull
        public Builder bindingType(@NonNull BindingType bindingType) {
            nBuilderBindingType(mNativeBuilder, bindingType.toFilamentNative());
            return this;
        }

        /**
         * Associate an optional name with this BufferObject for debugging purposes.
         *
         * <p>This method should be avoided in C++ in favor of the {@code StaticString} overload.
         * It is provided primarily for bindings to other languages.</p>
         *
         * @param name A string to identify this BufferObject
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder name(@NonNull String name) {
            nBuilderName(mNativeBuilder, name);
            return this;
        }

        /**
         * Creates the BufferObject and returns a pointer to it.
         *
         * <p>After creation, the buffer
         * object is uninitialized. Use BufferObject::setBuffer() to initialize it.</p>
         *
         * @param engine Reference to the filament::Engine to associate this BufferObject with.
         *
         * @return pointer to the newly created object
         *
         * @see IndexBuffer#setBuffer
         */
        @NonNull
        public BufferObject build(@NonNull Engine engine) {
            long nativeBufferObject = nBuilderBuild(mNativeBuilder, engine.getNativeObject());
            if (nativeBufferObject == 0) throw new IllegalStateException("Couldn't create BufferObject");
            return new BufferObject(nativeBufferObject);
        }

        private static class BuilderFinalizer {
            private final long mNativeObject;

            BuilderFinalizer(long nativeObject) { mNativeObject = nativeObject; }

            @Override
            public void finalize() {
                try {
                    super.finalize();
                } catch (Throwable t) { // Ignore
                } finally {
                    nDestroyBuilder(mNativeObject);
                }
            }
        }
    }

    /**
     * Asynchronously copy-initializes a region of this BufferObject from the data provided.
     *
     * @param engine Reference to the filament::Engine associated with this BufferObject.
     * @param buffer A BufferDescriptor representing the data used to initialize the BufferObject.
     */
    public void setBuffer(@NonNull Engine engine, @NonNull Buffer buffer) {
        setBuffer(engine, buffer, 0, 0, null, null);
    }

    /**
     * Asynchronously copy-initializes a region of this BufferObject from the data provided.
     *
     * @param engine Reference to the filament::Engine associated with this BufferObject.
     * @param buffer A BufferDescriptor representing the data used to initialize the BufferObject.
     * @param destOffsetInBytes Offset in bytes into the BufferObject. Must be multiple of 4.
     * @param count number of bytes to copy
     */
    public void setBuffer(@NonNull Engine engine, @NonNull Buffer buffer,
            @IntRange(from = 0) int destOffsetInBytes, @IntRange(from = 0) int count) {
        setBuffer(engine, buffer, destOffsetInBytes, count, null, null);
    }

    /**
     * Asynchronously copy-initializes a region of this BufferObject from the data provided.
     *
     * @param engine Reference to the filament::Engine associated with this BufferObject.
     * @param buffer A BufferDescriptor representing the data used to initialize the BufferObject.
     * @param destOffsetInBytes Offset in bytes into the BufferObject. Must be multiple of 4.
     * @param count number of bytes to copy
     * @param handler handler to dispatch the callback or null for the default handler
     * @param callback runnable called upon completion of the operation
     */
    public void setBuffer(@NonNull Engine engine, @NonNull Buffer buffer,
            @IntRange(from = 0) int destOffsetInBytes, @IntRange(from = 0) int count,
            @Nullable Object handler, @Nullable Runnable callback) {
        int result = nSetBuffer(getNativeObject(), engine.getNativeObject(), buffer, buffer.remaining(),
                destOffsetInBytes, count == 0 ? buffer.remaining() : count, handler, callback);
        if (result < 0) {
            throw new BufferOverflowException();
        }
    }

    /**
     * Returns the size of this BufferObject in elements.
     *
     * @return The maximum capacity of the BufferObject.
     */
    @IntRange(from = 0)
    public int getByteCount() {
        return nGetByteCount(getNativeObject());
    }

    public long getNativeObject() {
        if (mNativeObject == 0) {
            throw new IllegalStateException("Calling method on destroyed BufferObject");
        }
        return mNativeObject;
    }

    void clearNativeObject() {
        mNativeObject = 0;
    }

    private static native int nSetBuffer(long nativeBufferObject, long nativeEngine, Buffer buffer, int remaining, int destOffsetInBytes, int count, Object handler, Runnable callback);
    @IntRange(from = 0)
    private static native int nGetByteCount(long nativeBufferObject);
    private static native long nCreateBuilder();
    private static native void nDestroyBuilder(long nativeBuilder);
    private static native void nBuilderSize(long nativeBuilder, int byteCount);
    private static native void nBuilderBindingType(long nativeBuilder, int bindingType);
    private static native void nBuilderName(long nativeBuilder, String name);
    private static native long nBuilderBuild(long nativeBuilder, long nativeEngine);
}

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.
