/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.

package com.google.android.filament;

import java.lang.IllegalStateException;

import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.RestrictTo;
import androidx.annotation.Size;

/**
 * IndirectLight is used to simulate environment lighting, a form of global illumination.
 *
 * <p>Environment lighting has a two components:</p>
 *
 * <ol>
 *   <li>irradiance</li>
 *   <li>reflections (specular component)
 * Environments are usually captured as high-resolution HDR equirectangular images and processed
 * by the <b>cmgen</b> tool to generate the data needed by IndirectLight.</li>
 * </ol>
 *
 * <h1>Creation and destruction</h1>
 *
 * <p>An IndirectLight object is created using the IndirectLight::Builder and destroyed by calling
 * Engine::destroy(const IndirectLight*).</p>
 *
 * <pre>{@code
 *  filament::Engine* engine = filament::Engine::create();
 *
 *  filament::IndirectLight* environment = filament::IndirectLight::Builder()
 *              .reflections(cubemap)
 *              .build(*engine);
 *
 *  engine->destroy(environment);
 *
 * }</pre>
 *
 * <h1>Irradiance</h1>
 *
 * <p>The irradiance represents the light that comes from the environment and shines an
 * object's surface.</p>
 *
 * <p>The irradiance is calculated automatically from the Reflections (see below), and generally
 * doesn't need to be provided explicitly.  However, it can be provided separately from the
 * Reflections as
 * <a href="https://en.wikipedia.org/wiki/Spherical_harmonics">spherical harmonics</a> (SH) of 1, 2 or
 * 3 bands, respectively 1, 4 or 9 coefficients.</p>
 *
 * <h1>Reflections</h1>
 *
 * <p>The reflections on object surfaces (specular component) is calculated from a specially
 * filtered cubemap pyramid generated by the <b>cmgen</b> tool.</p>
 *
 * <p>Currently IndirectLight is intended to be used for "distant probes", that is, to represent
 * global illumination from a distant (i.e. at infinity) environment, such as the sky or distant
 * mountains. Only a single IndirectLight can be used in a Scene. This limitation will be lifted
 * in the future.</p>
 *
 * <p>Use the <b>cmgen</b> tool to generate the {@code SH} for a given environment.</p>
 *
 * @see Scene
 * @see Light
 * @see Texture
 * @see Skybox
 */
public class IndirectLight {
    private long mNativeObject;

    IndirectLight(long nativeObject) {
        mNativeObject = nativeObject;
    }

    @NonNull
    @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
    public static IndirectLight wrap(long nativeObject) {
        return new IndirectLight(nativeObject);
    }

    /** Use Builder to construct an IndirectLight object instance */
    public static class Builder {
        @SuppressWarnings({"FieldCanBeLocal", "UnusedDeclaration"}) // Keep to finalize native resources
        private final BuilderFinalizer mFinalizer;
        private final long mNativeBuilder;

        public Builder() {
            mNativeBuilder = nCreateBuilder();
            mFinalizer = new BuilderFinalizer(mNativeBuilder);
        }

        long getNativeBuilder() {
            return mNativeBuilder;
        }

        /**
         * Set the reflections cubemap mipmap chain.
         *
         * @param cubemap A mip-mapped cubemap generated by <b>cmgen</b>. Each cubemap level
         *                  encodes a the irradiance for a roughness level.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder reflections(@Nullable Texture cubemap) {
            nBuilderReflections(mNativeBuilder, cubemap != null ? cubemap.getNativeObject() : 0);
            return this;
        }

        /**
         * Sets the irradiance as Spherical Harmonics.
         *
         * <p>The irradiance must be pre-convolved by ⟨ n · l ⟩ and
         * pre-multiplied by the Lambertian diffuse BRDF 1 / π and
         * specified as Spherical Harmonics coefficients.</p>
         *
         * <p>Additionally, these Spherical Harmonics coefficients must be pre-scaled by the
         * reconstruction factors A<sub>l</sub><sup>m</sup> below.</p>
         *
         * <p>The final coefficients can be generated using the {@code cmgen} tool.</p>
         *
         * <p>The index in the {@code sh} array is given by:</p>
         *
         * <p>{@code index(l, m) = l * (l + 1) + m}</p>
         *
         * <p>sh[index(l,m)] = L<sub>l</sub><sup>m</sup> 1 / π A<sub>l</sub><sup>m</sup> C<sub>l</sub></p>
         *
         * <table summary="">
         *   <tr>
         *     <th style="text-align: center">index</th>
         *     <th style="text-align: center">l</th>
         *     <th style="text-align: center">m</th>
         *     <th style="text-align: center">A<sub>l</sub><sup>m</sup></th>
         *     <th style="text-align: center">C<sub>l</sub></th>
         *     <th style="text-align: center">1 / π A<sub>l</sub><sup>m</sup>C<sub>l</sub></th>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">0</td>
         *     <td style="text-align: center">0</td>
         *     <td style="text-align: center">0</td>
         *     <td style="text-align: center">0.282095</td>
         *     <td style="text-align: center">3.1415926</td>
         *     <td style="text-align: center">0.282095</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">1</td>
         *     <td style="text-align: center">1</td>
         *     <td style="text-align: center">-1</td>
         *     <td style="text-align: center">-0.488602</td>
         *     <td style="text-align: center">2.0943951</td>
         *     <td style="text-align: center">-0.325735</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">2</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">0</td>
         *     <td style="text-align: center">0.488602</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">0.325735</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">3</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">1</td>
         *     <td style="text-align: center">-0.488602</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">-0.325735</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">4</td>
         *     <td style="text-align: center">2</td>
         *     <td style="text-align: center">-2</td>
         *     <td style="text-align: center">1.092548</td>
         *     <td style="text-align: center">0.785398</td>
         *     <td style="text-align: center">0.273137</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">5</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">-1</td>
         *     <td style="text-align: center">-1.092548</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">-0.273137</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">6</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">0</td>
         *     <td style="text-align: center">0.315392</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">0.078848</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">7</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">1</td>
         *     <td style="text-align: center">-1.092548</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">-0.273137</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">8</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">2</td>
         *     <td style="text-align: center">0.546274</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">0.136569</td>
         *   </tr>
         * </table>
         *
         * <p>Only 1, 2 or 3 bands are allowed.</p>
         *
         * <p>Because the coefficients are pre-scaled, {@code sh[0]} is the environment's
         * average irradiance.</p>
         *
         * @param bands Number of spherical harmonics bands. Must be 1, 2 or 3.
         * @param sh Array containing the spherical harmonics coefficients.
         *                  The size of the array must be bands<sup>2</sup>.
         *                  (i.e. 1, 4 or 9 coefficients respectively).
         *
         * @return This Builder, for chaining calls.
         *
         * @see Material.Builder#sphericalHarmonicsBandCount
         */
        @NonNull
        public Builder irradiance(@IntRange(from = 0) int bands, @NonNull @Size(min = 3) float[] sh) {
            nBuilderIrradiance(mNativeBuilder, bands, sh);
            return this;
        }

        /**
         * Sets the irradiance from the radiance expressed as Spherical Harmonics.
         *
         * <p>The radiance must be specified as Spherical Harmonics coefficients L<sub>l</sub><sup>m</sup></p>
         *
         * <p>The index in the {@code sh} array is given by:</p>
         *
         * <p>{@code index(l, m) = l * (l + 1) + m}</p>
         *
         * <p>sh[index(l,m)] = L<sub>l</sub><sup>m</sup></p>
         *
         * <table summary="">
         *   <tr>
         *     <th style="text-align: center">index</th>
         *     <th style="text-align: center">l</th>
         *     <th style="text-align: center">m</th>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">0</td>
         *     <td style="text-align: center">0</td>
         *     <td style="text-align: center">0</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">1</td>
         *     <td style="text-align: center">1</td>
         *     <td style="text-align: center">-1</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">2</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">0</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">3</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">1</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">4</td>
         *     <td style="text-align: center">2</td>
         *     <td style="text-align: center">-2</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">5</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">-1</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">6</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">0</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">7</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">1</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: center">8</td>
         *     <td style="text-align: center">^</td>
         *     <td style="text-align: center">2</td>
         *   </tr>
         * </table>
         *
         * @param bands Number of spherical harmonics bands. Must be 1, 2 or 3.
         * @param sh Array containing the spherical harmonics coefficients.
         *                  The size of the array must be bands<sup>2</sup>.
         *                  (i.e. 1, 4 or 9 coefficients respectively).
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder radiance(@IntRange(from = 0) int bands, @NonNull @Size(min = 3) float[] sh) {
            nBuilderRadiance(mNativeBuilder, bands, sh);
            return this;
        }

        /**
         * Sets the irradiance as a cubemap.
         *
         * <p>The irradiance can alternatively be specified as a cubemap instead of Spherical
         * Harmonics coefficients. It may or may not be more efficient, depending on your
         * hardware (essentially, it's trading ALU for bandwidth).</p>
         *
         * <p>This irradiance cubemap can be generated with the <b>cmgen</b> tool.</p>
         *
         * @param cubemap Cubemap representing the Irradiance pre-convolved by
         *                  ⟨ n · l ⟩.
         *
         * @return This Builder, for chaining calls.
         *
         * @see #irradiance(int, float[])
         */
        @NonNull
        public Builder irradiance(@Nullable Texture cubemap) {
            nBuilderIrradiance(mNativeBuilder, cubemap != null ? cubemap.getNativeObject() : 0);
            return this;
        }

        /**
         * (optional) Environment intensity.
         *
         * <p>Because the environment is encoded usually relative to some reference, the
         * range can be adjusted with this method.</p>
         *
         * @param envIntensity Scale factor applied to the environment and irradiance such that
         *                      the result is in lux, or lumen/m^2 (default = 30000)
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder intensity(float envIntensity) {
            nBuilderIntensity(mNativeBuilder, envIntensity);
            return this;
        }

        /**
         * Specifies the rigid-body transformation to apply to the IBL.
         *
         * @param rotation 3x3 rotation matrix. Must be a rigid-body transform.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder rotation(@NonNull @Size(min = 9) float[] rotation) {
            nBuilderRotation(mNativeBuilder, rotation);
            return this;
        }

        /**
         * Creates the IndirectLight object and returns a pointer to it.
         *
         * @param engine Reference to the filament::Engine to associate this IndirectLight with.
         *
         * @return pointer to the newly created object or nullptr if exceptions are disabled and
         *         an error occurred.
         */
        @NonNull
        public IndirectLight build(@NonNull Engine engine) {
            long nativeIndirectLight = nBuilderBuild(mNativeBuilder, engine.getNativeObject());
            if (nativeIndirectLight == 0) throw new IllegalStateException("Couldn't create IndirectLight");
            return new IndirectLight(nativeIndirectLight);
        }

        private static class BuilderFinalizer {
            private final long mNativeObject;

            BuilderFinalizer(long nativeObject) { mNativeObject = nativeObject; }

            @Override
            public void finalize() {
                try {
                    super.finalize();
                } catch (Throwable t) { // Ignore
                } finally {
                    nDestroyBuilder(mNativeObject);
                }
            }
        }
    }

    /**
     * Sets the environment's intensity.
     *
     * <p>Because the environment is encoded usually relative to some reference, the
     * range can be adjusted with this method.</p>
     *
     * @param intensity Scale factor applied to the environment and irradiance such that
     *                   the result is in lux, or <i>lumen/m^2</i> (default = 30000)
     */
    public void setIntensity(float intensity) {
        nSetIntensity(getNativeObject(), intensity);
    }

    /** Returns the environment's intensity in <i>lux</i>, or <i>lumen/m^2</i>. */
    public float getIntensity() {
        return nGetIntensity(getNativeObject());
    }

    /**
     * Sets the rigid-body transformation to apply to the IBL.
     *
     * @param rotation 3x3 rotation matrix. Must be a rigid-body transform.
     */
    public void setRotation(@NonNull @Size(min = 9) float[] rotation) {
        Asserts.assertMat3fIn(rotation);
        nSetRotation(getNativeObject(), rotation);
    }

    /** Returns the rigid-body transformation applied to the IBL. */
    @NonNull @Size(min = 9)
    public float[] getRotation(@Nullable @Size(min = 9) float[] out) {
        out = Asserts.assertMat3f(out);
        nGetRotation(getNativeObject(), out);
        return out;
    }

    /** Returns the associated reflection map, or null if it does not exist. */
    public Texture getReflectionsTexture() {
        long nativeTexture = nGetReflectionsTexture(getNativeObject());
        return nativeTexture == 0 ? null : new Texture(nativeTexture);
    }

    /** Returns the associated irradiance map, or null if it does not exist. */
    public Texture getIrradianceTexture() {
        long nativeTexture = nGetIrradianceTexture(getNativeObject());
        return nativeTexture == 0 ? null : new Texture(nativeTexture);
    }

    /**
     * Helper to estimate the direction of the dominant light in the environment represented by spherical harmonics.
     *
     * <p>This assumes that there is only a single dominant light (such as the sun in outdoors
     * environments), if it's not the case the direction returned will be an average of the
     * various lights based on their intensity.</p>
     *
     * <p>If there are no clear dominant light, as is often the case with low dynamic range (LDR)
     * environments, this method may return a wrong or unexpected direction.</p>
     *
     * <p>The dominant light direction can be used to set a directional light's direction,
     * for instance to produce shadows that match the environment.</p>
     *
     * @param sh 3-band spherical harmonics
     *
     * @return A unit vector representing the direction of the dominant light
     *
     * @see LightManager.Builder#direction
     * @see #getColorEstimate
     */
    @NonNull @Size(min = 3)
    public static float[] getDirectionEstimate(@Size(min = 3) float[] sh, @Nullable @Size(min = 3) float[] out) {
        if (sh != null) {
            Asserts.assertFloat3In(sh);
        }
        out = Asserts.assertFloat3(out);
        nGetDirectionEstimate(sh, out);
        return out;
    }

    /**
     * Helper to estimate the color and relative intensity of the environment represented by spherical harmonics in a given direction.
     *
     * <p>This can be used to set the color and intensity of a directional light. In this case
     * make sure to multiply this relative intensity by the the intensity of this indirect light.</p>
     *
     * @param sh 3-band spherical harmonics
     * @param direction a unit vector representing the direction of the light to estimate the
     *                  color of. Typically this the value returned by getDirectionEstimate().
     *
     * @return A vector of 4 floats where the first 3 components represent the linear color and
     *         the 4th component represents the intensity of the dominant light
     *
     * @see LightManager.Builder#color
     * @see LightManager.Builder#intensity
     * @see #getDirectionEstimate
     * @see #getIntensity
     * @see #setIntensity
     */
    @NonNull @Size(min = 4)
    public static float[] getColorEstimate(float[] sh, @NonNull @Size(min = 3) float[] direction, @Nullable @Size(min = 4) float[] out) {
        return getColorEstimate(sh, direction[0], direction[1], direction[2], out);
    }

    /**
     * Helper to estimate the color and relative intensity of the environment represented by spherical harmonics in a given direction.
     *
     * <p>This can be used to set the color and intensity of a directional light. In this case
     * make sure to multiply this relative intensity by the the intensity of this indirect light.</p>
     *
     * @param sh 3-band spherical harmonics
     * @param directionx (x component) a unit vector representing the direction of the light to estimate the
     *                  color of. Typically this the value returned by getDirectionEstimate().
     * @param directiony (y component) a unit vector representing the direction of the light to estimate the
     *                  color of. Typically this the value returned by getDirectionEstimate().
     * @param directionz (z component) a unit vector representing the direction of the light to estimate the
     *                  color of. Typically this the value returned by getDirectionEstimate().
     *
     * @return A vector of 4 floats where the first 3 components represent the linear color and
     *         the 4th component represents the intensity of the dominant light
     *
     * @see LightManager.Builder#color
     * @see LightManager.Builder#intensity
     * @see #getDirectionEstimate
     * @see #getIntensity
     * @see #setIntensity
     */
    @NonNull @Size(min = 4)
    public static float[] getColorEstimate(@Size(min = 3) float[] sh, float directionx, float directiony, float directionz, @Nullable @Size(min = 4) float[] out) {
        if (sh != null) {
            Asserts.assertFloat3In(sh);
        }
        out = Asserts.assertFloat4(out);
        nGetColorEstimate(sh, directionx, directiony, directionz, out);
        return out;
    }

    /**
     * Helper to estimate the direction of the dominant light in the environment represented by spherical harmonics.
     *
     * <p>Spherical harmonics must be set in the Builder or the result is undefined.</p>
     *
     * @see #getDirectionEstimate(float[])
     * @see Builder#irradiance(int, float[])
     * @see Builder#radiance(int, float[])
     */
    @NonNull @Size(min = 3)
    public float[] getDirectionEstimate(@Nullable @Size(min = 3) float[] out) {
        out = Asserts.assertFloat3(out);
        nGetDirectionEstimate(getNativeObject(), out);
        return out;
    }

    /**
     * Helper to estimate the color and relative intensity of the environment represented by spherical harmonics in a given direction.
     *
     * <p>Spherical harmonics must be set in the Builder or the result is undefined.</p>
     *
     * @see #getColorEstimate(float[], float[])
     * @see Builder#irradiance(int, float[])
     * @see Builder#radiance(int, float[])
     */
    @NonNull @Size(min = 4)
    public float[] getColorEstimate(@NonNull @Size(min = 3) float[] direction, @Nullable @Size(min = 4) float[] out) {
        return getColorEstimate(direction[0], direction[1], direction[2], out);
    }

    /**
     * Helper to estimate the color and relative intensity of the environment represented by spherical harmonics in a given direction.
     *
     * <p>Spherical harmonics must be set in the Builder or the result is undefined.</p>
     *
     * @param directionx (x component)
     * @param directiony (y component)
     * @param directionz (z component)
     *
     * @see #getColorEstimate(float[], float[])
     * @see Builder#irradiance(int, float[])
     * @see Builder#radiance(int, float[])
     */
    @NonNull @Size(min = 4)
    public float[] getColorEstimate(float directionx, float directiony, float directionz, @Nullable @Size(min = 4) float[] out) {
        out = Asserts.assertFloat4(out);
        nGetColorEstimate(getNativeObject(), directionx, directiony, directionz, out);
        return out;
    }

    public long getNativeObject() {
        if (mNativeObject == 0) {
            throw new IllegalStateException("Calling method on destroyed IndirectLight");
        }
        return mNativeObject;
    }

    void clearNativeObject() {
        mNativeObject = 0;
    }

    private static native void nSetIntensity(long nativeIndirectLight, float intensity);
    private static native float nGetIntensity(long nativeIndirectLight);
    private static native void nSetRotation(long nativeIndirectLight, @NonNull @Size(min = 9) float[] rotation);
    private static native void nGetRotation(long nativeIndirectLight, @Size(min = 9) float[] out);
    private static native long nGetReflectionsTexture(long nativeIndirectLight);
    private static native long nGetIrradianceTexture(long nativeIndirectLight);
    private static native void nGetDirectionEstimate(@Size(min = 3) float[] sh, @Size(min = 3) float[] out);
    private static native void nGetColorEstimate(@Size(min = 3) float[] sh, float directionx, float directiony, float directionz, @Size(min = 4) float[] out);
    private static native void nGetDirectionEstimate(long nativeIndirectLight, @Size(min = 3) float[] out);
    private static native void nGetColorEstimate(long nativeIndirectLight, float directionx, float directiony, float directionz, @Size(min = 4) float[] out);
    private static native long nCreateBuilder();
    private static native void nDestroyBuilder(long nativeBuilder);
    private static native void nBuilderReflections(long nativeBuilder, long cubemap);
    private static native void nBuilderIrradiance(long nativeBuilder, int bands, float[] sh);
    private static native void nBuilderRadiance(long nativeBuilder, int bands, float[] sh);
    private static native void nBuilderIrradiance(long nativeBuilder, long cubemap);
    private static native void nBuilderIntensity(long nativeBuilder, float envIntensity);
    private static native void nBuilderRotation(long nativeBuilder, float[] rotation);
    private static native long nBuilderBuild(long nativeBuilder, long nativeEngine);
}

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.
