/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.

package com.google.android.filament;

import java.lang.IllegalStateException;

import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.RestrictTo;
import androidx.annotation.Size;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.LOCAL_VARIABLE;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.PARAMETER;
import static java.lang.annotation.RetentionPolicy.SOURCE;

/**
 * LightManager allows to create a light source in the scene, such as a sun or street lights.
 *
 * <p>At least one light must be added to a scene in order to see anything
 * (unless the Material.Shading.UNLIT is used).</p>
 *
 * <h1>Creation and destruction</h1>
 *
 * <p>A Light component is created using the LightManager::Builder and destroyed by calling
 * LightManager::destroy(utils::Entity).</p>
 *
 * <pre>{@code
 *  filament::Engine* engine = filament::Engine::create();
 *  utils::Entity sun = utils::EntityManager.get().create();
 *
 *  filament::LightManager::Builder(Type::SUN)
 *              .castShadows(true)
 *              .build(*engine, sun);
 *
 *  engine->getLightManager().destroy(sun);
 *
 * }</pre>
 *
 * <h1>Light types</h1>
 *
 * <p>Lights come in three flavors:</p>
 *
 * <ul>
 *   <li>directional lights</li>
 *   <li>point lights</li>
 *   <li>spot lights</li>
 * </ul>
 *
 * <h2>Directional lights</h2>
 *
 * <p>Directional lights have a direction, but don't have a position. All light rays are
 * parallel and come from infinitely far away and from everywhere. Typically a directional light
 * is used to simulate the sun.</p>
 *
 * <p>Directional lights and spot lights are able to cast shadows.</p>
 *
 * <p>To create a directional light use Type.DIRECTIONAL or Type.SUN, both are similar, but the later
 * also draws a sun's disk in the sky and its reflection on glossy objects.</p>
 *
 * <p>By default, only the dominant directional light (the one with the highest intensity) of a
 * scene is evaluated. Several directional lights can be used by enabling
 * Engine::Config::enableMultipleDirectionalLights: the dominant one is still the only one that
 * can cast shadows and draw a sun's disk, and up to CONFIG_MAX_EXTRA_DIRECTIONAL_LIGHTS (4)
 * additional directional lights are evaluated without shadows; any further directional lights
 * are ignored. Scenes with a single directional light don't pay any cost for this feature.</p>
 *
 * <h2>Point lights</h2>
 *
 * <p>Unlike directional lights, point lights have a position but emit light in all directions.
 * The intensity of the light diminishes with the inverse square of the distance to the light.
 * Builder.falloff() controls distance beyond which the light has no more influence.</p>
 *
 * <p>A scene can have multiple point lights.</p>
 *
 * <h2>Spot lights</h2>
 *
 * <p>Spot lights are similar to point lights but the light it emits is limited to a cone defined by
 * Builder.spotLightCone() and the light's direction.</p>
 *
 * <p>A spot light is therefore defined by a position, a direction and inner and outer cones. The
 * spot light's influence is limited to inside the outer cone. The inner cone defines the light's
 * falloff attenuation.</p>
 *
 * <p>A physically correct spot light is a little difficult to use because changing the outer angle
 * of the cone changes the illumination levels, as the same amount of light is spread over a
 * changing volume. The coupling of illumination and the outer cone means that an artist cannot
 * tweak the influence cone of a spot light without also changing the perceived illumination.
 * It therefore makes sense to provide artists with a parameter to disable this coupling. This
 * is the difference between Type.FOCUSED_SPOT and Type.SPOT.</p>
 *
 * <h1>Performance considerations</h1>
 *
 * <p>Generally, adding lights to the scene hurts performance, however filament is designed to be
 * able to handle hundreds of lights in a scene under certain conditions. Here are some tips
 * to keep performances high.</p>
 *
 * <ol>
 *   <li>Prefer spot lights to point lights and use the smallest outer cone angle possible.</li>
 *   <li>Use the smallest possible falloff distance for point and spot lights.
 * Performance is very sensitive to overlapping lights. The falloff distance essentially
 * defines a sphere of influence for the light, so try to position point and spot lights
 * such that they don't overlap too much.
 * On the other hand, a scene can contain hundreds of non overlapping lights without
 * incurring a significant overhead.</li>
 * </ol>
 *
 * @see Builder#direction
 * @see Builder#sunAngularRadius
 * @see Builder#position
 * @see Builder#falloff
 * @see Builder#position
 * @see Builder#direction
 * @see Builder#falloff
 * @see Builder#spotLightCone
 */
public class LightManager {
    @Retention(SOURCE)
    @Target({PARAMETER, METHOD, LOCAL_VARIABLE, FIELD})
    public @interface LinearColor {
    }

    static final class EnumCache {
        static final Type[] sTypeValues = Type.values();
    }

    private long mNativeObject;

    /** Denotes the type of the light being created. */
    public enum Type {
        /** Directional light that also draws a sun's disk in the sky. */
        SUN,
        /** Directional light, emits light in a given direction. */
        DIRECTIONAL,
        /** Point light, emits light from a position, in all directions. */
        POINT,
        /** Physically correct spot light. */
        FOCUSED_SPOT,
        /** Spot light with coupling of outer cone and illumination disabled. */
        SPOT;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /** Typical efficiency of an incandescent light bulb (2.2%) */
    public static final float EFFICIENCY_INCANDESCENT = 0.0220f;
    /** Typical efficiency of an halogen light bulb (7.0%) */
    public static final float EFFICIENCY_HALOGEN = 0.0707f;
    /** Typical efficiency of a fluorescent light bulb (8.7%) */
    public static final float EFFICIENCY_FLUORESCENT = 0.0878f;
    /** Typical efficiency of a LED light bulb (11.7%) */
    public static final float EFFICIENCY_LED = 0.1171f;

    LightManager(long nativeObject) {
        mNativeObject = nativeObject;
    }

    @NonNull
    @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
    public static LightManager wrap(long nativeObject) {
        return new LightManager(nativeObject);
    }

    /** Use Builder to construct a Light object instance */
    public static class Builder {
        @SuppressWarnings({"FieldCanBeLocal", "UnusedDeclaration"}) // Keep to finalize native resources
        private final BuilderFinalizer mFinalizer;
        private final long mNativeBuilder;

        public enum Result {
            Error(-1),
            Success(0);

            private final int mValue;

            Result(int value) {
                mValue = value;
            }

            /** @return the value of this enum constant as used by the native Filament engine. */
            public int toFilamentNative() { return mValue; }

            public static Result from(int value) {
                switch (value) {
                    case -1: return Error;
                    case 0: return Success;
                    default: throw new IllegalArgumentException("Unknown Result value: " + value);
                }
            }
        }

        /**
         * Creates a light builder and set the light's #Type.
         *
         * @param type #Type of Light object to create.
         */
        public Builder(Type type) {
            mNativeBuilder = nCreateBuilder(type.toFilamentNative());
            mFinalizer = new BuilderFinalizer(mNativeBuilder);
        }

        long getNativeBuilder() {
            return mNativeBuilder;
        }

        /**
         * Enables or disables a light channel.
         *
         * <p>Light channel 0 is enabled by default.</p>
         *
         * @param channel Light channel to enable or disable, between 0 and 7.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder lightChannel(@IntRange(from = 0) int channel) {
            return lightChannel(channel, true);
        }

        /**
         * Enables or disables a light channel.
         *
         * <p>Light channel 0 is enabled by default.</p>
         *
         * @param channel Light channel to enable or disable, between 0 and 7.
         * @param enable Whether to enable or disable the light channel.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder lightChannel(@IntRange(from = 0) int channel, boolean enable) {
            nBuilderLightChannel(mNativeBuilder, channel, enable);
            return this;
        }

        /**
         * Whether this Light casts shadows (disabled by default)
         *
         * @param enable Enables or disables casting shadows from this Light.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder castShadows(boolean enable) {
            nBuilderCastShadows(mNativeBuilder, enable);
            return this;
        }

        /**
         * Sets the shadow-map options for this light.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder shadowOptions(@NonNull ShadowOptions options) {
            nBuilderShadowOptions(mNativeBuilder, options.getMapSize(), options.getShadowCascades(), options.getCascadeSplitPositions0(), options.getCascadeSplitPositions1(), options.getCascadeSplitPositions2(), options.getConstantBias(), options.getNormalBias(), options.getShadowFar(), options.getShadowNearHint(), options.getShadowFarHint(), options.getStable(), options.getLispsm(), options.getPolygonOffsetConstant(), options.getPolygonOffsetSlope(), options.getScreenSpaceContactShadows(), options.getStepCount(), options.getMaxShadowDistance(), options.getVsm().getElvsm(), options.getVsm().getBlurWidth(), options.getShadowBulbRadius(), options.getTransformX(), options.getTransformY(), options.getTransformZ(), options.getTransformW(), options.getPenumbraScale(), options.getPenumbraRatioScale(), options.getMaxPenumbraRatio(), options.getMaxSearchRadius());
            return this;
        }

        /**
         * Whether this light casts light (enabled by default)
         *
         * <p>In some situations it can be useful to have a light in the scene that doesn't
         * actually emit light, but does cast shadows.</p>
         *
         * @param enable Enables or disables lighting from this Light.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder castLight(boolean enable) {
            nBuilderCastLight(mNativeBuilder, enable);
            return this;
        }

        /**
         * Sets the initial position of the light in world space.
         *
         * <p>The Light's position is ignored for directional lights (Type.DIRECTIONAL or Type.SUN)</p>
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder position(float positionx, float positiony, float positionz) {
            nBuilderPosition(mNativeBuilder, positionx, positiony, positionz);
            return this;
        }

        /**
         * Sets the initial position of the light in world space.
         *
         * <p>The Light's position is ignored for directional lights (Type.DIRECTIONAL or Type.SUN)</p>
         *
         * @param position Light's position in world space. The default is at the origin.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder position(@NonNull @Size(min = 3) float[] position) {
            return position(position[0], position[1], position[2]);
        }

        /**
         * Sets the initial direction of a light in world space.
         *
         * <p>The Light's direction is ignored for Type.POINT lights.</p>
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder direction(float directionx, float directiony, float directionz) {
            nBuilderDirection(mNativeBuilder, directionx, directiony, directionz);
            return this;
        }

        /**
         * Sets the initial direction of a light in world space.
         *
         * <p>The Light's direction is ignored for Type.POINT lights.</p>
         *
         * @param direction Light's direction in world space. Should be a unit vector.
         *                  The default is {0,-1,0}.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder direction(@NonNull @Size(min = 3) float[] direction) {
            return direction(direction[0], direction[1], direction[2]);
        }

        /**
         * Sets the initial color of a light.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder color(@LinearColor float colorx, @LinearColor float colory, @LinearColor float colorz) {
            nBuilderColor(mNativeBuilder, colorx, colory, colorz);
            return this;
        }

        /**
         * Sets the initial color of a light.
         *
         * @param color Color of the light specified in the linear sRGB color-space.
         *              The default is white {1,1,1}.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder color(@NonNull @Size(min = 3) float[] color) {
            return color(color[0], color[1], color[2]);
        }

        /**
         * Sets the initial intensity of a light.
         *
         * @param intensity <p>This parameter depends on the Light.Type:</p>
         *
         * <ul>
         *   <li>For directional lights, it specifies the illuminance in <i>lux</i>
         * (or <i>lumen/m^2</i>).</li>
         *   <li>For point lights and spot lights, it specifies the luminous power
         * in <i>lumen</i>.</li>
         * </ul>
         *
         * @return <p>This Builder, for chaining calls.</p>
         *
         * <p>For example, the sun's illuminance is about 100,000 lux.</p>
         *
         * <p>This method overrides any prior calls to intensity or intensityCandela.</p>
         */
        @NonNull
        public Builder intensity(float intensity) {
            nBuilderIntensity(mNativeBuilder, intensity);
            return this;
        }

        /**
         * Sets the initial intensity of a spot or point light in candela.
         *
         * <p>This method is equivalent to calling intensity(float intensity) for directional lights
         * (Type.DIRECTIONAL or Type.SUN).</p>
         *
         * @param intensity Luminous intensity in <i>candela</i>.
         *
         * @return <p>This Builder, for chaining calls.</p>
         *
         * <p>This method overrides any prior calls to intensity or intensityCandela.</p>
         */
        @NonNull
        public Builder intensityCandela(float intensity) {
            nBuilderIntensityCandela(mNativeBuilder, intensity);
            return this;
        }

        /**
         * Sets the initial intensity of a light in watts.
         *
         * <p>This call is equivalent to {@code Builder::intensity(efficiency <i> 683 </i> watts);}</p>
         *
         * @param watts Energy consumed by a lightbulb. It is related to the energy produced
         *                      and ultimately the brightness by the {@code efficiency} parameter.
         *                      This value is often available on the packaging of commercial
         *                      lightbulbs.
         * @param efficiency <p>Efficiency in percent. This depends on the type of lightbulb used.</p>
         *
         * <table summary="">
         *   <tr>
         *     <th style="text-align: right">Lightbulb type</th>
         *     <th style="text-align: right">Efficiency</th>
         *   </tr>
         *   <tr>
         *     <td style="text-align: right">Incandescent</td>
         *     <td style="text-align: right">2.2%</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: right">Halogen</td>
         *     <td style="text-align: right">7.0%</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: right">LED</td>
         *     <td style="text-align: right">8.7%</td>
         *   </tr>
         *   <tr>
         *     <td style="text-align: right">Fluorescent</td>
         *     <td style="text-align: right">10.7%</td>
         *   </tr>
         * </table>
         *
         * @return <p>This Builder, for chaining calls.</p>
         *
         * <p>This method overrides any prior calls to intensity or intensityCandela.</p>
         */
        @NonNull
        public Builder intensity(float watts, float efficiency) {
            nBuilderIntensity(mNativeBuilder, watts, efficiency);
            return this;
        }

        /**
         * Set the falloff distance for point lights and spot lights.
         *
         * <p>At the falloff distance, the light has no more effect on objects.</p>
         *
         * <p>The falloff distance essentially defines a <i>sphere of influence</i> around the light, and
         * therefore has an impact on performance. Larger falloffs might reduce performance
         * significantly, especially when many lights are used.</p>
         *
         * <p>Try to avoid having a large number of light's spheres of influence overlap.</p>
         *
         * <p>The Light's falloff is ignored for directional lights (Type.DIRECTIONAL or Type.SUN)</p>
         *
         * @param radius Falloff distance in world units. Default is 1 meter.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder falloff(float radius) {
            nBuilderFalloff(mNativeBuilder, radius);
            return this;
        }

        /**
         * Defines a spot light'st angular falloff attenuation.
         *
         * <p>A spot light is defined by a position, a direction and two cones, {@code inner} and {@code outer}.
         * These two cones are used to define the angular falloff attenuation of the spot light
         * and are defined by the angle from the center axis to where the falloff begins (i.e.
         * cones are defined by their half-angle).</p>
         *
         * <p>Both inner and outer are silently clamped to a minimum value of 0.5 degrees
         * (~0.00873 radians) to avoid floating-point precision issues during rendering.</p>
         *
         * <p>The spot light cone is ignored for directional and point lights.</p>
         *
         * @param inner inner cone angle in <i>radians</i> between 0.00873 and {@code outer}
         * @param outer outer cone angle in <i>radians</i> between 0.00873 inner and π/2
         *
         * @return This Builder, for chaining calls.
         *
         * @see Type.SPOT
         * @see Type.FOCUSED_SPOT
         */
        @NonNull
        public Builder spotLightCone(float inner, float outer) {
            nBuilderSpotLightCone(mNativeBuilder, inner, outer);
            return this;
        }

        /**
         * Defines the angular radius of the sun, in degrees, between 0.25° and 20.0°
         *
         * <p>The Sun as seen from Earth has an angular size of 0.526° to 0.545°</p>
         *
         * @param angularRadiusDeg sun's radius in degree. Default is 0.545°.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder sunAngularRadius(float angularRadiusDeg) {
            nBuilderSunAngularRadius(mNativeBuilder, angularRadiusDeg);
            return this;
        }

        /**
         * Defines the halo radius of the sun.
         *
         * <p>The radius of the halo is defined as a
         * multiplier of the sun angular radius.  Must be at least 1.0.</p>
         *
         * @param haloSize radius multiplier. Default is 10.0.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder sunHaloSize(float haloSize) {
            nBuilderSunHaloSize(mNativeBuilder, haloSize);
            return this;
        }

        /**
         * Defines the halo falloff of the sun.
         *
         * <p>The falloff is a dimensionless number
         * used as an exponent. Must be at least 1.0.</p>
         *
         * @param haloFalloff halo falloff. Default is 80.0.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder sunHaloFalloff(float haloFalloff) {
            nBuilderSunHaloFalloff(mNativeBuilder, haloFalloff);
            return this;
        }

        /**
         * Adds the Light component to an entity.
         *
         * <p>Currently, only 2048 lights can be created on a given Engine.</p>
         *
         * @param engine Reference to the filament::Engine to associate this light with.
         * @param entity Entity to add the light component to.
         *
         * @return <p>Success if the component was created successfully, Error otherwise.</p>
         *
         * <p>If exceptions are disabled and an error occurs, this function is a no-op.
         *        Success can be checked by looking at the return value.</p>
         *
         * <p>If this component already exists on the given entity, it is first destroyed as if
         * destroy(utils::Entity e) was called.</p>
         */
        public void build(@NonNull Engine engine, @Entity int entity) {
            if (!nBuilderBuild(mNativeBuilder, engine.getNativeObject(), entity)) {
                throw new IllegalStateException("Couldn't create LightManager");
            }
        }

        private static class BuilderFinalizer {
            private final long mNativeObject;

            BuilderFinalizer(long nativeObject) { mNativeObject = nativeObject; }

            @Override
            public void finalize() {
                try {
                    super.finalize();
                } catch (Throwable t) { // Ignore
                } finally {
                    nDestroyBuilder(mNativeObject);
                }
            }
        }
    }

    /**
     * Returns the number of component in the LightManager, note that component are not guaranteed to be active.
     *
     * <p>Use the EntityManager::isAlive() before use if needed.</p>
     *
     * @return number of component in the LightManager
     */
    @IntRange(from = 0)
    public int getComponentCount() {
        return nGetComponentCount(getNativeObject());
    }

    /**
     * Returns whether a particular Entity is associated with a component of this LightManager
     *
     * @param e An Entity.
     *
     * @return true if this Entity has a component associated with this manager.
     */
    public boolean hasComponent(@Entity int e) {
        return nHasComponent(getNativeObject(), e);
    }

    /** @return true if the this manager has no components */
    public boolean empty() {
        return nEmpty(getNativeObject());
    }

    /**
     * Retrieve the {@code Entity} of the component from its {@code Instance}.
     *
     * @param i Instance of the component obtained from getInstance()
     */
    @Entity
    public int getEntity(@EntityInstance int i) {
        return nGetEntity(getNativeObject(), i);
    }

    /**
     * Retrieve the Entities of all the components of this manager.
     *
     * @param out pre-allocated array to receive the items, or null.
     *
     * @return A list, in no particular order, of all the entities managed by this manager.
     */
    @NonNull
    public @Entity int[] getAllEntities(@Nullable @Entity int[] out) {
        return nGetAllEntities(getNativeObject(), out);
    }

    @NonNull
    public @Entity int[] getAllEntities() {
        return getAllEntities(null);
    }

    /**
     * Gets an Instance representing the Light component associated with the given Entity.
     *
     * <p>Use Instance::isValid() to make sure the component exists.</p>
     *
     * @param e An Entity.
     *
     * @return An Instance object, which represents the Light component associated with the Entity e.
     *
     * @see #hasComponent
     */
    @EntityInstance
    public int getInstance(@Entity int e) {
        return nGetInstance(getNativeObject(), e);
    }

    public void destroy(@Entity int e) {
        nDestroy(getNativeObject(), e);
    }

    public Type getType(@EntityInstance int i) {
        return EnumCache.sTypeValues[nGetType(getNativeObject(), i)];
    }

    /**
     * Helper function that returns if a light is a directional light
     *
     * @param i Instance of the component obtained from getInstance().
     *
     * @return true is this light is a type of directional light
     */
    public boolean isDirectional(@EntityInstance int i) {
        return nIsDirectional(getNativeObject(), i);
    }

    /**
     * Helper function that returns if a light is a point light
     *
     * @param i Instance of the component obtained from getInstance().
     *
     * @return true is this light is a type of point light
     */
    public boolean isPointLight(@EntityInstance int i) {
        return nIsPointLight(getNativeObject(), i);
    }

    /**
     * Helper function that returns if a light is a spot light
     *
     * @param i Instance of the component obtained from getInstance().
     *
     * @return true is this light is a type of spot light
     */
    public boolean isSpotLight(@EntityInstance int i) {
        return nIsSpotLight(getNativeObject(), i);
    }

    /**
     * Enables or disables a light channel.
     *
     * <p>Light channel 0 is enabled by default.</p>
     *
     * @param channel light channel to enable or disable, between 0 and 7.
     */
    public void setLightChannel(@EntityInstance int i, @IntRange(from = 0) int channel) {
        setLightChannel(i, channel, true);
    }

    /**
     * Enables or disables a light channel.
     *
     * <p>Light channel 0 is enabled by default.</p>
     *
     * @param channel light channel to enable or disable, between 0 and 7.
     * @param enable whether to enable (true) or disable (false) the specified light channel.
     */
    public void setLightChannel(@EntityInstance int i, @IntRange(from = 0) int channel, boolean enable) {
        nSetLightChannel(getNativeObject(), i, channel, enable);
    }

    /**
     * Returns whether a light channel is enabled on a specified light.
     *
     * @param i Instance of the component obtained from getInstance().
     * @param channel Light channel to query
     *
     * @return true if the light channel is enabled, false otherwise
     */
    public boolean getLightChannel(@EntityInstance int i, @IntRange(from = 0) int channel) {
        return nGetLightChannel(getNativeObject(), i, channel);
    }

    /**
     * Dynamically updates the light's position.
     *
     * @param i Instance of the component obtained from getInstance().
     * @param positionx (x component) Light's position in world space. The default is at the origin.
     * @param positiony (y component) Light's position in world space. The default is at the origin.
     * @param positionz (z component) Light's position in world space. The default is at the origin.
     *
     * @see Builder#position
     */
    public void setPosition(@EntityInstance int i, float positionx, float positiony, float positionz) {
        nSetPosition(getNativeObject(), i, positionx, positiony, positionz);
    }

    /**
     * Dynamically updates the light's position.
     *
     * @param i Instance of the component obtained from getInstance().
     * @param position Light's position in world space. The default is at the origin.
     *
     * @see Builder#position
     */
    public void setPosition(@EntityInstance int i, @NonNull @Size(min = 3) float[] position) {
        setPosition(i, position[0], position[1], position[2]);
    }

    /** returns the light's position in world space */
    @NonNull @Size(min = 3)
    public float[] getPosition(@EntityInstance int i, @Nullable @Size(min = 3) float[] out) {
        out = Asserts.assertFloat3(out);
        nGetPosition(getNativeObject(), i, out);
        return out;
    }

    /**
     * Dynamically updates the light's direction
     *
     * @param i Instance of the component obtained from getInstance().
     * @param directionx (x component) Light's direction in world space. Should be a unit vector.
     *                  The default is {0,-1,0}.
     * @param directiony (y component) Light's direction in world space. Should be a unit vector.
     *                  The default is {0,-1,0}.
     * @param directionz (z component) Light's direction in world space. Should be a unit vector.
     *                  The default is {0,-1,0}.
     *
     * @see Builder#direction
     */
    public void setDirection(@EntityInstance int i, float directionx, float directiony, float directionz) {
        nSetDirection(getNativeObject(), i, directionx, directiony, directionz);
    }

    /**
     * Dynamically updates the light's direction
     *
     * @param i Instance of the component obtained from getInstance().
     * @param direction Light's direction in world space. Should be a unit vector.
     *                  The default is {0,-1,0}.
     *
     * @see Builder#direction
     */
    public void setDirection(@EntityInstance int i, @NonNull @Size(min = 3) float[] direction) {
        setDirection(i, direction[0], direction[1], direction[2]);
    }

    /** returns the light's direction in world space */
    @NonNull @Size(min = 3)
    public float[] getDirection(@EntityInstance int i, @Nullable @Size(min = 3) float[] out) {
        out = Asserts.assertFloat3(out);
        nGetDirection(getNativeObject(), i, out);
        return out;
    }

    /**
     * Dynamically updates the light's hue as linear sRGB
     *
     * @param i Instance of the component obtained from getInstance().
     * @param colorx (x component) Color of the light specified in the linear sRGB color-space.
     *              The default is white {1,1,1}.
     * @param colory (y component) Color of the light specified in the linear sRGB color-space.
     *              The default is white {1,1,1}.
     * @param colorz (z component) Color of the light specified in the linear sRGB color-space.
     *              The default is white {1,1,1}.
     *
     * @see Builder#color
     * @see #getInstance
     */
    public void setColor(@EntityInstance int i, float colorx, float colory, float colorz) {
        nSetColor(getNativeObject(), i, colorx, colory, colorz);
    }

    /**
     * Dynamically updates the light's hue as linear sRGB
     *
     * @param i Instance of the component obtained from getInstance().
     * @param color Color of the light specified in the linear sRGB color-space.
     *              The default is white {1,1,1}.
     *
     * @see Builder#color
     * @see #getInstance
     */
    public void setColor(@EntityInstance int i, @NonNull @Size(min = 3) float[] color) {
        setColor(i, color[0], color[1], color[2]);
    }

    /**
     * @param i Instance of the component obtained from getInstance().
     *
     * @return the light's color in linear sRGB
     */
    @NonNull @Size(min = 3)
    public float[] getColor(@EntityInstance int i, @Nullable @Size(min = 3) float[] out) {
        out = Asserts.assertFloat3(out);
        nGetColor(getNativeObject(), i, out);
        return out;
    }

    /**
     * Dynamically updates the light's intensity.
     *
     * <p>The intensity can be negative.</p>
     *
     * @param i Instance of the component obtained from getInstance().
     * @param intensity <p>This parameter depends on the Light.Type:</p>
     *
     * <ul>
     *   <li>For directional lights, it specifies the illuminance in <i>lux</i>
     * (or <i>lumen/m^2</i>).</li>
     *   <li>For point lights and spot lights, it specifies the luminous power
     * in <i>lumen</i>.</li>
     * </ul>
     *
     * @see Builder#intensity
     */
    public void setIntensity(@EntityInstance int i, float intensity) {
        nSetIntensity(getNativeObject(), i, intensity);
    }

    /**
     * Dynamically updates the light's intensity.
     *
     * <p>The intensity can be negative.</p>
     *
     * @param i Instance of the component obtained from getInstance().
     * @param watts Energy consumed by a lightbulb. It is related to the energy produced
     *                      and ultimately the brightness by the {@code efficiency} parameter.
     *                      This value is often available on the packaging of commercial
     *                      lightbulbs.
     * @param efficiency <p>Efficiency in percent. This depends on the type of lightbulb used.</p>
     *
     * <table summary="">
     *   <tr>
     *     <th style="text-align: right">Lightbulb type</th>
     *     <th style="text-align: right">Efficiency</th>
     *   </tr>
     *   <tr>
     *     <td style="text-align: right">Incandescent</td>
     *     <td style="text-align: right">2.2%</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: right">Halogen</td>
     *     <td style="text-align: right">7.0%</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: right">LED</td>
     *     <td style="text-align: right">8.7%</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: right">Fluorescent</td>
     *     <td style="text-align: right">10.7%</td>
     *   </tr>
     * </table>
     *
     * @see Builder#intensity(float, float)
     */
    public void setIntensity(@EntityInstance int i, float watts, float efficiency) {
        nSetIntensity(getNativeObject(), i, watts, efficiency);
    }

    /**
     * Dynamically updates the light's intensity in candela.
     *
     * <p>The intensity can be negative.</p>
     *
     * <p>This method is equivalent to calling setIntensity(float intensity) for directional lights
     * (Type.DIRECTIONAL or Type.SUN).</p>
     *
     * @param i Instance of the component obtained from getInstance().
     * @param intensity Luminous intensity in <i>candela</i>.
     *
     * @see Builder#intensityCandela(float)
     */
    public void setIntensityCandela(@EntityInstance int i, float intensity) {
        nSetIntensityCandela(getNativeObject(), i, intensity);
    }

    /**
     * returns the light's luminous intensity in candela.
     *
     * <p>for Type.FOCUSED_SPOT lights, the returned value depends on the {@code outer} cone angle.</p>
     *
     * @param i Instance of the component obtained from getInstance().
     *
     * @return luminous intensity in candela.
     */
    public float getIntensity(@EntityInstance int i) {
        return nGetIntensity(getNativeObject(), i);
    }

    /**
     * Set the falloff distance for point lights and spot lights.
     *
     * @param i Instance of the component obtained from getInstance().
     * @param radius falloff distance in world units. Default is 1 meter.
     *
     * @see Builder#falloff
     */
    public void setFalloff(@EntityInstance int i, float radius) {
        nSetFalloff(getNativeObject(), i, radius);
    }

    /**
     * returns the falloff distance of this light.
     *
     * @param i Instance of the component obtained from getInstance().
     *
     * @return the falloff distance of this light.
     */
    public float getFalloff(@EntityInstance int i) {
        return nGetFalloff(getNativeObject(), i);
    }

    /**
     * Dynamically updates a spot light's cone as angles
     *
     * @param i Instance of the component obtained from getInstance().
     * @param inner inner cone angle in <i>radians</i> between 0.00873 and outer
     * @param outer outer cone angle in <i>radians</i> between 0.00873 and pi/2
     *
     * @see Builder#spotLightCone
     */
    public void setSpotLightCone(@EntityInstance int i, float inner, float outer) {
        nSetSpotLightCone(getNativeObject(), i, inner, outer);
    }

    /**
     * returns the outer cone angle in <i>radians</i> between inner and pi/2.
     *
     * @param i Instance of the component obtained from getInstance().
     *
     * @return the outer cone angle of this light.
     */
    public float getSpotLightOuterCone(@EntityInstance int i) {
        return nGetSpotLightOuterCone(getNativeObject(), i);
    }

    /**
     * returns the inner cone angle in <i>radians</i> between 0 and pi/2.
     *
     * <p>The value is recomputed from the initial values, thus is not precisely
     * the same as the one passed to setSpotLightCone() or Builder.spotLightCone().</p>
     *
     * @param i Instance of the component obtained from getInstance().
     *
     * @return the inner cone angle of this light.
     */
    public float getSpotLightInnerCone(@EntityInstance int i) {
        return nGetSpotLightInnerCone(getNativeObject(), i);
    }

    /**
     * Dynamically updates the angular radius of a Type.SUN light
     *
     * <p>The Sun as seen from Earth has an angular size of 0.526° to 0.545°</p>
     *
     * @param i Instance of the component obtained from getInstance().
     * @param angularRadius sun's radius in degrees. Default is 0.545°.
     */
    public void setSunAngularRadius(@EntityInstance int i, float angularRadius) {
        nSetSunAngularRadius(getNativeObject(), i, angularRadius);
    }

    /**
     * returns the angular radius if the sun in degrees.
     *
     * @param i Instance of the component obtained from getInstance().
     *
     * @return the angular radius if the sun in degrees.
     */
    public float getSunAngularRadius(@EntityInstance int i) {
        return nGetSunAngularRadius(getNativeObject(), i);
    }

    /**
     * Dynamically updates the halo radius of a Type.SUN light.
     *
     * <p>The radius
     * of the halo is defined as a multiplier of the sun angular radius.</p>
     *
     * @param i Instance of the component obtained from getInstance().
     * @param haloSize radius multiplier. Default is 10.0.
     */
    public void setSunHaloSize(@EntityInstance int i, float haloSize) {
        nSetSunHaloSize(getNativeObject(), i, haloSize);
    }

    /**
     * returns the halo size of a Type.SUN light as a multiplier of the sun angular radius.
     *
     * @param i Instance of the component obtained from getInstance().
     *
     * @return the halo size
     */
    public float getSunHaloSize(@EntityInstance int i) {
        return nGetSunHaloSize(getNativeObject(), i);
    }

    /**
     * Dynamically updates the halo falloff of a Type.SUN light.
     *
     * <p>The falloff
     * is a dimensionless number used as an exponent.</p>
     *
     * @param i Instance of the component obtained from getInstance().
     * @param haloFalloff halo falloff. Default is 80.0.
     */
    public void setSunHaloFalloff(@EntityInstance int i, float haloFalloff) {
        nSetSunHaloFalloff(getNativeObject(), i, haloFalloff);
    }

    /**
     * returns the halo falloff of a Type.SUN light as a dimensionless value.
     *
     * @param i Instance of the component obtained from getInstance().
     *
     * @return the halo falloff
     */
    public float getSunHaloFalloff(@EntityInstance int i) {
        return nGetSunHaloFalloff(getNativeObject(), i);
    }

    /**
     * returns the shadow-map options for a given light
     *
     * @param i Instance of the component obtained from getInstance().
     * @param out pre-allocated ShadowOptions to receive the data, or null.
     *
     * @return A ShadowOption structure
     */
    @NonNull
    public ShadowOptions getShadowOptions(@EntityInstance int i, @Nullable ShadowOptions out) {
        if (out == null) {
            out = new ShadowOptions();
        }
        nGetShadowOptions(getNativeObject(), i, out);
        return out;
    }

    @NonNull
    public ShadowOptions getShadowOptions(@EntityInstance int i) {
        return getShadowOptions(i, null);
    }

    /**
     * sets the shadow-map options for a given light
     *
     * @param i Instance of the component obtained from getInstance().
     * @param options A ShadowOption structure
     */
    public void setShadowOptions(@EntityInstance int i, @NonNull ShadowOptions options) {
        nSetShadowOptions(getNativeObject(), i, options.getMapSize(), options.getShadowCascades(), options.getCascadeSplitPositions0(), options.getCascadeSplitPositions1(), options.getCascadeSplitPositions2(), options.getConstantBias(), options.getNormalBias(), options.getShadowFar(), options.getShadowNearHint(), options.getShadowFarHint(), options.getStable(), options.getLispsm(), options.getPolygonOffsetConstant(), options.getPolygonOffsetSlope(), options.getScreenSpaceContactShadows(), options.getStepCount(), options.getMaxShadowDistance(), options.getVsm().getElvsm(), options.getVsm().getBlurWidth(), options.getShadowBulbRadius(), options.getTransformX(), options.getTransformY(), options.getTransformZ(), options.getTransformW(), options.getPenumbraScale(), options.getPenumbraRatioScale(), options.getMaxPenumbraRatio(), options.getMaxSearchRadius());
    }

    /**
     * Whether this Light casts shadows (disabled by default)
     *
     * <ul>
     *   <li>Only a Type.DIRECTIONAL, Type.SUN, Type.SPOT, or Type.FOCUSED_SPOT light can cast shadows</li>
     * </ul>
     *
     * @param i Instance of the component obtained from getInstance().
     * @param shadowCaster Enables or disables casting shadows from this Light.
     */
    public void setShadowCaster(@EntityInstance int i, boolean shadowCaster) {
        nSetShadowCaster(getNativeObject(), i, shadowCaster);
    }

    /**
     * returns whether this light casts shadows.
     *
     * @param i Instance of the component obtained from getInstance().
     */
    public boolean isShadowCaster(@EntityInstance int i) {
        return nIsShadowCaster(getNativeObject(), i);
    }

    public long getNativeObject() {
        if (mNativeObject == 0) {
            throw new IllegalStateException("Calling method on destroyed LightManager");
        }
        return mNativeObject;
    }

    void clearNativeObject() {
        mNativeObject = 0;
    }
    /** Control the quality / performance of the shadow map associated to this light */
    public static class ShadowOptions {
        @IntRange(from = 0)
        public int mapSize;
        @IntRange(from = 0)
        public int shadowCascades;
        private float mCascadeSplitPositions0;
        private float mCascadeSplitPositions1;
        private float mCascadeSplitPositions2;
        public float constantBias;
        public float normalBias;
        public float shadowFar;
        public float shadowNearHint;
        public float shadowFarHint;
        public boolean stable;
        public boolean lispsm;
        public float polygonOffsetConstant;
        public float polygonOffsetSlope;
        public boolean screenSpaceContactShadows;
        @IntRange(from = 0)
        public int stepCount;
        public float maxShadowDistance;
        private boolean mVsmElvsm;
        private float mVsmBlurWidth;
        public float shadowBulbRadius;
        private float mTransformX;
        private float mTransformY;
        private float mTransformZ;
        private float mTransformW;
        public float penumbraScale;
        public float penumbraRatioScale;
        public float maxPenumbraRatio;
        public float maxSearchRadius;

        public ShadowOptions() {
        }

        public ShadowOptions(@IntRange(from = 0) int mapSize, @IntRange(from = 0) int shadowCascades, float cascadeSplitPositions0, float cascadeSplitPositions1, float cascadeSplitPositions2, float constantBias, float normalBias, float shadowFar, float shadowNearHint, float shadowFarHint, boolean stable, boolean lispsm, float polygonOffsetConstant, float polygonOffsetSlope, boolean screenSpaceContactShadows, @IntRange(from = 0) int stepCount, float maxShadowDistance, boolean vsmElvsm, float vsmBlurWidth, float shadowBulbRadius, float transformX, float transformY, float transformZ, float transformW, float penumbraScale, float penumbraRatioScale, float maxPenumbraRatio, float maxSearchRadius) {
            setMapSize(mapSize);
            setShadowCascades(shadowCascades);
            setCascadeSplitPositions(cascadeSplitPositions0, cascadeSplitPositions1, cascadeSplitPositions2);
            setConstantBias(constantBias);
            setNormalBias(normalBias);
            setShadowFar(shadowFar);
            setShadowNearHint(shadowNearHint);
            setShadowFarHint(shadowFarHint);
            setStable(stable);
            setLispsm(lispsm);
            setPolygonOffsetConstant(polygonOffsetConstant);
            setPolygonOffsetSlope(polygonOffsetSlope);
            setScreenSpaceContactShadows(screenSpaceContactShadows);
            setStepCount(stepCount);
            setMaxShadowDistance(maxShadowDistance);
            setVsm(new Vsm(vsmElvsm, vsmBlurWidth));
            setShadowBulbRadius(shadowBulbRadius);
            setTransform(transformX, transformY, transformZ, transformW);
            setPenumbraScale(penumbraScale);
            setPenumbraRatioScale(penumbraRatioScale);
            setMaxPenumbraRatio(maxPenumbraRatio);
            setMaxSearchRadius(maxSearchRadius);
        }

        public ShadowOptions(@IntRange(from = 0) int mapSize, @IntRange(from = 0) int shadowCascades, @NonNull @Size(min = 3) float[] cascadeSplitPositions, float constantBias, float normalBias, float shadowFar, float shadowNearHint, float shadowFarHint, boolean stable, boolean lispsm, float polygonOffsetConstant, float polygonOffsetSlope, boolean screenSpaceContactShadows, @IntRange(from = 0) int stepCount, float maxShadowDistance, @NonNull Vsm vsm, float shadowBulbRadius, @NonNull @Size(min = 4) float[] transform, float penumbraScale, float penumbraRatioScale, float maxPenumbraRatio, float maxSearchRadius) {
            setMapSize(mapSize);
            setShadowCascades(shadowCascades);
            setCascadeSplitPositions(cascadeSplitPositions);
            setConstantBias(constantBias);
            setNormalBias(normalBias);
            setShadowFar(shadowFar);
            setShadowNearHint(shadowNearHint);
            setShadowFarHint(shadowFarHint);
            setStable(stable);
            setLispsm(lispsm);
            setPolygonOffsetConstant(polygonOffsetConstant);
            setPolygonOffsetSlope(polygonOffsetSlope);
            setScreenSpaceContactShadows(screenSpaceContactShadows);
            setStepCount(stepCount);
            setMaxShadowDistance(maxShadowDistance);
            setVsm(vsm);
            setShadowBulbRadius(shadowBulbRadius);
            setTransform(transform);
            setPenumbraScale(penumbraScale);
            setPenumbraRatioScale(penumbraRatioScale);
            setMaxPenumbraRatio(maxPenumbraRatio);
            setMaxSearchRadius(maxSearchRadius);
        }

        public void setMapSize(@IntRange(from = 0) int mapSize) {
            this.mapSize = mapSize;
        }

        @IntRange(from = 0) public int getMapSize() {
            return mapSize;
        }

        public void setShadowCascades(@IntRange(from = 0) int shadowCascades) {
            this.shadowCascades = shadowCascades;
        }

        @IntRange(from = 0) public int getShadowCascades() {
            return shadowCascades;
        }

        public void setCascadeSplitPositions(float cascadeSplitPositions0, float cascadeSplitPositions1, float cascadeSplitPositions2) {
            mCascadeSplitPositions0 = cascadeSplitPositions0;
            mCascadeSplitPositions1 = cascadeSplitPositions1;
            mCascadeSplitPositions2 = cascadeSplitPositions2;
        }

        public void setCascadeSplitPositions(@NonNull @Size(min = 3) float[] cascadeSplitPositions) {
            mCascadeSplitPositions0 = cascadeSplitPositions[0];
            mCascadeSplitPositions1 = cascadeSplitPositions[1];
            mCascadeSplitPositions2 = cascadeSplitPositions[2];
        }

        @NonNull @Size(min = 3)
        public float[] getCascadeSplitPositions(@Nullable @Size(min = 3) float[] out) {
            if (out == null) {
                out = new float[3];
            }
            out[0] = mCascadeSplitPositions0;
            out[1] = mCascadeSplitPositions1;
            out[2] = mCascadeSplitPositions2;
            return out;
        }

        @NonNull @Size(min = 3)
        public float[] getCascadeSplitPositions() {
            return getCascadeSplitPositions(null);
        }

        public float getCascadeSplitPositions0() {
            return mCascadeSplitPositions0;
        }

        public void setCascadeSplitPositions0(float cascadeSplitPositions0) {
            mCascadeSplitPositions0 = cascadeSplitPositions0;
        }

        public float getCascadeSplitPositions1() {
            return mCascadeSplitPositions1;
        }

        public void setCascadeSplitPositions1(float cascadeSplitPositions1) {
            mCascadeSplitPositions1 = cascadeSplitPositions1;
        }

        public float getCascadeSplitPositions2() {
            return mCascadeSplitPositions2;
        }

        public void setCascadeSplitPositions2(float cascadeSplitPositions2) {
            mCascadeSplitPositions2 = cascadeSplitPositions2;
        }

        public void setConstantBias(float constantBias) {
            this.constantBias = constantBias;
        }

        public float getConstantBias() {
            return constantBias;
        }

        public void setNormalBias(float normalBias) {
            this.normalBias = normalBias;
        }

        public float getNormalBias() {
            return normalBias;
        }

        public void setShadowFar(float shadowFar) {
            this.shadowFar = shadowFar;
        }

        public float getShadowFar() {
            return shadowFar;
        }

        public void setShadowNearHint(float shadowNearHint) {
            this.shadowNearHint = shadowNearHint;
        }

        public float getShadowNearHint() {
            return shadowNearHint;
        }

        public void setShadowFarHint(float shadowFarHint) {
            this.shadowFarHint = shadowFarHint;
        }

        public float getShadowFarHint() {
            return shadowFarHint;
        }

        public void setStable(boolean stable) {
            this.stable = stable;
        }

        public boolean getStable() {
            return stable;
        }

        public void setLispsm(boolean lispsm) {
            this.lispsm = lispsm;
        }

        public boolean getLispsm() {
            return lispsm;
        }

        public void setPolygonOffsetConstant(float polygonOffsetConstant) {
            this.polygonOffsetConstant = polygonOffsetConstant;
        }

        public float getPolygonOffsetConstant() {
            return polygonOffsetConstant;
        }

        public void setPolygonOffsetSlope(float polygonOffsetSlope) {
            this.polygonOffsetSlope = polygonOffsetSlope;
        }

        public float getPolygonOffsetSlope() {
            return polygonOffsetSlope;
        }

        public void setScreenSpaceContactShadows(boolean screenSpaceContactShadows) {
            this.screenSpaceContactShadows = screenSpaceContactShadows;
        }

        public boolean getScreenSpaceContactShadows() {
            return screenSpaceContactShadows;
        }

        public void setStepCount(@IntRange(from = 0) int stepCount) {
            this.stepCount = stepCount;
        }

        @IntRange(from = 0) public int getStepCount() {
            return stepCount;
        }

        public void setMaxShadowDistance(float maxShadowDistance) {
            this.maxShadowDistance = maxShadowDistance;
        }

        public float getMaxShadowDistance() {
            return maxShadowDistance;
        }

        public void setVsm(@NonNull Vsm vsm) {
            mVsmElvsm = vsm.getElvsm();
            mVsmBlurWidth = vsm.getBlurWidth();
        }

        @NonNull
        public Vsm getVsm(@Nullable Vsm out) {
            if (out == null) {
                out = new Vsm();
            }
            out.setElvsm(mVsmElvsm);
            out.setBlurWidth(mVsmBlurWidth);
            return out;
        }

        @NonNull
        public Vsm getVsm() {
            return getVsm(null);
        }

        public void setShadowBulbRadius(float shadowBulbRadius) {
            this.shadowBulbRadius = shadowBulbRadius;
        }

        public float getShadowBulbRadius() {
            return shadowBulbRadius;
        }

        public void setTransform(float transformX, float transformY, float transformZ, float transformW) {
            mTransformX = transformX;
            mTransformY = transformY;
            mTransformZ = transformZ;
            mTransformW = transformW;
        }

        public void setTransform(@NonNull @Size(min = 4) float[] transform) {
            mTransformX = transform[0];
            mTransformY = transform[1];
            mTransformZ = transform[2];
            mTransformW = transform[3];
        }

        @NonNull @Size(min = 4)
        public float[] getTransform(@Nullable @Size(min = 4) float[] out) {
            if (out == null) {
                out = new float[4];
            }
            out[0] = mTransformX;
            out[1] = mTransformY;
            out[2] = mTransformZ;
            out[3] = mTransformW;
            return out;
        }

        @NonNull @Size(min = 4)
        public float[] getTransform() {
            return getTransform(null);
        }

        public float getTransformX() {
            return mTransformX;
        }

        public void setTransformX(float transformX) {
            mTransformX = transformX;
        }

        public float getTransformY() {
            return mTransformY;
        }

        public void setTransformY(float transformY) {
            mTransformY = transformY;
        }

        public float getTransformZ() {
            return mTransformZ;
        }

        public void setTransformZ(float transformZ) {
            mTransformZ = transformZ;
        }

        public float getTransformW() {
            return mTransformW;
        }

        public void setTransformW(float transformW) {
            mTransformW = transformW;
        }

        public void setPenumbraScale(float penumbraScale) {
            this.penumbraScale = penumbraScale;
        }

        public float getPenumbraScale() {
            return penumbraScale;
        }

        public void setPenumbraRatioScale(float penumbraRatioScale) {
            this.penumbraRatioScale = penumbraRatioScale;
        }

        public float getPenumbraRatioScale() {
            return penumbraRatioScale;
        }

        public void setMaxPenumbraRatio(float maxPenumbraRatio) {
            this.maxPenumbraRatio = maxPenumbraRatio;
        }

        public float getMaxPenumbraRatio() {
            return maxPenumbraRatio;
        }

        public void setMaxSearchRadius(float maxSearchRadius) {
            this.maxSearchRadius = maxSearchRadius;
        }

        public float getMaxSearchRadius() {
            return maxSearchRadius;
        }

        /**
         * Options available when the View's ShadowType is set to VSM.
         *
         * <p>This API is still experimental and subject to change.</p>
         *
         * @see View#setShadowType
         */
        public static class Vsm {
            public boolean elvsm;
            public float blurWidth;

            public Vsm() {
            }

            public Vsm(boolean elvsm, float blurWidth) {
                setElvsm(elvsm);
                setBlurWidth(blurWidth);
            }

            public void setElvsm(boolean elvsm) {
                this.elvsm = elvsm;
            }

            public boolean getElvsm() {
                return elvsm;
            }

            public void setBlurWidth(float blurWidth) {
                this.blurWidth = blurWidth;
            }

            public float getBlurWidth() {
                return blurWidth;
            }

        }

    }


    @IntRange(from = 0)
    private static native int nGetComponentCount(long nativeLightManager);
    private static native boolean nHasComponent(long nativeLightManager, @Entity int e);
    private static native boolean nEmpty(long nativeLightManager);
    @Entity
    private static native int nGetEntity(long nativeLightManager, @EntityInstance int i);
    @NonNull
    private static native int[] nGetAllEntities(long nativeLightManager, int[] out);
    @EntityInstance
    private static native int nGetInstance(long nativeLightManager, @Entity int e);
    private static native void nDestroy(long nativeLightManager, @Entity int e);
    private static native int nGetType(long nativeLightManager, @EntityInstance int i);
    private static native boolean nIsDirectional(long nativeLightManager, @EntityInstance int i);
    private static native boolean nIsPointLight(long nativeLightManager, @EntityInstance int i);
    private static native boolean nIsSpotLight(long nativeLightManager, @EntityInstance int i);
    private static native void nSetLightChannel(long nativeLightManager, @EntityInstance int i, @IntRange(from = 0) int channel, boolean enable);
    private static native boolean nGetLightChannel(long nativeLightManager, @EntityInstance int i, @IntRange(from = 0) int channel);
    private static native void nSetPosition(long nativeLightManager, @EntityInstance int i, float positionx, float positiony, float positionz);
    private static native void nGetPosition(long nativeLightManager, @EntityInstance int i, @Size(min = 3) float[] out);
    private static native void nSetDirection(long nativeLightManager, @EntityInstance int i, float directionx, float directiony, float directionz);
    private static native void nGetDirection(long nativeLightManager, @EntityInstance int i, @Size(min = 3) float[] out);
    private static native void nSetColor(long nativeLightManager, @EntityInstance int i, float colorx, float colory, float colorz);
    private static native void nGetColor(long nativeLightManager, @EntityInstance int i, @Size(min = 3) float[] out);
    private static native void nSetIntensity(long nativeLightManager, @EntityInstance int i, float intensity);
    private static native void nSetIntensity(long nativeLightManager, @EntityInstance int i, float watts, float efficiency);
    private static native void nSetIntensityCandela(long nativeLightManager, @EntityInstance int i, float intensity);
    private static native float nGetIntensity(long nativeLightManager, @EntityInstance int i);
    private static native void nSetFalloff(long nativeLightManager, @EntityInstance int i, float radius);
    private static native float nGetFalloff(long nativeLightManager, @EntityInstance int i);
    private static native void nSetSpotLightCone(long nativeLightManager, @EntityInstance int i, float inner, float outer);
    private static native float nGetSpotLightOuterCone(long nativeLightManager, @EntityInstance int i);
    private static native float nGetSpotLightInnerCone(long nativeLightManager, @EntityInstance int i);
    private static native void nSetSunAngularRadius(long nativeLightManager, @EntityInstance int i, float angularRadius);
    private static native float nGetSunAngularRadius(long nativeLightManager, @EntityInstance int i);
    private static native void nSetSunHaloSize(long nativeLightManager, @EntityInstance int i, float haloSize);
    private static native float nGetSunHaloSize(long nativeLightManager, @EntityInstance int i);
    private static native void nSetSunHaloFalloff(long nativeLightManager, @EntityInstance int i, float haloFalloff);
    private static native float nGetSunHaloFalloff(long nativeLightManager, @EntityInstance int i);
    private static native void nGetShadowOptions(long nativeLightManager, @EntityInstance int i, @NonNull ShadowOptions out);
    private static native void nSetShadowOptions(long nativeLightManager, @EntityInstance int i, int optionsMapSize, int optionsShadowCascades, float optionsCascadeSplitPositions0, float optionsCascadeSplitPositions1, float optionsCascadeSplitPositions2, float optionsConstantBias, float optionsNormalBias, float optionsShadowFar, float optionsShadowNearHint, float optionsShadowFarHint, boolean optionsStable, boolean optionsLispsm, float optionsPolygonOffsetConstant, float optionsPolygonOffsetSlope, boolean optionsScreenSpaceContactShadows, int optionsStepCount, float optionsMaxShadowDistance, boolean optionsVsmElvsm, float optionsVsmBlurWidth, float optionsShadowBulbRadius, float optionsTransformX, float optionsTransformY, float optionsTransformZ, float optionsTransformW, float optionsPenumbraScale, float optionsPenumbraRatioScale, float optionsMaxPenumbraRatio, float optionsMaxSearchRadius);
    private static native void nSetShadowCaster(long nativeLightManager, @EntityInstance int i, boolean shadowCaster);
    private static native boolean nIsShadowCaster(long nativeLightManager, @EntityInstance int i);
    private static native long nCreateBuilder(int type);
    private static native void nDestroyBuilder(long nativeBuilder);
    private static native void nBuilderLightChannel(long nativeBuilder, int channel, boolean enable);
    private static native void nBuilderCastShadows(long nativeBuilder, boolean enable);
    private static native void nBuilderShadowOptions(long nativeBuilder, int mapSize, int shadowCascades, float cascadeSplitPositions0, float cascadeSplitPositions1, float cascadeSplitPositions2, float constantBias, float normalBias, float shadowFar, float shadowNearHint, float shadowFarHint, boolean stable, boolean lispsm, float polygonOffsetConstant, float polygonOffsetSlope, boolean screenSpaceContactShadows, int stepCount, float maxShadowDistance, boolean vsmElvsm, float vsmBlurWidth, float shadowBulbRadius, float transformX, float transformY, float transformZ, float transformW, float penumbraScale, float penumbraRatioScale, float maxPenumbraRatio, float maxSearchRadius);
    private static native void nBuilderCastLight(long nativeBuilder, boolean enable);
    private static native void nBuilderPosition(long nativeBuilder, float positionx, float positiony, float positionz);
    private static native void nBuilderDirection(long nativeBuilder, float directionx, float directiony, float directionz);
    private static native void nBuilderColor(long nativeBuilder, float colorx, float colory, float colorz);
    private static native void nBuilderIntensity(long nativeBuilder, float intensity);
    private static native void nBuilderIntensityCandela(long nativeBuilder, float intensity);
    private static native void nBuilderIntensity(long nativeBuilder, float watts, float efficiency);
    private static native void nBuilderFalloff(long nativeBuilder, float radius);
    private static native void nBuilderSpotLightCone(long nativeBuilder, float inner, float outer);
    private static native void nBuilderSunAngularRadius(long nativeBuilder, float angularRadiusDeg);
    private static native void nBuilderSunHaloSize(long nativeBuilder, float haloSize);
    private static native void nBuilderSunHaloFalloff(long nativeBuilder, float haloFalloff);
    private static native boolean nBuilderBuild(long nativeBuilder, long nativeEngine, int entity);
}

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.
