/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.

package com.google.android.filament;

import java.lang.IllegalStateException;

import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.RestrictTo;
import androidx.annotation.Size;

/**
 * A container for vertex morphing data that supports both automatic and manual morphing.
 *
 * <p>MorphTargetBuffer operates in a hybrid model depending on the attribute being morphed:</p>
 *
 * <ol>
 *   <li>Automatic for Built-ins (positions/tangents):
 * Enable via {@code withPositions(true)} or {@code withTangents(true)}. The MorphTargetBuffer will
 * allocate internal storage and hold the data for these attributes, which you upload
 * via {@code setPositionsAt()} or {@code setTangentsAt()}. The framework automatically applies
 * the morphing logic in the vertex shader.</li>
 *   <li>Manual for Custom Data (e.g., UVs, colors):
 * The MorphTargetBuffer does NOT hold data for custom targets. The user is responsible
 * for the full data pipeline:</li>
 * </ol>
 * <ul>
 *   <li>Create and manage a separate {@code Texture} to hold the morph target data (offsets).</li>
 *   <li>In the material, declare a {@code sampler2d_array} parameter.</li>
 *   <li>Bind the {@code Texture} to the material instance.</li>
 *   <li>In the vertex shader, manually call {@code morphData2}, {@code morphData3}, or {@code morphData4}
 * with the custom sampler to apply the morphing.
 * A MorphTargetBuffer object must be associated with a Renderable via
 * {@code RenderableManager::Builder::morphing()} to enable the morphing pipeline for all cases.</li>
 * </ul>
 *
 * @see RenderableManager
 */
public class MorphTargetBuffer {
    private long mNativeObject;

    MorphTargetBuffer(long nativeObject) {
        mNativeObject = nativeObject;
    }

    @NonNull
    @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
    public static MorphTargetBuffer wrap(long nativeObject) {
        return new MorphTargetBuffer(nativeObject);
    }

    public static class Builder {
        @SuppressWarnings({"FieldCanBeLocal", "UnusedDeclaration"}) // Keep to finalize native resources
        private final BuilderFinalizer mFinalizer;
        private final long mNativeBuilder;

        public Builder() {
            mNativeBuilder = nCreateBuilder();
            mFinalizer = new BuilderFinalizer(mNativeBuilder);
        }

        long getNativeBuilder() {
            return mNativeBuilder;
        }

        /**
         * Size of the morph targets in vertex counts.
         *
         * @param vertexCount Number of vertex counts the morph targets can hold.
         *
         * @return A reference to this Builder for chaining calls.
         */
        @NonNull
        public Builder vertexCount(@IntRange(from = 0) int vertexCount) {
            nBuilderVertexCount(mNativeBuilder, vertexCount);
            return this;
        }

        /**
         * Size of the morph targets in targets.
         *
         * @param count Number of targets the morph targets can hold.
         *
         * @return A reference to this Builder for chaining calls.
         */
        @NonNull
        public Builder count(@IntRange(from = 0) int count) {
            nBuilderCount(mNativeBuilder, count);
            return this;
        }

        /**
         * Associate an optional name with this MorphTargetBuffer for debugging purposes.
         *
         * <p>This method should be avoided in C++ in favor of the {@code StaticString} overload.
         * It is provided primarily for bindings to other languages.</p>
         *
         * @param name A string to identify this MorphTargetBuffer
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder name(@NonNull String name) {
            nBuilderName(mNativeBuilder, name);
            return this;
        }

        /**
         * Enables and allocates the built-in buffer for position morphing.
         *
         * <p>If enabled, {@code setPositionsAt} can be called to set the position data for each target.
         * The vertex position will be morphed automatically without any further actions.</p>
         *
         * @return A reference to this Builder for chaining calls.
         */
        @NonNull
        public Builder withPositions() {
            return withPositions(true);
        }

        /**
         * Enables and allocates the built-in buffer for position morphing.
         *
         * <p>If enabled, {@code setPositionsAt} can be called to set the position data for each target.
         * The vertex position will be morphed automatically without any further actions.</p>
         *
         * @param enable true to enable, false to disable. Default is true.
         *
         * @return A reference to this Builder for chaining calls.
         */
        @NonNull
        public Builder withPositions(boolean enable) {
            nBuilderWithPositions(mNativeBuilder, enable);
            return this;
        }

        /**
         * Enables and allocates the built-in buffer for tangent/normal morphing.
         *
         * <p>If enabled, {@code setTangentsAt} can be called to set the tangent data for each target.
         * The vertex position will be morphed automatically without any further actions.</p>
         *
         * @return A reference to this Builder for chaining calls.
         */
        @NonNull
        public Builder withTangents() {
            return withTangents(true);
        }

        /**
         * Enables and allocates the built-in buffer for tangent/normal morphing.
         *
         * <p>If enabled, {@code setTangentsAt} can be called to set the tangent data for each target.
         * The vertex position will be morphed automatically without any further actions.</p>
         *
         * @param enable true to enable, false to disable. Default is true.
         *
         * @return A reference to this Builder for chaining calls.
         */
        @NonNull
        public Builder withTangents(boolean enable) {
            nBuilderWithTangents(mNativeBuilder, enable);
            return this;
        }

        /**
         * Enables the custom morphing pipeline.
         *
         * <p>When enabled, the {@code morphData2}, {@code morphData3}, and {@code morphData4} helper functions are
         * available in the vertex shader. You must provide a 2D array texture containing the morph
         * deltas, bind it to a {@code sampler2DArray} uniform, and call the appropriate {@code morphData}
         * function to apply the morphing to your custom attributes.</p>
         *
         * <p>Note: Unlike {@code withPositions} or {@code withTangents}, this does NOT allocate any internal
         * storage. You are responsible for managing the morph data texture.</p>
         *
         * <p>Custom morphing can be used together with automatic position and/or tangent morphing.</p>
         *
         * @param enable true to enable, false to disable. Default is false.
         *
         * @return A reference to this Builder for chaining calls.
         */
        @NonNull
        public Builder enableCustomMorphing(boolean enable) {
            nBuilderEnableCustomMorphing(mNativeBuilder, enable);
            return this;
        }

        /**
         * Creates the MorphTargetBuffer object and returns a pointer to it.
         *
         * @param engine Reference to the filament::Engine to associate this MorphTargetBuffer with.
         *
         * @return pointer to the newly created object.
         */
        @NonNull
        public MorphTargetBuffer build(@NonNull Engine engine) {
            long nativeMorphTargetBuffer = nBuilderBuild(mNativeBuilder, engine.getNativeObject());
            if (nativeMorphTargetBuffer == 0) throw new IllegalStateException("Couldn't create MorphTargetBuffer");
            return new MorphTargetBuffer(nativeMorphTargetBuffer);
        }

        private static class BuilderFinalizer {
            private final long mNativeObject;

            BuilderFinalizer(long nativeObject) { mNativeObject = nativeObject; }

            @Override
            public void finalize() {
                try {
                    super.finalize();
                } catch (Throwable t) { // Ignore
                } finally {
                    nDestroyBuilder(mNativeObject);
                }
            }
        }
    }

    /**
     * Updates positions for the given morph target.
     *
     * <p>This method can only be called if the MorphTargetBuffer was built with {@code withPositions(true)}.
     * This is equivalent to the float4 method, but uses 1.0 for the 4th component.</p>
     *
     * @param engine Reference to the filament::Engine associated with this MorphTargetBuffer.
     * @param targetIndex the index of morph target to be updated.
     * @param positions pointer to at least "count" positions
     * @param count number of float3 vectors in positions
     */
    public void setPositionsAt(@NonNull Engine engine, @IntRange(from = 0) int targetIndex, @NonNull @Size(min = 3) float[] positions, @IntRange(from = 0) int count) {
        setPositionsAt(engine, targetIndex, positions, count, 0);
    }

    /**
     * Updates positions for the given morph target.
     *
     * <p>This method can only be called if the MorphTargetBuffer was built with {@code withPositions(true)}.
     * This is equivalent to the float4 method, but uses 1.0 for the 4th component.</p>
     *
     * @param engine Reference to the filament::Engine associated with this MorphTargetBuffer.
     * @param targetIndex the index of morph target to be updated.
     * @param positions pointer to at least "count" positions
     * @param count number of float3 vectors in positions
     * @param offset offset into the target buffer, expressed as a number of float3 vectors
     */
    public void setPositionsAt(@NonNull Engine engine, @IntRange(from = 0) int targetIndex, @NonNull @Size(min = 3) float[] positions, @IntRange(from = 0) int count, @IntRange(from = 0) int offset) {
        Asserts.assertFloat3In(positions);
        nSetPositionsAt(getNativeObject(), engine.getNativeObject(), targetIndex, positions, count, offset);
    }

    /**
     * Updates tangents for the given morph target.
     *
     * <p>This method can only be called if the MorphTargetBuffer was built with {@code withTangents(true)}.
     * These quaternions must be represented as signed shorts, where real numbers in the [-1,+1]
     * range multiplied by 32767.</p>
     *
     * @param engine Reference to the filament::Engine associated with this MorphTargetBuffer.
     * @param targetIndex the index of morph target to be updated.
     * @param tangents pointer to at least "count" tangents
     * @param count number of short4 quaternions in tangents
     */
    public void setTangentsAt(@NonNull Engine engine, @IntRange(from = 0) int targetIndex, @NonNull @Size(min = 4) short[] tangents, @IntRange(from = 0) int count) {
        setTangentsAt(engine, targetIndex, tangents, count, 0);
    }

    /**
     * Updates tangents for the given morph target.
     *
     * <p>This method can only be called if the MorphTargetBuffer was built with {@code withTangents(true)}.
     * These quaternions must be represented as signed shorts, where real numbers in the [-1,+1]
     * range multiplied by 32767.</p>
     *
     * @param engine Reference to the filament::Engine associated with this MorphTargetBuffer.
     * @param targetIndex the index of morph target to be updated.
     * @param tangents pointer to at least "count" tangents
     * @param count number of short4 quaternions in tangents
     * @param offset offset into the target buffer, expressed as a number of short4 vectors
     */
    public void setTangentsAt(@NonNull Engine engine, @IntRange(from = 0) int targetIndex, @NonNull @Size(min = 4) short[] tangents, @IntRange(from = 0) int count, @IntRange(from = 0) int offset) {
        Asserts.assertShort4In(tangents);
        nSetTangentsAt(getNativeObject(), engine.getNativeObject(), targetIndex, tangents, count, offset);
    }

    /**
     * Returns the vertex count of this MorphTargetBuffer.
     *
     * @return The number of vertices the MorphTargetBuffer holds.
     */
    @IntRange(from = 0)
    public int getVertexCount() {
        return nGetVertexCount(getNativeObject());
    }

    /**
     * Returns the target count of this MorphTargetBuffer.
     *
     * @return The number of targets the MorphTargetBuffer holds.
     */
    @IntRange(from = 0)
    public int getCount() {
        return nGetCount(getNativeObject());
    }

    /**
     * Returns true if this MorphTargetBuffer has a position buffer.
     *
     * @see Builder#withPositions
     */
    public boolean hasPositions() {
        return nHasPositions(getNativeObject());
    }

    /**
     * Returns true if this MorphTargetBuffer has a tangent buffer.
     *
     * @see Builder#withTangents
     */
    public boolean hasTangents() {
        return nHasTangents(getNativeObject());
    }

    /**
     * Returns true if custom morphing is enabled
     *
     * @see Builder#enableCustomMorphing
     */
    public boolean isCustomMorphingEnabled() {
        return nIsCustomMorphingEnabled(getNativeObject());
    }

    public long getNativeObject() {
        if (mNativeObject == 0) {
            throw new IllegalStateException("Calling method on destroyed MorphTargetBuffer");
        }
        return mNativeObject;
    }

    void clearNativeObject() {
        mNativeObject = 0;
    }

    private static native void nSetPositionsAt(long nativeMorphTargetBuffer, long nativeEngine, @IntRange(from = 0) int targetIndex, @NonNull @Size(min = 3) float[] positions, @IntRange(from = 0) int count, @IntRange(from = 0) int offset);
    private static native void nSetTangentsAt(long nativeMorphTargetBuffer, long nativeEngine, @IntRange(from = 0) int targetIndex, @NonNull @Size(min = 4) short[] tangents, @IntRange(from = 0) int count, @IntRange(from = 0) int offset);
    @IntRange(from = 0)
    private static native int nGetVertexCount(long nativeMorphTargetBuffer);
    @IntRange(from = 0)
    private static native int nGetCount(long nativeMorphTargetBuffer);
    private static native boolean nHasPositions(long nativeMorphTargetBuffer);
    private static native boolean nHasTangents(long nativeMorphTargetBuffer);
    private static native boolean nIsCustomMorphingEnabled(long nativeMorphTargetBuffer);
    private static native long nCreateBuilder();
    private static native void nDestroyBuilder(long nativeBuilder);
    private static native void nBuilderVertexCount(long nativeBuilder, int vertexCount);
    private static native void nBuilderCount(long nativeBuilder, int count);
    private static native void nBuilderName(long nativeBuilder, String name);
    private static native void nBuilderWithPositions(long nativeBuilder, boolean enable);
    private static native void nBuilderWithTangents(long nativeBuilder, boolean enable);
    private static native void nBuilderEnableCustomMorphing(long nativeBuilder, boolean enable);
    private static native long nBuilderBuild(long nativeBuilder, long nativeEngine);
}

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.
