/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.

package com.google.android.filament;

import java.lang.IllegalStateException;

import java.nio.Buffer;
import java.nio.BufferOverflowException;

import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.RestrictTo;
import androidx.annotation.Size;

/**
 * SkinningBuffer is used to hold skinning data (bones).
 *
 * <p>It is a simple wraper around
 * a structured UBO.</p>
 *
 * @see RenderableManager#setSkinningBuffer
 */
public class SkinningBuffer {
    private long mNativeObject;

    SkinningBuffer(long nativeObject) {
        mNativeObject = nativeObject;
    }

    @NonNull
    @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
    public static SkinningBuffer wrap(long nativeObject) {
        return new SkinningBuffer(nativeObject);
    }

    public static class Builder {
        @SuppressWarnings({"FieldCanBeLocal", "UnusedDeclaration"}) // Keep to finalize native resources
        private final BuilderFinalizer mFinalizer;
        private final long mNativeBuilder;

        public Builder() {
            mNativeBuilder = nCreateBuilder();
            mFinalizer = new BuilderFinalizer(mNativeBuilder);
        }

        long getNativeBuilder() {
            return mNativeBuilder;
        }

        /**
         * Size of the skinning buffer in bones.
         *
         * <p>Due to limitation in the GLSL, the SkinningBuffer must always by a multiple of
         * 256, this adjustment is done automatically, but can cause
         * some memory overhead. This memory overhead can be mitigated by using the same
         * SkinningBuffer to store the bone information for multiple RenderPrimitives.</p>
         *
         * @param boneCount Number of bones the skinning buffer can hold.
         *
         * @return A reference to this Builder for chaining calls.
         */
        @NonNull
        public Builder boneCount(@IntRange(from = 0) int boneCount) {
            nBuilderBoneCount(mNativeBuilder, boneCount);
            return this;
        }

        /**
         * The new buffer is created with identity bones
         *
         * @return A reference to this Builder for chaining calls.
         */
        @NonNull
        public Builder initialize() {
            return initialize(true);
        }

        /**
         * The new buffer is created with identity bones
         *
         * @param initialize true to initializing the buffer, false to not.
         *
         * @return A reference to this Builder for chaining calls.
         */
        @NonNull
        public Builder initialize(boolean initialize) {
            nBuilderInitialize(mNativeBuilder, initialize);
            return this;
        }

        /**
         * Associate an optional name with this SkinningBuffer for debugging purposes.
         *
         * <p>This method should be avoided in C++ in favor of the {@code StaticString} overload.
         * It is provided primarily for bindings to other languages.</p>
         *
         * @param name A string to identify this SkinningBuffer
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder name(@NonNull String name) {
            nBuilderName(mNativeBuilder, name);
            return this;
        }

        /**
         * Creates the SkinningBuffer object and returns a pointer to it.
         *
         * @param engine Reference to the filament::Engine to associate this SkinningBuffer with.
         *
         * @return pointer to the newly created object.
         *
         * @see SkinningBuffer#setBones
         */
        @NonNull
        public SkinningBuffer build(@NonNull Engine engine) {
            long nativeSkinningBuffer = nBuilderBuild(mNativeBuilder, engine.getNativeObject());
            if (nativeSkinningBuffer == 0) throw new IllegalStateException("Couldn't create SkinningBuffer");
            return new SkinningBuffer(nativeSkinningBuffer);
        }

        private static class BuilderFinalizer {
            private final long mNativeObject;

            BuilderFinalizer(long nativeObject) { mNativeObject = nativeObject; }

            @Override
            public void finalize() {
                try {
                    super.finalize();
                } catch (Throwable t) { // Ignore
                } finally {
                    nDestroyBuilder(mNativeObject);
                }
            }
        }
    }

    /**
     * Updates the bone transforms in the range [offset, offset + count).
     *
     * @param engine Reference to the filament::Engine to associate this SkinningBuffer with.
     * @param transforms buffer of Bone transforms
     * @param count number of elements (structured element count) in <code>transforms</code>
     * @param offset offset in elements (not bytes) in the SkinningBuffer
     *
     * @see RenderableManager#setSkinningBuffer
     */
    public void setBonesAsQuaternions(@NonNull Engine engine, @NonNull Buffer transforms, @IntRange(from = 0) int count, @IntRange(from = 0) int offset) {
        int result = nSetBonesAsQuaternions(getNativeObject(), engine.getNativeObject(), transforms, transforms.remaining(), count, offset);
        if (result < 0) {
            throw new BufferOverflowException();
        }
    }

    /**
     * Updates the bone transforms in the range [0, count).
     *
     * @param engine Reference to the filament::Engine to associate this SkinningBuffer with.
     * @param transforms buffer of Bone transforms
     * @param count number of elements (structured element count) in <code>transforms</code>
     *
     * @see RenderableManager#setSkinningBuffer
     */
    public void setBonesAsQuaternions(@NonNull Engine engine, @NonNull Buffer transforms, @IntRange(from = 0) int count) {
        setBonesAsQuaternions(engine, transforms, count, 0);
    }

    /**
     * Updates the bone transforms in the range [offset, offset + count).
     *
     * @param engine Reference to the filament::Engine to associate this SkinningBuffer with.
     * @param transforms array of Bone transforms
     * @param arrayOffset offset in elements (structured element count) in <code>transforms</code> to skip
     * @param count number of elements (structured element count) in <code>transforms</code>
     * @param offset offset in elements (not bytes) in the SkinningBuffer
     *
     * @see RenderableManager#setSkinningBuffer
     */
    public void setBonesAsQuaternions(@NonNull Engine engine, @NonNull @Size(min = 8) float[] transforms, @IntRange(from = 0) int arrayOffset, @IntRange(from = 0) int count, @IntRange(from = 0) int offset) {
        if (transforms.length < (arrayOffset + count) * 8) {
            throw new ArrayIndexOutOfBoundsException("Array length must be at least " + ((arrayOffset + count) * 8));
        }
        nSetBonesAsQuaternions(getNativeObject(), engine.getNativeObject(), transforms, count, offset, arrayOffset);
    }

    /**
     * Updates the bone transforms in the range [offset, offset + count).
     *
     * @param engine Reference to the filament::Engine to associate this SkinningBuffer with.
     * @param transforms array of Bone transforms
     * @param count number of elements (structured element count) in <code>transforms</code>
     * @param offset offset in elements (not bytes) in the SkinningBuffer
     *
     * @see RenderableManager#setSkinningBuffer
     */
    public void setBonesAsQuaternions(@NonNull Engine engine, @NonNull @Size(min = 8) float[] transforms, @IntRange(from = 0) int count, @IntRange(from = 0) int offset) {
        setBonesAsQuaternions(engine, transforms, 0, count, offset);
    }

    /**
     * Updates the bone transforms in the range [0, count).
     *
     * @param engine Reference to the filament::Engine to associate this SkinningBuffer with.
     * @param transforms array of Bone transforms
     * @param count number of elements (structured element count) in <code>transforms</code>
     *
     * @see RenderableManager#setSkinningBuffer
     */
    public void setBonesAsQuaternions(@NonNull Engine engine, @NonNull @Size(min = 8) float[] transforms, @IntRange(from = 0) int count) {
        setBonesAsQuaternions(engine, transforms, 0, count, 0);
    }

    /**
     * Updates the bone transforms in the range [0, transforms.length / 8).
     *
     * @param engine Reference to the filament::Engine to associate this SkinningBuffer with.
     * @param transforms array of Bone transforms
     *
     * @see RenderableManager#setSkinningBuffer
     */
    public void setBonesAsQuaternions(@NonNull Engine engine, @NonNull @Size(min = 8) float[] transforms) {
        setBonesAsQuaternions(engine, transforms, 0, transforms.length / 8, 0);
    }

    /**
     * Updates the bone transforms in the range [offset, offset + count).
     *
     * @param engine Reference to the filament::Engine to associate this SkinningBuffer with.
     * @param transforms buffer of mat4f transforms
     * @param count number of elements (structured element count) in <code>transforms</code>
     * @param offset offset in elements (not bytes) in the SkinningBuffer
     *
     * @see RenderableManager#setSkinningBuffer
     */
    public void setBonesAsMatrices(@NonNull Engine engine, @NonNull Buffer transforms, @IntRange(from = 0) int count, @IntRange(from = 0) int offset) {
        int result = nSetBonesAsMatrices(getNativeObject(), engine.getNativeObject(), transforms, transforms.remaining(), count, offset);
        if (result < 0) {
            throw new BufferOverflowException();
        }
    }

    /**
     * Updates the bone transforms in the range [0, count).
     *
     * @param engine Reference to the filament::Engine to associate this SkinningBuffer with.
     * @param transforms buffer of mat4f transforms
     * @param count number of elements (structured element count) in <code>transforms</code>
     *
     * @see RenderableManager#setSkinningBuffer
     */
    public void setBonesAsMatrices(@NonNull Engine engine, @NonNull Buffer transforms, @IntRange(from = 0) int count) {
        setBonesAsMatrices(engine, transforms, count, 0);
    }

    /**
     * Updates the bone transforms in the range [offset, offset + count).
     *
     * @param engine Reference to the filament::Engine to associate this SkinningBuffer with.
     * @param transforms array of mat4f transforms
     * @param arrayOffset offset in elements (structured element count) in <code>transforms</code> to skip
     * @param count number of elements (structured element count) in <code>transforms</code>
     * @param offset offset in elements (not bytes) in the SkinningBuffer
     *
     * @see RenderableManager#setSkinningBuffer
     */
    public void setBonesAsMatrices(@NonNull Engine engine, @NonNull @Size(min = 16) float[] transforms, @IntRange(from = 0) int arrayOffset, @IntRange(from = 0) int count, @IntRange(from = 0) int offset) {
        if (transforms.length < (arrayOffset + count) * 16) {
            throw new ArrayIndexOutOfBoundsException("Array length must be at least " + ((arrayOffset + count) * 16));
        }
        nSetBonesAsMatrices(getNativeObject(), engine.getNativeObject(), transforms, count, offset, arrayOffset);
    }

    /**
     * Updates the bone transforms in the range [offset, offset + count).
     *
     * @param engine Reference to the filament::Engine to associate this SkinningBuffer with.
     * @param transforms array of mat4f transforms
     * @param count number of elements (structured element count) in <code>transforms</code>
     * @param offset offset in elements (not bytes) in the SkinningBuffer
     *
     * @see RenderableManager#setSkinningBuffer
     */
    public void setBonesAsMatrices(@NonNull Engine engine, @NonNull @Size(min = 16) float[] transforms, @IntRange(from = 0) int count, @IntRange(from = 0) int offset) {
        setBonesAsMatrices(engine, transforms, 0, count, offset);
    }

    /**
     * Updates the bone transforms in the range [0, count).
     *
     * @param engine Reference to the filament::Engine to associate this SkinningBuffer with.
     * @param transforms array of mat4f transforms
     * @param count number of elements (structured element count) in <code>transforms</code>
     *
     * @see RenderableManager#setSkinningBuffer
     */
    public void setBonesAsMatrices(@NonNull Engine engine, @NonNull @Size(min = 16) float[] transforms, @IntRange(from = 0) int count) {
        setBonesAsMatrices(engine, transforms, 0, count, 0);
    }

    /**
     * Updates the bone transforms in the range [0, transforms.length / 16).
     *
     * @param engine Reference to the filament::Engine to associate this SkinningBuffer with.
     * @param transforms array of mat4f transforms
     *
     * @see RenderableManager#setSkinningBuffer
     */
    public void setBonesAsMatrices(@NonNull Engine engine, @NonNull @Size(min = 16) float[] transforms) {
        setBonesAsMatrices(engine, transforms, 0, transforms.length / 16, 0);
    }

    /**
     * Returns the size of this SkinningBuffer in elements.
     *
     * @return The number of bones the SkinningBuffer holds.
     */
    @IntRange(from = 0)
    public int getBoneCount() {
        return nGetBoneCount(getNativeObject());
    }

    public long getNativeObject() {
        if (mNativeObject == 0) {
            throw new IllegalStateException("Calling method on destroyed SkinningBuffer");
        }
        return mNativeObject;
    }

    void clearNativeObject() {
        mNativeObject = 0;
    }

    private static native int nSetBonesAsQuaternions(long nativeSkinningBuffer, long nativeEngine, @NonNull Buffer transforms, int remaining, @IntRange(from = 0) int count, @IntRange(from = 0) int offset);
    private static native void nSetBonesAsQuaternions(long nativeSkinningBuffer, long nativeEngine, @NonNull @Size(min = 8) float[] transforms, @IntRange(from = 0) int count, @IntRange(from = 0) int offset, @IntRange(from = 0) int arrayOffset);
    private static native int nSetBonesAsMatrices(long nativeSkinningBuffer, long nativeEngine, @NonNull Buffer transforms, int remaining, @IntRange(from = 0) int count, @IntRange(from = 0) int offset);
    private static native void nSetBonesAsMatrices(long nativeSkinningBuffer, long nativeEngine, @NonNull @Size(min = 16) float[] transforms, @IntRange(from = 0) int count, @IntRange(from = 0) int offset, @IntRange(from = 0) int arrayOffset);
    @IntRange(from = 0)
    private static native int nGetBoneCount(long nativeSkinningBuffer);
    private static native long nCreateBuilder();
    private static native void nDestroyBuilder(long nativeBuilder);
    private static native void nBuilderBoneCount(long nativeBuilder, int boneCount);
    private static native void nBuilderInitialize(long nativeBuilder, boolean initialize);
    private static native void nBuilderName(long nativeBuilder, String name);
    private static native long nBuilderBuild(long nativeBuilder, long nativeEngine);
}

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.
