/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.

package com.google.android.filament;

import java.lang.IllegalStateException;

import java.nio.Buffer;
import java.nio.ByteBuffer;
import java.nio.BufferOverflowException;
import java.nio.ReadOnlyBufferException;

import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.RestrictTo;

/**
 * Texture
 *
 * <p>The Texture class supports:</p>
 *
 * <ul>
 *   <li>2D textures</li>
 *   <li>3D textures</li>
 *   <li>Cube maps</li>
 *   <li>mip mapping</li>
 * </ul>
 *
 * <h1>Creation and destruction</h1>
 *
 * <p>A Texture object is created using the Texture::Builder and destroyed by calling
 * Engine::destroy(const Texture*).</p>
 *
 * <pre>{@code
 *  filament::Engine* engine = filament::Engine::create();
 *
 *  filament::Texture* texture = filament::Texture::Builder()
 *              .width(64)
 *              .height(64)
 *              .build(*engine);
 *
 *  engine->destroy(texture);
 *
 * }</pre>
 */
public class Texture {
    static final class EnumCache {
        static final InternalFormat[] sInternalFormatValues = InternalFormat.values();
        static final Sampler[] sSamplerValues = Sampler.values();
    }

    private long mNativeObject;

    /** Texture sampler type */
    public enum Sampler {
        /** 2D texture */
        SAMPLER_2D,
        /** 2D array texture */
        SAMPLER_2D_ARRAY,
        /** Cube map texture */
        SAMPLER_CUBEMAP,
        /** External texture */
        SAMPLER_EXTERNAL,
        /** 3D texture */
        SAMPLER_3D,
        /** Cube map array texture (feature level 2) */
        SAMPLER_CUBEMAP_ARRAY;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /**
     * Supported texel formats
     *
     * <p>These formats are typically used to specify a texture's internal storage format.</p>
     *
     * <h1>Enumerants syntax format</h1>
     *
     * <p>{@code [components][size][type]}</p>
     *
     * <p>{@code components} : List of stored components by this format.
     * {@code size}       : Size in bit of each component.
     * {@code type}       : Type this format is stored as.</p>
     *
     * <table summary="">
     *   <tr>
     *     <th style="text-align: left">Name</th>
     *     <th style="text-align: left">Component</th>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">R</td>
     *     <td style="text-align: left">Linear Red</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">RG</td>
     *     <td style="text-align: left">Linear Red, Green</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">RGB</td>
     *     <td style="text-align: left">Linear Red, Green, Blue</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">RGBA</td>
     *     <td style="text-align: left">Linear Red, Green Blue, Alpha</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">SRGB</td>
     *     <td style="text-align: left">sRGB encoded Red, Green, Blue</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">DEPTH</td>
     *     <td style="text-align: left">Depth</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">STENCIL</td>
     *     <td style="text-align: left">Stencil</td>
     *   </tr>
     * </table>
     *
     * <table summary="">
     *   <tr>
     *     <th style="text-align: left">Name</th>
     *     <th style="text-align: left">Type</th>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">(none)</td>
     *     <td style="text-align: left">Unsigned Normalized Integer [0, 1]</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">_SNORM</td>
     *     <td style="text-align: left">Signed Normalized Integer [-1, 1]</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">UI</td>
     *     <td style="text-align: left">Unsigned Integer [0, 2<sup>size</sup>]</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">I</td>
     *     <td style="text-align: left">Signed Integer [-2<sup>size-1</sup>, 2<sup>size-1</sup>-1]</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">F</td>
     *     <td style="text-align: left">Floating-point</td>
     *   </tr>
     * </table>
     *
     * <h2>Special color formats</h2>
     *
     * <p>There are a few special color formats that don't follow the convention above:</p>
     *
     * <table summary="">
     *   <tr>
     *     <th style="text-align: left">Name</th>
     *     <th style="text-align: left">Format</th>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">RGB565</td>
     *     <td style="text-align: left">5-bits for R and B, 6-bits for G.</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">RGB5_A1</td>
     *     <td style="text-align: left">5-bits for R, G and B, 1-bit for A.</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">RGB10_A2</td>
     *     <td style="text-align: left">10-bits for R, G and B, 2-bits for A.</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">RGB9_E5</td>
     *     <td style="text-align: left"><b>Unsigned</b> floating point. 9-bits mantissa for RGB, 5-bits shared exponent</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">R11F_G11F_B10F</td>
     *     <td style="text-align: left"><b>Unsigned</b> floating point. 6-bits mantissa, for R and G, 5-bits for B. 5-bits exponent.</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">SRGB8_A8</td>
     *     <td style="text-align: left">sRGB 8-bits with linear 8-bits alpha.</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">DEPTH24_STENCIL8</td>
     *     <td style="text-align: left">24-bits unsigned normalized integer depth, 8-bits stencil.</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">DEPTH32F_STENCIL8</td>
     *     <td style="text-align: left">32-bits floating-point depth, 8-bits stencil.</td>
     *   </tr>
     * </table>
     *
     * <h2>Compressed texture formats</h2>
     *
     * <p>Many compressed texture formats are supported as well, which include (but are not limited to)
     * the following list:</p>
     *
     * <table summary="">
     *   <tr>
     *     <th style="text-align: left">Name</th>
     *     <th style="text-align: left">Format</th>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">EAC_R11</td>
     *     <td style="text-align: left">Compresses R11UI</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">EAC_R11_SIGNED</td>
     *     <td style="text-align: left">Compresses R11I</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">EAC_RG11</td>
     *     <td style="text-align: left">Compresses RG11UI</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">EAC_RG11_SIGNED</td>
     *     <td style="text-align: left">Compresses RG11I</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">ETC2_RGB8</td>
     *     <td style="text-align: left">Compresses RGB8</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">ETC2_SRGB8</td>
     *     <td style="text-align: left">compresses SRGB8</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">ETC2_EAC_RGBA8</td>
     *     <td style="text-align: left">Compresses RGBA8</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">ETC2_EAC_SRGBA8</td>
     *     <td style="text-align: left">Compresses SRGB8_A8</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">ETC2_RGB8_A1</td>
     *     <td style="text-align: left">Compresses RGB8 with 1-bit alpha</td>
     *   </tr>
     *   <tr>
     *     <td style="text-align: left">ETC2_SRGB8_A1</td>
     *     <td style="text-align: left">Compresses sRGB8 with 1-bit alpha</td>
     *   </tr>
     * </table>
     *
     * @see Texture
     */
    public enum InternalFormat {
        R8,
        R8_SNORM,
        R8UI,
        R8I,
        STENCIL8,
        R16F,
        R16UI,
        R16I,
        RG8,
        RG8_SNORM,
        RG8UI,
        RG8I,
        RGB565,
        RGB9_E5,
        RGB5_A1,
        RGBA4,
        DEPTH16,
        RGB8,
        SRGB8,
        RGB8_SNORM,
        RGB8UI,
        RGB8I,
        DEPTH24,
        R32F,
        R32UI,
        R32I,
        RG16F,
        RG16UI,
        RG16I,
        R11F_G11F_B10F,
        RGBA8,
        SRGB8_A8,
        RGBA8_SNORM,
        UNUSED,
        RGB10_A2,
        RGBA8UI,
        RGBA8I,
        DEPTH32F,
        DEPTH24_STENCIL8,
        DEPTH32F_STENCIL8,
        RGB16F,
        RGB16UI,
        RGB16I,
        RG32F,
        RG32UI,
        RG32I,
        RGBA16F,
        RGBA16UI,
        RGBA16I,
        RGB32F,
        RGB32UI,
        RGB32I,
        RGBA32F,
        RGBA32UI,
        RGBA32I,
        EAC_R11,
        EAC_R11_SIGNED,
        EAC_RG11,
        EAC_RG11_SIGNED,
        ETC2_RGB8,
        ETC2_SRGB8,
        ETC2_RGB8_A1,
        ETC2_SRGB8_A1,
        ETC2_EAC_RGBA8,
        ETC2_EAC_SRGBA8,
        DXT1_RGB,
        DXT1_RGBA,
        DXT3_RGBA,
        DXT5_RGBA,
        DXT1_SRGB,
        DXT1_SRGBA,
        DXT3_SRGBA,
        DXT5_SRGBA,
        RGBA_ASTC_4x4,
        RGBA_ASTC_5x4,
        RGBA_ASTC_5x5,
        RGBA_ASTC_6x5,
        RGBA_ASTC_6x6,
        RGBA_ASTC_8x5,
        RGBA_ASTC_8x6,
        RGBA_ASTC_8x8,
        RGBA_ASTC_10x5,
        RGBA_ASTC_10x6,
        RGBA_ASTC_10x8,
        RGBA_ASTC_10x10,
        RGBA_ASTC_12x10,
        RGBA_ASTC_12x12,
        SRGB8_ALPHA8_ASTC_4x4,
        SRGB8_ALPHA8_ASTC_5x4,
        SRGB8_ALPHA8_ASTC_5x5,
        SRGB8_ALPHA8_ASTC_6x5,
        SRGB8_ALPHA8_ASTC_6x6,
        SRGB8_ALPHA8_ASTC_8x5,
        SRGB8_ALPHA8_ASTC_8x6,
        SRGB8_ALPHA8_ASTC_8x8,
        SRGB8_ALPHA8_ASTC_10x5,
        SRGB8_ALPHA8_ASTC_10x6,
        SRGB8_ALPHA8_ASTC_10x8,
        SRGB8_ALPHA8_ASTC_10x10,
        SRGB8_ALPHA8_ASTC_12x10,
        SRGB8_ALPHA8_ASTC_12x12,
        RED_RGTC1,
        SIGNED_RED_RGTC1,
        RED_GREEN_RGTC2,
        SIGNED_RED_GREEN_RGTC2,
        RGB_BPTC_SIGNED_FLOAT,
        RGB_BPTC_UNSIGNED_FLOAT,
        RGBA_BPTC_UNORM,
        SRGB_ALPHA_BPTC_UNORM;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /** Texture Cubemap Face */
    public enum CubemapFace {
        /** +x face */
        POSITIVE_X,
        /** -x face */
        NEGATIVE_X,
        /** +y face */
        POSITIVE_Y,
        /** -y face */
        NEGATIVE_Y,
        /** +z face */
        POSITIVE_Z,
        /** -z face */
        NEGATIVE_Z;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /** Pixel Data Format */
    public enum Format {
        /** One Red channel, float */
        R,
        /** One Red channel, integer */
        R_INTEGER,
        /** Two Red and Green channels, float */
        RG,
        /** Two Red and Green channels, integer */
        RG_INTEGER,
        /** Three Red, Green and Blue channels, float */
        RGB,
        /** Three Red, Green and Blue channels, integer */
        RGB_INTEGER,
        /** Four Red, Green, Blue and Alpha channels, float */
        RGBA,
        /** Four Red, Green, Blue and Alpha channels, integer */
        RGBA_INTEGER,
        UNUSED,
        /** Depth, 16-bit or 24-bits usually */
        DEPTH_COMPONENT,
        /** Two Depth (24-bits) + Stencil (8-bits) channels */
        DEPTH_STENCIL,
        ALPHA;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /** Pixel Data Type */
    public enum Type {
        /** unsigned byte */
        UBYTE,
        /** signed byte */
        BYTE,
        /** unsigned short (16-bit) */
        USHORT,
        /** signed short (16-bit) */
        SHORT,
        /** unsigned int (32-bit) */
        UINT,
        /** signed int (32-bit) */
        INT,
        /** half-float (16-bit float) */
        HALF,
        /** float (32-bits float) */
        FLOAT,
        /** compressed pixels, */
        COMPRESSED,
        /** three low precision floating-point numbers */
        UINT_10F_11F_11F_REV,
        /** unsigned int (16-bit), encodes 3 RGB channels */
        USHORT_565,
        /** unsigned normalized 10 bits RGB, 2 bits alpha */
        UINT_2_10_10_10_REV;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /** Compressed pixel data types */
    public enum CompressedType {
        EAC_R11,
        EAC_R11_SIGNED,
        EAC_RG11,
        EAC_RG11_SIGNED,
        ETC2_RGB8,
        ETC2_SRGB8,
        ETC2_RGB8_A1,
        ETC2_SRGB8_A1,
        ETC2_EAC_RGBA8,
        ETC2_EAC_SRGBA8,
        DXT1_RGB,
        DXT1_RGBA,
        DXT3_RGBA,
        DXT5_RGBA,
        DXT1_SRGB,
        DXT1_SRGBA,
        DXT3_SRGBA,
        DXT5_SRGBA,
        RGBA_ASTC_4x4,
        RGBA_ASTC_5x4,
        RGBA_ASTC_5x5,
        RGBA_ASTC_6x5,
        RGBA_ASTC_6x6,
        RGBA_ASTC_8x5,
        RGBA_ASTC_8x6,
        RGBA_ASTC_8x8,
        RGBA_ASTC_10x5,
        RGBA_ASTC_10x6,
        RGBA_ASTC_10x8,
        RGBA_ASTC_10x10,
        RGBA_ASTC_12x10,
        RGBA_ASTC_12x12,
        SRGB8_ALPHA8_ASTC_4x4,
        SRGB8_ALPHA8_ASTC_5x4,
        SRGB8_ALPHA8_ASTC_5x5,
        SRGB8_ALPHA8_ASTC_6x5,
        SRGB8_ALPHA8_ASTC_6x6,
        SRGB8_ALPHA8_ASTC_8x5,
        SRGB8_ALPHA8_ASTC_8x6,
        SRGB8_ALPHA8_ASTC_8x8,
        SRGB8_ALPHA8_ASTC_10x5,
        SRGB8_ALPHA8_ASTC_10x6,
        SRGB8_ALPHA8_ASTC_10x8,
        SRGB8_ALPHA8_ASTC_10x10,
        SRGB8_ALPHA8_ASTC_12x10,
        SRGB8_ALPHA8_ASTC_12x12,
        RED_RGTC1,
        SIGNED_RED_RGTC1,
        RED_GREEN_RGTC2,
        SIGNED_RED_GREEN_RGTC2,
        RGB_BPTC_SIGNED_FLOAT,
        RGB_BPTC_UNSIGNED_FLOAT,
        RGBA_BPTC_UNORM,
        SRGB_ALPHA_BPTC_UNORM;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /** Bitmask describing the intended Texture Usage */
    public static class Usage {
        private Usage() {}

        public static final int NONE = 0;
        /** Texture can be used as a color attachment */
        public static final int COLOR_ATTACHMENT = 0x1;
        /** Texture can be used as a depth attachment */
        public static final int DEPTH_ATTACHMENT = 0x2;
        /** Texture can be used as a stencil attachment */
        public static final int STENCIL_ATTACHMENT = 0x4;
        /** Data can be uploaded into this texture (default) */
        public static final int UPLOADABLE = 0x8;
        /** Texture can be sampled (default) */
        public static final int SAMPLEABLE = 0x10;
        /** Texture can be used as a subpass input */
        public static final int SUBPASS_INPUT = 0x20;
        /** Texture can be used the source of a blit() */
        public static final int BLIT_SRC = 0x40;
        /** Texture can be used the destination of a blit() */
        public static final int BLIT_DST = 0x80;
        /** Texture can be used for protected content */
        public static final int PROTECTED = 0x100;
        /** Texture can be used with generateMipmaps() */
        public static final int GEN_MIPMAPPABLE = 0x200;
        /** Default texture usage */
        public static final int DEFAULT = 0x18;
        /** Mask of all attachments */
        public static final int ALL_ATTACHMENTS = 0x27;
    }

    /** Texture swizzle */
    public enum Swizzle {
        SUBSTITUTE_ZERO,
        SUBSTITUTE_ONE,
        CHANNEL_0,
        CHANNEL_1,
        CHANNEL_2,
        CHANNEL_3;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /**
     * Outcome of an asynchronous operation, reported to its completion callback.
     *
     * <p>A completion callback that cannot say why it fired is ambiguous: chaining another operation from
     * a callback that fired because the operation was canceled would proceed on a resource that was
     * never populated. The caller cannot reconstruct the answer out of band either, because an
     * operation can be canceled without anyone asking for it (the driver dropping queued work while
     * shutting down).</p>
     *
     * @see AsyncCallback
     * @see #cancelAsyncJob
     */
    public enum AsyncCallStatus {
        /** The operation ran to completion. */
        COMPLETED,
        /** The operation never ran: it was canceled, or dropped because the driver is shutting down. */
        CANCELED;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    public static final int BASE_LEVEL = 0;

    Texture(long nativeObject) {
        mNativeObject = nativeObject;
    }

    @NonNull
    @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
    public static Texture wrap(long nativeObject) {
        return new Texture(nativeObject);
    }

    /** Use Builder to construct a Texture object instance */
    public static class Builder {
        @SuppressWarnings({"FieldCanBeLocal", "UnusedDeclaration"}) // Keep to finalize native resources
        private final BuilderFinalizer mFinalizer;
        private final long mNativeBuilder;

        public Builder() {
            mNativeBuilder = nCreateBuilder();
            mFinalizer = new BuilderFinalizer(mNativeBuilder);
        }

        long getNativeBuilder() {
            return mNativeBuilder;
        }

        /**
         * Specifies the width in texels of the texture.
         *
         * <p>Doesn't need to be a power-of-two.</p>
         *
         * @param width Width of the texture in texels (default: 1).
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder width(@IntRange(from = 0) int width) {
            nBuilderWidth(mNativeBuilder, width);
            return this;
        }

        /**
         * Specifies the height in texels of the texture.
         *
         * <p>Doesn't need to be a power-of-two.</p>
         *
         * @param height Height of the texture in texels (default: 1).
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder height(@IntRange(from = 0) int height) {
            nBuilderHeight(mNativeBuilder, height);
            return this;
        }

        /**
         * Specifies the depth in texels of the texture.
         *
         * <p>Doesn't need to be a power-of-two.
         * The depth controls the number of layers in a 2D array texture. Values greater than 1
         * effectively create a 3D texture.</p>
         *
         * @param depth Depth of the texture in texels (default: 1).
         *
         * @return This Builder, for chaining calls.
         * @attention This Texture instance must use Sampler::SAMPLER_3D or
         *            Sampler::SAMPLER_2D_ARRAY or it has no effect.
         */
        @NonNull
        public Builder depth(@IntRange(from = 0) int depth) {
            nBuilderDepth(mNativeBuilder, depth);
            return this;
        }

        /**
         * Specifies the numbers of mip map levels.
         *
         * <p>This creates a mip-map pyramid. The maximum number of levels a texture can have is
         * such that max(width, height, level) / 2^MAX_LEVELS = 1</p>
         *
         * @param levels Number of mipmap levels for this texture.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder levels(@IntRange(from = 0) int levels) {
            nBuilderLevels(mNativeBuilder, levels);
            return this;
        }

        /**
         * Specifies the numbers of samples used for MSAA (Multisample Anti-Aliasing).
         *
         * <p>Calling this method implicitly indicates the texture is used as a render target. Hence,
         * this method should not be used in conjunction with other methods that are semantically
         * conflicting like {@code setImage}.</p>
         *
         * <p>If this is invoked for array textures, it means this texture is used for multiview.</p>
         *
         * @param samples Number of samples for this texture.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder samples(@IntRange(from = 0) int samples) {
            nBuilderSamples(mNativeBuilder, samples);
            return this;
        }

        /**
         * Specifies the type of sampler to use.
         *
         * @param target Sampler type
         *
         * @return This Builder, for chaining calls.
         *
         * @see Sampler
         */
        @NonNull
        public Builder sampler(@NonNull Sampler target) {
            nBuilderSampler(mNativeBuilder, target.toFilamentNative());
            return this;
        }

        /**
         * Specifies the <i>internal</i> format of this texture.
         *
         * <p>The internal format specifies how texels are stored (which may be different from how
         * they're specified in setImage()). InternalFormat specifies both the color components
         * and the data type used.</p>
         *
         * @param format Format of the texture's texel.
         *
         * @return This Builder, for chaining calls.
         *
         * @see InternalFormat
         * @see #setImage
         */
        @NonNull
        public Builder format(@NonNull InternalFormat format) {
            nBuilderFormat(mNativeBuilder, format.toFilamentNative());
            return this;
        }

        /**
         * Specifies if the texture will be used as a render target attachment.
         *
         * <p>If the texture is potentially rendered into, it may require a different memory layout,
         * which needs to be known during construction.</p>
         *
         * @param usage Defaults to Texture::Usage::DEFAULT; c.f. Texture::Usage::COLOR_ATTACHMENT.
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder usage(@IntRange(from = 0) int usage) {
            nBuilderUsage(mNativeBuilder, usage);
            return this;
        }

        /**
         * Specifies how a texture's channels map to color components
         *
         * <p>Texture Swizzle is only supported if isTextureSwizzleSupported() returns true.</p>
         *
         * @param r texture channel for red component
         * @param g texture channel for green component
         * @param b texture channel for blue component
         * @param a texture channel for alpha component
         *
         * @return This Builder, for chaining calls.
         *
         * @see Texture#isTextureSwizzleSupported
         */
        @NonNull
        public Builder swizzle(@NonNull Swizzle r, @NonNull Swizzle g, @NonNull Swizzle b, @NonNull Swizzle a) {
            nBuilderSwizzle(mNativeBuilder, r.toFilamentNative(), g.toFilamentNative(), b.toFilamentNative(), a.toFilamentNative());
            return this;
        }

        /**
         * Associate an optional name with this Texture for debugging purposes.
         *
         * <p>This method should be avoided in C++ in favor of the {@code StaticString} overload.
         * It is provided primarily for bindings to other languages.</p>
         *
         * @param name A string to identify this Texture
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder name(@NonNull String name) {
            nBuilderName(mNativeBuilder, name);
            return this;
        }

        /**
         * Creates an external texture.
         *
         * <p>The content must be set using setExternalImage().
         * The sampler can be SAMPLER_EXTERNAL or SAMPLER_2D depending on the format. Generally
         * YUV formats must use SAMPLER_EXTERNAL. This depends on the backend features and is not
         * validated.</p>
         *
         * <p>If the Sampler is set to SAMPLER_EXTERNAL, external() is implied.</p>
         */
        @NonNull
        public Builder external() {
            nBuilderExternal(mNativeBuilder);
            return this;
        }

        /**
         * Creates the Texture object and returns a pointer to it.
         *
         * @param engine Reference to the filament::Engine to associate this Texture with.
         *
         * @return pointer to the newly created object.
         */
        @NonNull
        public Texture build(@NonNull Engine engine) {
            long nativeTexture = nBuilderBuild(mNativeBuilder, engine.getNativeObject());
            if (nativeTexture == 0) throw new IllegalStateException("Couldn't create Texture");
            return new Texture(nativeTexture);
        }

        /**
         * Specify a native texture to import as a Filament texture.
         *
         * <p>The texture id is backend-specific:</p>
         *
         * <ul>
         *   <li>OpenGL: GLuint texture ID</li>
         *   <li>Metal: id<MTLTexture>
         * With Metal, the id<MTLTexture> object should be cast to an intptr_t using
         * CFBridgingRetain to transfer ownership to Filament. Filament will release ownership of
         * the texture object when the Filament texture is destroyed.</li>
         * </ul>
         *
         * <pre>{@code
         *  id <MTLTexture> metalTexture = ...
         *  filamentTexture->import((intptr_t) CFBridgingRetain(metalTexture));
         *  // free to release metalTexture
         *
         *  // after using texture:
         *  engine->destroy(filamentTexture);   // metalTexture is released
         *
         * }</pre>
         *
         * <p>This method should be used as a last resort. This API is subject to change or
         * removal.</p>
         *
         * @param id a backend specific texture identifier
         *
         * @return This Builder, for chaining calls.
         */
        @NonNull
        public Builder importTexture(long id) {
            nBuilderImportTexture(mNativeBuilder, id);
            return this;
        }

        private static class BuilderFinalizer {
            private final long mNativeObject;

            BuilderFinalizer(long nativeObject) { mNativeObject = nativeObject; }

            @Override
            public void finalize() {
                try {
                    super.finalize();
                } catch (Throwable t) { // Ignore
                } finally {
                    nDestroyBuilder(mNativeObject);
                }
            }
        }
    }

    /**
     * @deprecated Use {@link com.google.android.filament.PixelBufferDescriptor} instead.
     */
    @Deprecated
    public static class PixelBufferDescriptor extends com.google.android.filament.PixelBufferDescriptor {
        public PixelBufferDescriptor(@NonNull Buffer storage,
                @NonNull Texture.Format format, @NonNull Texture.Type type,
                @IntRange(from = 1, to = 8) int alignment,
                @IntRange(from = 0) int left, @IntRange(from = 0) int top,
                @IntRange(from = 0) int stride,
                @Nullable Object handler, @Nullable Runnable callback) {
            super(storage, format, type, alignment, left, top, stride, handler, callback);
        }

        public PixelBufferDescriptor(@NonNull Buffer storage,
                @NonNull Texture.Format format, @NonNull Texture.Type type) {
            super(storage, format, type);
        }

        public PixelBufferDescriptor(@NonNull Buffer storage,
                @NonNull Texture.Format format, @NonNull Texture.Type type,
                @IntRange(from = 1, to = 8) int alignment) {
            super(storage, format, type, alignment);
        }

        public PixelBufferDescriptor(@NonNull Buffer storage,
                @NonNull Texture.Format format, @NonNull Texture.Type type,
                @IntRange(from = 1, to = 8) int alignment,
                @IntRange(from = 0) int left, @IntRange(from = 0) int top) {
            super(storage, format, type, alignment, left, top);
        }

        public PixelBufferDescriptor(@NonNull Buffer storage,
                @NonNull Texture.Format format, @NonNull Texture.Type type,
                @Nullable Object handler, @Nullable Runnable callback) {
            this(storage, format, type, 1, 0, 0, 0, handler, callback);
        }

        public PixelBufferDescriptor(@NonNull Buffer storage,
                @NonNull Texture.Format format, @NonNull Texture.Type type,
                @IntRange(from = 1, to = 8) int alignment,
                @Nullable Object handler, @Nullable Runnable callback) {
            this(storage, format, type, alignment, 0, 0, 0, handler, callback);
        }

        public PixelBufferDescriptor(@NonNull ByteBuffer storage,
                @NonNull Texture.CompressedType compressedFormat,
                @IntRange(from = 0) int compressedSizeInBytes,
                @Nullable Object handler, @Nullable Runnable callback) {
            this(storage, compressedFormat, compressedSizeInBytes);
            setCallback(handler, callback);
        }

        public PixelBufferDescriptor(@NonNull ByteBuffer storage,
                @NonNull Texture.CompressedType compressedFormat,
                @IntRange(from = 0) int compressedSizeInBytes) {
            super(storage, compressedFormat, compressedSizeInBytes);
        }
    }

    /** @return Whether a backend supports a particular format. */
    public static boolean isTextureFormatSupported(@NonNull Engine engine, @NonNull InternalFormat format) {
        return nIsTextureFormatSupported(engine.getNativeObject(), format.toFilamentNative());
    }

    /** @return Whether a backend supports mipmapping of a particular format. */
    public static boolean isTextureFormatMipmappable(@NonNull Engine engine, @NonNull InternalFormat format) {
        return nIsTextureFormatMipmappable(engine.getNativeObject(), format.toFilamentNative());
    }

    /** @return Whether particular format is compressed */
    public static boolean isTextureFormatCompressed(@NonNull InternalFormat format) {
        return nIsTextureFormatCompressed(format.toFilamentNative());
    }

    /** @return Whether this backend supports protected textures. */
    public static boolean isProtectedTexturesSupported(@NonNull Engine engine) {
        return nIsProtectedTexturesSupported(engine.getNativeObject());
    }

    /** @return Whether a backend supports texture swizzling. */
    public static boolean isTextureSwizzleSupported(@NonNull Engine engine) {
        return nIsTextureSwizzleSupported(engine.getNativeObject());
    }

    @IntRange(from = 0)
    public static int computeTextureDataSize(@NonNull Format format, @NonNull Type type, @IntRange(from = 0) int stride, @IntRange(from = 0) int height, @IntRange(from = 0) int alignment) {
        return nComputeTextureDataSize(format.toFilamentNative(), type.toFilamentNative(), stride, height, alignment);
    }

    /** @return Whether a combination of texture format, pixel format and type is valid. */
    public static boolean validatePixelFormatAndType(@NonNull InternalFormat internalFormat, @NonNull Format format, @NonNull Type type) {
        return nValidatePixelFormatAndType(internalFormat.toFilamentNative(), format.toFilamentNative(), type.toFilamentNative());
    }

    /**
     * @return the maximum size in texels of a texture of type {@code type}. At least 2048 for
     * 2D textures, 256 for 3D textures.
     */
    @IntRange(from = 0)
    public static int getMaxTextureSize(@NonNull Engine engine, @NonNull Sampler type) {
        return nGetMaxTextureSize(engine.getNativeObject(), type.toFilamentNative());
    }

    /** @return the maximum number of layers supported by texture arrays. At least 256. */
    @IntRange(from = 0)
    public static int getMaxArrayTextureLayers(@NonNull Engine engine) {
        return nGetMaxArrayTextureLayers(engine.getNativeObject());
    }

    /**
     * Returns the width of a 2D or 3D texture level
     *
     * @return Width in texel of the specified {@code level}, clamped to 1.
     * @attention If this texture is using Sampler::SAMPLER_EXTERNAL, the dimension
     * of the texture are unknown and this method always returns whatever was set on the Builder.
     */
    @IntRange(from = 0)
    public int getWidth() {
        return getWidth(BASE_LEVEL);
    }

    /**
     * Returns the width of a 2D or 3D texture level
     *
     * @param level texture level.
     *
     * @return Width in texel of the specified {@code level}, clamped to 1.
     * @attention If this texture is using Sampler::SAMPLER_EXTERNAL, the dimension
     * of the texture are unknown and this method always returns whatever was set on the Builder.
     */
    @IntRange(from = 0)
    public int getWidth(@IntRange(from = 0) int level) {
        return nGetWidth(getNativeObject(), level);
    }

    /**
     * Returns the height of a 2D or 3D texture level
     *
     * @return Height in texel of the specified {@code level}, clamped to 1.
     * @attention If this texture is using Sampler::SAMPLER_EXTERNAL, the dimension
     * of the texture are unknown and this method always returns whatever was set on the Builder.
     */
    @IntRange(from = 0)
    public int getHeight() {
        return getHeight(BASE_LEVEL);
    }

    /**
     * Returns the height of a 2D or 3D texture level
     *
     * @param level texture level.
     *
     * @return Height in texel of the specified {@code level}, clamped to 1.
     * @attention If this texture is using Sampler::SAMPLER_EXTERNAL, the dimension
     * of the texture are unknown and this method always returns whatever was set on the Builder.
     */
    @IntRange(from = 0)
    public int getHeight(@IntRange(from = 0) int level) {
        return nGetHeight(getNativeObject(), level);
    }

    /**
     * Returns the depth of a 3D texture level
     *
     * @return Depth in texel of the specified {@code level}, clamped to 1.
     * @attention If this texture is using Sampler::SAMPLER_EXTERNAL, the dimension
     * of the texture are unknown and this method always returns whatever was set on the Builder.
     */
    @IntRange(from = 0)
    public int getDepth() {
        return getDepth(BASE_LEVEL);
    }

    /**
     * Returns the depth of a 3D texture level
     *
     * @param level texture level.
     *
     * @return Depth in texel of the specified {@code level}, clamped to 1.
     * @attention If this texture is using Sampler::SAMPLER_EXTERNAL, the dimension
     * of the texture are unknown and this method always returns whatever was set on the Builder.
     */
    @IntRange(from = 0)
    public int getDepth(@IntRange(from = 0) int level) {
        return nGetDepth(getNativeObject(), level);
    }

    /**
     * Returns the maximum number of levels this texture can have.
     *
     * @return maximum number of levels this texture can have.
     * @attention If this texture is using Sampler::SAMPLER_EXTERNAL, the dimension
     * of the texture are unknown and this method always returns whatever was set on the Builder.
     */
    @IntRange(from = 0)
    public int getLevels() {
        return nGetLevels(getNativeObject());
    }

    /**
     * Return this texture Sampler as set by Builder::sampler().
     *
     * @return this texture Sampler as set by Builder::sampler()
     */
    public Sampler getTarget() {
        return EnumCache.sSamplerValues[nGetTarget(getNativeObject())];
    }

    /**
     * Return this texture InternalFormat as set by Builder::format().
     *
     * @return this texture InternalFormat as set by Builder::format().
     */
    public InternalFormat getFormat() {
        return EnumCache.sInternalFormatValues[nGetFormat(getNativeObject())];
    }

    /**
     * Updates a sub-image of a 3D texture or 2D texture array for a level.
     *
     * <p>Cubemaps are treated
     * like a 2D array of six layers.</p>
     *
     * @param engine Engine this texture is associated to.
     * @param level Level to set the image for.
     * @param xoffset Left offset of the sub-region to update.
     * @param yoffset Bottom offset of the sub-region to update.
     * @param zoffset Depth offset of the sub-region to update.
     * @param width Width of the sub-region to update.
     * @param height Height of the sub-region to update.
     * @param depth Depth of the sub-region to update.
     * @param buffer <p>Client-side buffer containing the image to set. The driver will invoke
     *                  the callback associated with this buffer when the data has been consumed.</p>
     *
     * <p>@attention {@code engine} must be the instance passed to Builder::build()
     * @attention {@code level} must be less than getLevels().
     * @attention {@code buffer}'s Texture::Format must match that of getFormat().
     * @attention This Texture instance must use Sampler::SAMPLER_3D, Sampler::SAMPLER_2D_ARRAY
     *             or Sampler::SAMPLER_CUBEMAP.</p>
     *
     * @see Builder#sampler
     */
    public void setImage(@NonNull Engine engine, @IntRange(from = 0) int level, @IntRange(from = 0) int xoffset, @IntRange(from = 0) int yoffset, @IntRange(from = 0) int zoffset, @IntRange(from = 0) int width, @IntRange(from = 0) int height, @IntRange(from = 0) int depth, @NonNull PixelBufferDescriptor buffer) {
        int type = (buffer.type != null) ? buffer.type.ordinal() : 0;
        int format = (buffer.type == Texture.Type.COMPRESSED) ?
                (buffer.compressedFormat != null ? buffer.compressedFormat.ordinal() : 0) :
                (buffer.format != null ? buffer.format.ordinal() : 0);
        int stride = (buffer.type == Texture.Type.COMPRESSED) ? buffer.compressedSizeInBytes : buffer.stride;
        nSetImage(getNativeObject(), engine.getNativeObject(), level, xoffset, yoffset, zoffset, width, height, depth, buffer.storage, buffer.storage.remaining(),
                buffer.left, buffer.top, type, buffer.alignment,
                stride, format,
                buffer.handler, buffer.callback);
    }

    /**
     * inline helper to update a 2D texture
     *
     * @see #setImage
     */
    public void setImage(@NonNull Engine engine, @IntRange(from = 0) int level, @NonNull PixelBufferDescriptor buffer) {
        int type = (buffer.type != null) ? buffer.type.ordinal() : 0;
        int format = (buffer.type == Texture.Type.COMPRESSED) ?
                (buffer.compressedFormat != null ? buffer.compressedFormat.ordinal() : 0) :
                (buffer.format != null ? buffer.format.ordinal() : 0);
        int stride = (buffer.type == Texture.Type.COMPRESSED) ? buffer.compressedSizeInBytes : buffer.stride;
        nSetImage(getNativeObject(), engine.getNativeObject(), level, buffer.storage, buffer.storage.remaining(),
                buffer.left, buffer.top, type, buffer.alignment,
                stride, format,
                buffer.handler, buffer.callback);
    }

    /**
     * inline helper to update a 2D texture
     *
     * @see #setImage
     */
    public void setImage(@NonNull Engine engine, @IntRange(from = 0) int level, @IntRange(from = 0) int xoffset, @IntRange(from = 0) int yoffset, @IntRange(from = 0) int width, @IntRange(from = 0) int height, @NonNull PixelBufferDescriptor buffer) {
        int type = (buffer.type != null) ? buffer.type.ordinal() : 0;
        int format = (buffer.type == Texture.Type.COMPRESSED) ?
                (buffer.compressedFormat != null ? buffer.compressedFormat.ordinal() : 0) :
                (buffer.format != null ? buffer.format.ordinal() : 0);
        int stride = (buffer.type == Texture.Type.COMPRESSED) ? buffer.compressedSizeInBytes : buffer.stride;
        nSetImage(getNativeObject(), engine.getNativeObject(), level, xoffset, yoffset, width, height, buffer.storage, buffer.storage.remaining(),
                buffer.left, buffer.top, type, buffer.alignment,
                stride, format,
                buffer.handler, buffer.callback);
    }

    /**
     * Specify the external image to associate with this Texture. Typically, the external
     *
     * <p>image is OS specific, and can be a video or camera frame.
     * There are many restrictions when using an external image as a texture, such as:</p>
     *
     * <ul>
     *   <li>only the level of detail (lod) 0 can be specified</li>
     *   <li>only nearest or linear filtering is supported</li>
     *   <li>the size and format of the texture is defined by the external image</li>
     *   <li>only the CLAMP_TO_EDGE wrap mode is supported</li>
     * </ul>
     *
     * @param engine Engine this texture is associated to.
     * @param image An opaque handle to a platform specific image. It must be created using Platform
     *                      specific APIs. For example PlatformEGL::createExternalImage(EGLImageKHR eglImage)
     *
     * @see PlatformEGL#createExternalImage
     * @see PlatformEGLAndroid#createExternalImage
     * @see PlatformCocoaGL#createExternalImage
     * @see PlatformCocoaTouchGL#createExternalImage
     */
    public void setExternalImage(@NonNull Engine engine, long image) {
        nSetExternalImage(getNativeObject(), engine.getNativeObject(), image);
    }

    /**
     * Specify the external image and plane to associate with this Texture. Typically, the external
     *
     * <p>image is OS specific, and can be a video or camera frame. When using this method, the
     * external image must be a planar type (such as a YUV camera frame). The plane parameter
     * selects which image plane is bound to this texture.</p>
     *
     * <p>A single external image can be bound to different Filament textures, with each texture
     * associated with a separate plane:</p>
     *
     * <pre>{@code
     * textureA->setExternalImage(engine, image, 0);
     * textureB->setExternalImage(engine, image, 1);
     *
     * }</pre>
     *
     * <p>There are many restrictions when using an external image as a texture, such as:</p>
     *
     * <ul>
     *   <li>only the level of detail (lod) 0 can be specified</li>
     *   <li>only nearest or linear filtering is supported</li>
     *   <li>the size and format of the texture is defined by the external image</li>
     *   <li>only the CLAMP_TO_EDGE wrap mode is supported</li>
     * </ul>
     *
     * @param engine Engine this texture is associated to.
     * @param image An opaque handle to a platform specific image. Supported types are
     *                      eglImageOES on Android and CVPixelBufferRef on iOS.
     * @param plane <p>The plane index of the external image to associate with this texture.</p>
     *
     * <p>This method is only meaningful on iOS with
     *                      kCVPixelFormatType_420YpCbCr8BiPlanarFullRange images. On platforms
     *                      other than iOS, this method is a no-op.</p>
     */
    public void setExternalImage(@NonNull Engine engine, long image, @IntRange(from = 0) int plane) {
        nSetExternalImage(getNativeObject(), engine.getNativeObject(), image, plane);
    }

    /**
     * Specify the external stream to associate with this Texture. Typically, the external
     *
     * <p>stream is OS specific, and can be a video or camera stream.
     * There are many restrictions when using an external stream as a texture, such as:</p>
     *
     * <ul>
     *   <li>only the level of detail (lod) 0 can be specified</li>
     *   <li>only nearest or linear filtering is supported</li>
     *   <li>the size and format of the texture is defined by the external stream</li>
     * </ul>
     *
     * @param engine Engine this texture is associated to.
     * @param stream <p>A Stream object</p>
     *
     * <p>@attention {@code engine} must be the instance passed to Builder::build()
     * @attention This Texture instance must use Sampler::SAMPLER_EXTERNAL, or it has no effect</p>
     *
     * @see Builder#sampler
     * @see Stream
     */
    public void setExternalStream(@NonNull Engine engine, @Nullable Stream stream) {
        nSetExternalStream(getNativeObject(), engine.getNativeObject(), stream != null ? stream.getNativeObject() : 0);
    }

    /**
     * Generates all the mipmap levels automatically.
     *
     * <p>This requires the texture to have a
     * color-renderable format and usage set to BLIT_SRC | BLIT_DST. If unspecified,
     * usage bits are set automatically.</p>
     *
     * @param engine <p>Engine this texture is associated to.</p>
     *
     * <p>@attention {@code engine} must be the instance passed to Builder::build()
     * @attention This Texture instance must NOT use SamplerType::SAMPLER_3D or it has no effect</p>
     */
    public void generateMipmaps(@NonNull Engine engine) {
        nGenerateMipmaps(getNativeObject(), engine.getNativeObject());
    }

    /**
     * This non-blocking method checks if the resource has finished creation <i>successfully</i>.
     *
     * <p>If the
     * resource creation was initiated asynchronously, it will return true only after all related
     * asynchronous tasks are complete, and only if none of them was canceled. If the resource was
     * created normally without using async method, it will always return true.</p>
     *
     * <p>A canceled asynchronous creation never populates the resource, so this method keeps returning
     * false for it. The object itself remains valid and must still be destroyed as usual.</p>
     *
     * @return Whether the resource is created and usable.
     *
     * @see Builder#async
     */
    public boolean isCreationComplete() {
        return nIsCreationComplete(getNativeObject());
    }

    public long getNativeObject() {
        if (mNativeObject == 0) {
            throw new IllegalStateException("Calling method on destroyed Texture");
        }
        return mNativeObject;
    }

    void clearNativeObject() {
        mNativeObject = 0;
    }

    private static native boolean nIsTextureFormatSupported(long nativeEngine, int format);
    private static native boolean nIsTextureFormatMipmappable(long nativeEngine, int format);
    private static native boolean nIsTextureFormatCompressed(int format);
    private static native boolean nIsProtectedTexturesSupported(long nativeEngine);
    private static native boolean nIsTextureSwizzleSupported(long nativeEngine);
    @IntRange(from = 0)
    private static native int nComputeTextureDataSize(int format, int type, @IntRange(from = 0) int stride, @IntRange(from = 0) int height, @IntRange(from = 0) int alignment);
    private static native boolean nValidatePixelFormatAndType(int internalFormat, int format, int type);
    @IntRange(from = 0)
    private static native int nGetMaxTextureSize(long nativeEngine, int type);
    @IntRange(from = 0)
    private static native int nGetMaxArrayTextureLayers(long nativeEngine);
    @IntRange(from = 0)
    private static native int nGetWidth(long nativeTexture, @IntRange(from = 0) int level);
    @IntRange(from = 0)
    private static native int nGetHeight(long nativeTexture, @IntRange(from = 0) int level);
    @IntRange(from = 0)
    private static native int nGetDepth(long nativeTexture, @IntRange(from = 0) int level);
    @IntRange(from = 0)
    private static native int nGetLevels(long nativeTexture);
    private static native int nGetTarget(long nativeTexture);
    private static native int nGetFormat(long nativeTexture);
    private static native void nSetImage(long nativeTexture, long nativeEngine, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, Buffer storage, int remaining, int left, int top, int type, int alignment, int stride, int format, Object handler, Runnable callback);
    private static native void nSetImage(long nativeTexture, long nativeEngine, int level, Buffer storage, int remaining, int left, int top, int type, int alignment, int stride, int format, Object handler, Runnable callback);
    private static native void nSetImage(long nativeTexture, long nativeEngine, int level, int xoffset, int yoffset, int width, int height, Buffer storage, int remaining, int left, int top, int type, int alignment, int stride, int format, Object handler, Runnable callback);
    private static native void nSetExternalImage(long nativeTexture, long nativeEngine, long image);
    private static native void nSetExternalImage(long nativeTexture, long nativeEngine, long image, @IntRange(from = 0) int plane);
    private static native void nSetExternalStream(long nativeTexture, long nativeEngine, long nativeStream);
    private static native void nGenerateMipmaps(long nativeTexture, long nativeEngine);
    private static native boolean nIsCreationComplete(long nativeTexture);
    private static native long nCreateBuilder();
    private static native void nDestroyBuilder(long nativeBuilder);
    private static native void nBuilderWidth(long nativeBuilder, int width);
    private static native void nBuilderHeight(long nativeBuilder, int height);
    private static native void nBuilderDepth(long nativeBuilder, int depth);
    private static native void nBuilderLevels(long nativeBuilder, int levels);
    private static native void nBuilderSamples(long nativeBuilder, int samples);
    private static native void nBuilderSampler(long nativeBuilder, int target);
    private static native void nBuilderFormat(long nativeBuilder, int format);
    private static native void nBuilderUsage(long nativeBuilder, int usage);
    private static native void nBuilderSwizzle(long nativeBuilder, int r, int g, int b, int a);
    private static native void nBuilderName(long nativeBuilder, String name);
    private static native void nBuilderExternal(long nativeBuilder);
    private static native long nBuilderBuild(long nativeBuilder, long nativeEngine);
    private static native void nBuilderImportTexture(long nativeBuilder, long id);
}

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.
