/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.

package com.google.android.filament;

import androidx.annotation.NonNull;

/** TextureSampler defines how a texture is accessed. */
public class TextureSampler {
    static final class EnumCache {
        static final CompareFunc[] sCompareFuncValues = CompareFunc.values();
        static final CompareMode[] sCompareModeValues = CompareMode.values();
        static final MagFilter[] sMagFilterValues = MagFilter.values();
        static final MinFilter[] sMinFilterValues = MinFilter.values();
        static final WrapMode[] sWrapModeValues = WrapMode.values();
    }

    /* package */ int mSampler;

    /** Sampler Wrap mode */
    public enum WrapMode {
        /**
         * clamp-to-edge.
         *
         * <p>The edge of the texture extends to infinity.</p>
         */
        CLAMP_TO_EDGE,
        /**
         * repeat.
         *
         * <p>The texture infinitely repeats in the wrap direction.</p>
         */
        REPEAT,
        /**
         * mirrored-repeat.
         *
         * <p>The texture infinitely repeats and mirrors in the wrap direction.</p>
         */
        MIRRORED_REPEAT;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /** Sampler minification filter */
    public enum MinFilter {
        /**
         * No filtering.
         *
         * <p>Nearest neighbor is used.</p>
         */
        NEAREST,
        /**
         * Box filtering.
         *
         * <p>Weighted average of 4 neighbors is used.</p>
         */
        LINEAR,
        /**
         * Mip-mapping is activated.
         *
         * <p>But no filtering occurs.</p>
         */
        NEAREST_MIPMAP_NEAREST,
        /** Box filtering within a mip-map level. */
        LINEAR_MIPMAP_NEAREST,
        /** Mip-map levels are interpolated, but no other filtering occurs. */
        NEAREST_MIPMAP_LINEAR,
        /** Both interpolated Mip-mapping and linear filtering are used. */
        LINEAR_MIPMAP_LINEAR;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /** Sampler magnification filter */
    public enum MagFilter {
        /**
         * No filtering.
         *
         * <p>Nearest neighbor is used.</p>
         */
        NEAREST,
        /**
         * Box filtering.
         *
         * <p>Weighted average of 4 neighbors is used.</p>
         */
        LINEAR;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /** Sampler compare mode */
    public enum CompareMode {
        NONE,
        COMPARE_TO_TEXTURE;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /** comparison function for the depth / stencil sampler */
    public enum CompareFunc {
        /** Less or equal */
        LE,
        /** Greater or equal */
        GE,
        /** Strictly less than */
        L,
        /** Strictly greater than */
        G,
        /** Equal */
        E,
        /** Not equal */
        NE,
        /**
         * Always.
         *
         * <p>Depth / stencil testing is deactivated.</p>
         */
        A,
        /**
         * Never.
         *
         * <p>The depth / stencil test always fails.</p>
         */
        N;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /**
     * Creates a default sampler.
     *
     * <p>The default parameters are:</p>
     *
     * <ul>
     *   <li>filterMag      : NEAREST</li>
     *   <li>filterMin      : NEAREST</li>
     *   <li>wrapS          : CLAMP_TO_EDGE</li>
     *   <li>wrapT          : CLAMP_TO_EDGE</li>
     *   <li>wrapR          : CLAMP_TO_EDGE</li>
     *   <li>compareMode    : NONE</li>
     *   <li>compareFunc    : Less or equal</li>
     *   <li>no anisotropic filtering</li>
     * </ul>
     */
    public TextureSampler() {
        mSampler = nCreateTextureSampler();
    }

    /**
     * Creates a TextureSampler with the default parameters but setting the filtering and wrap modes.
     *
     * @param minMag filtering for both minification and magnification
     */
    public TextureSampler(@NonNull MagFilter minMag) {
        this(minMag, WrapMode.CLAMP_TO_EDGE);
    }

    /**
     * Creates a TextureSampler with the default parameters but setting the filtering and wrap modes.
     *
     * @param minMag filtering for both minification and magnification
     * @param str wrapping mode for all texture coordinate axes
     */
    public TextureSampler(@NonNull MagFilter minMag, @NonNull WrapMode str) {
        mSampler = nCreateTextureSamplerMagFilterWrapMode(minMag.toFilamentNative(), str.toFilamentNative());
    }

    /**
     * Creates a TextureSampler with the default parameters but setting the filtering and wrap modes.
     *
     * @param min filtering for minification
     * @param mag filtering for magnification
     */
    public TextureSampler(@NonNull MinFilter min, @NonNull MagFilter mag) {
        this(min, mag, WrapMode.CLAMP_TO_EDGE);
    }

    /**
     * Creates a TextureSampler with the default parameters but setting the filtering and wrap modes.
     *
     * @param min filtering for minification
     * @param mag filtering for magnification
     * @param str wrapping mode for all texture coordinate axes
     */
    public TextureSampler(@NonNull MinFilter min, @NonNull MagFilter mag, @NonNull WrapMode str) {
        mSampler = nCreateTextureSamplerMinFilterMagFilterWrapMode(min.toFilamentNative(), mag.toFilamentNative(), str.toFilamentNative());
    }

    /**
     * Creates a TextureSampler with the default parameters but setting the filtering and wrap modes.
     *
     * @param min filtering for minification
     * @param mag filtering for magnification
     * @param s wrap mode for the s (horizontal)texture coordinate
     * @param t wrap mode for the t (vertical) texture coordinate
     * @param r wrap mode for the r (depth) texture coordinate
     */
    public TextureSampler(@NonNull MinFilter min, @NonNull MagFilter mag, @NonNull WrapMode s, @NonNull WrapMode t, @NonNull WrapMode r) {
        mSampler = nCreateTextureSamplerMinFilterMagFilterWrapModeWrapModeWrapMode(min.toFilamentNative(), mag.toFilamentNative(), s.toFilamentNative(), t.toFilamentNative(), r.toFilamentNative());
    }

    /**
     * Creates a TextureSampler with the default parameters but setting the compare mode and function
     *
     * @param mode Compare mode
     */
    public TextureSampler(@NonNull CompareMode mode) {
        this(mode, CompareFunc.LE);
    }

    /**
     * Creates a TextureSampler with the default parameters but setting the compare mode and function
     *
     * @param mode Compare mode
     * @param func Compare function
     */
    public TextureSampler(@NonNull CompareMode mode, @NonNull CompareFunc func) {
        mSampler = nCreateTextureSamplerCompareModeCompareFunc(mode.toFilamentNative(), func.toFilamentNative());
    }

    /**
     * Sets the minification filter
     *
     * @param v Minification filter
     */
    public void setMinFilter(@NonNull MinFilter v) {
        mSampler = nSetMinFilter(mSampler, v.toFilamentNative());
    }

    /**
     * Sets the magnification filter
     *
     * @param v Magnification filter
     */
    public void setMagFilter(@NonNull MagFilter v) {
        mSampler = nSetMagFilter(mSampler, v.toFilamentNative());
    }

    /**
     * Sets the wrap mode for the s (horizontal) texture coordinate
     *
     * @param v wrap mode
     */
    public void setWrapModeS(@NonNull WrapMode v) {
        mSampler = nSetWrapModeS(mSampler, v.toFilamentNative());
    }

    /**
     * Sets the wrap mode for the t (vertical) texture coordinate
     *
     * @param v wrap mode
     */
    public void setWrapModeT(@NonNull WrapMode v) {
        mSampler = nSetWrapModeT(mSampler, v.toFilamentNative());
    }

    /**
     * Sets the wrap mode for the r (depth, for 3D textures) texture coordinate
     *
     * @param v wrap mode
     */
    public void setWrapModeR(@NonNull WrapMode v) {
        mSampler = nSetWrapModeR(mSampler, v.toFilamentNative());
    }

    /**
     * This controls anisotropic filtering.
     *
     * @param anisotropy Amount of anisotropy, should be a power-of-two. The default is 1.
     *                   The maximum permissible value is 128.
     */
    public void setAnisotropy(float anisotropy) {
        mSampler = nSetAnisotropy(mSampler, anisotropy);
    }

    /**
     * Sets the compare mode and function.
     *
     * @param mode Compare mode
     */
    public void setCompareMode(@NonNull CompareMode mode) {
        setCompareMode(mode, CompareFunc.LE);
    }

    /**
     * Sets the compare mode and function.
     *
     * @param mode Compare mode
     * @param func Compare function
     */
    public void setCompareMode(@NonNull CompareMode mode, @NonNull CompareFunc func) {
        mSampler = nSetCompareMode(mSampler, mode.toFilamentNative(), func.toFilamentNative());
    }

    /** returns the minification filter value */
    public MinFilter getMinFilter() {
        return EnumCache.sMinFilterValues[nGetMinFilter(mSampler)];
    }

    /** returns the magnification filter value */
    public MagFilter getMagFilter() {
        return EnumCache.sMagFilterValues[nGetMagFilter(mSampler)];
    }

    /** returns the s-coordinate wrap mode (horizontal) */
    public WrapMode getWrapModeS() {
        return EnumCache.sWrapModeValues[nGetWrapModeS(mSampler)];
    }

    /** returns the t-coordinate wrap mode (vertical) */
    public WrapMode getWrapModeT() {
        return EnumCache.sWrapModeValues[nGetWrapModeT(mSampler)];
    }

    /** returns the r-coordinate wrap mode (depth) */
    public WrapMode getWrapModeR() {
        return EnumCache.sWrapModeValues[nGetWrapModeR(mSampler)];
    }

    /** returns the anisotropy value */
    public float getAnisotropy() {
        return nGetAnisotropy(mSampler);
    }

    /** returns the compare mode */
    public CompareMode getCompareMode() {
        return EnumCache.sCompareModeValues[nGetCompareMode(mSampler)];
    }

    /** returns the compare function */
    public CompareFunc getCompareFunc() {
        return EnumCache.sCompareFuncValues[nGetCompareFunc(mSampler)];
    }


    private static native int nCreateTextureSampler();
    private static native int nCreateTextureSamplerMagFilterWrapMode(int minMag, int str);
    private static native int nCreateTextureSamplerMinFilterMagFilterWrapMode(int min, int mag, int str);
    private static native int nCreateTextureSamplerMinFilterMagFilterWrapModeWrapModeWrapMode(int min, int mag, int s, int t, int r);
    private static native int nCreateTextureSamplerCompareModeCompareFunc(int mode, int func);
    private static native int nSetMinFilter(int sampler, int v);
    private static native int nSetMagFilter(int sampler, int v);
    private static native int nSetWrapModeS(int sampler, int v);
    private static native int nSetWrapModeT(int sampler, int v);
    private static native int nSetWrapModeR(int sampler, int v);
    private static native int nSetAnisotropy(int sampler, float anisotropy);
    private static native int nSetCompareMode(int sampler, int mode, int func);
    private static native int nGetMinFilter(int sampler);
    private static native int nGetMagFilter(int sampler);
    private static native int nGetWrapModeS(int sampler);
    private static native int nGetWrapModeT(int sampler);
    private static native int nGetWrapModeR(int sampler);
    private static native float nGetAnisotropy(int sampler);
    private static native int nGetCompareMode(int sampler);
    private static native int nGetCompareFunc(int sampler);
}

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.
