/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.

package com.google.android.filament;

import java.lang.IllegalStateException;

import java.util.EnumSet;

import androidx.annotation.IntRange;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.annotation.RestrictTo;
import androidx.annotation.Size;

import com.google.android.filament.proguard.UsedByNative;

/**
 * A View encompasses all the state needed for rendering a Scene.
 *
 * <p>Renderer::render() operates on View objects. These View objects specify important parameters
 * such as:</p>
 *
 * <ul>
 *   <li>The Scene</li>
 *   <li>The Camera</li>
 *   <li>The Viewport</li>
 *   <li>Some rendering parameters
 * For example, in a game, a View could be used for the main scene and another one for the
 * game's user interface. More View instances could be used for creating special effects (e.g.
 * a View is akin to a rendering pass).</li>
 * </ul>
 *
 * <p>View instances are heavy objects that internally cache a lot of data needed for rendering.
 * It is not advised for an application to use many View objects.</p>
 *
 * @see Renderer
 * @see Scene
 * @see Camera
 * @see RenderTarget
 */
public class View {
    static final class EnumCache {
        static final AmbientOcclusion[] sAmbientOcclusionValues = AmbientOcclusion.values();
        static final AntiAliasing[] sAntiAliasingValues = AntiAliasing.values();
        static final BlendMode[] sBlendModeValues = BlendMode.values();
        static final Dithering[] sDitheringValues = Dithering.values();
        static final ShadowType[] sShadowTypeValues = ShadowType.values();
    }

    private long mNativeObject;
    private @Nullable Scene mScene;
    private @Nullable RenderTarget mRenderTarget;
    private @Nullable Viewport mViewport;
    private @Nullable Camera mCamera;
    private @Nullable TemporalAntiAliasingOptions mTemporalAntiAliasingOptions;
    private @Nullable ScreenSpaceReflectionsOptions mScreenSpaceReflectionsOptions;
    private @Nullable GuardBandOptions mGuardBandOptions;
    private @Nullable MultiSampleAntiAliasingOptions mMultiSampleAntiAliasingOptions;
    private @Nullable ColorGrading mColorGrading;
    private @Nullable AmbientOcclusionOptions mAmbientOcclusionOptions;
    private @Nullable BloomOptions mBloomOptions;
    private @Nullable FogOptions mFogOptions;
    private @Nullable DepthOfFieldOptions mDepthOfFieldOptions;
    private @Nullable VignetteOptions mVignetteOptions;
    private @Nullable DynamicResolutionOptions mDynamicResolutionOptions;
    private @Nullable RenderQuality mRenderQuality;
    private @Nullable VsmShadowOptions mVsmShadowOptions;
    private @Nullable SoftShadowOptions mSoftShadowOptions;
    private @Nullable StereoscopicOptions mStereoscopicOptions;

    /** Generic quality level. */
    public enum QualityLevel {
        LOW,
        MEDIUM,
        HIGH,
        ULTRA;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    public enum BlendMode {
        OPAQUE,
        TRANSLUCENT;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /**
     * List of available post-processing anti-aliasing techniques.
     *
     * @see #setAntiAliasing
     * @see #getAntiAliasing
     * @see #setSampleCount
     */
    public enum AntiAliasing {
        /** no anti aliasing performed as part of post-processing */
        NONE,
        /** FXAA is a low-quality but very efficient type of anti-aliasing. (default). */
        FXAA;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /** List of available post-processing dithering techniques. */
    public enum Dithering {
        /** No dithering */
        NONE,
        /** Temporal dithering (default) */
        TEMPORAL;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /**
     * List of available shadow mapping techniques.
     *
     * @see #setShadowType
     */
    public enum ShadowType {
        /** percentage-closer filtered shadows (default) */
        PCF,
        /** exponential variance shadows (EVSM) */
        VSM,
        /** @deprecated falls back to PCSS */
        DPCF,
        /** EVSM with soft shadows and contact hardening */
        PCSS,
        /** EVSM with soft shadows and contact hardening */
        PCFd;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /**
     * List of available ambient occlusion techniques
     *
     * @deprecated use AmbientOcclusionOptions::enabled instead
     */
    public enum AmbientOcclusion {
        /** No Ambient Occlusion */
        NONE,
        /** Basic, sampling SSAO */
        SSAO;

        /** @return the value of this enum constant as used by the native Filament engine. */
        public int toFilamentNative() { return ordinal(); }
    }

    /**
     * List of available tone-mapping operators
     *
     * @deprecated Use ColorGrading instead
     */
    @Deprecated
    public enum ToneMapping {
        /**
         * Equivalent to disabling tone-mapping.
         */
        LINEAR,

        /**
         * The Academy Color Encoding System (ACES).
         */
        ACES
    }

    /**
     * Used to select buffers.
     */
    public enum TargetBufferFlags {
        /**
         * Color 0 buffer selected.
         */
        COLOR0(0x1),
        /**
         * Color 1 buffer selected.
         */
        COLOR1(0x2),
        /**
         * Color 2 buffer selected.
         */
        COLOR2(0x4),
        /**
         * Color 3 buffer selected.
         */
        COLOR3(0x8),
        /**
         * Depth buffer selected.
         */
        DEPTH(0x10),
        /**
         * Stencil buffer selected.
         */
        STENCIL(0x20);

        /*
         * No buffer selected
         */
        public static EnumSet<TargetBufferFlags> NONE = EnumSet.noneOf(TargetBufferFlags.class);

        /*
         * All color buffers selected
         */
        public static EnumSet<TargetBufferFlags> ALL_COLOR =
                EnumSet.of(COLOR0, COLOR1, COLOR2, COLOR3);
        /**
         * Depth and stencil buffer selected.
         */
        public static EnumSet<TargetBufferFlags> DEPTH_STENCIL = EnumSet.of(DEPTH, STENCIL);
        /**
         * All buffers are selected.
         */
        public static EnumSet<TargetBufferFlags> ALL = EnumSet.range(COLOR0, STENCIL);

        private int mFlags;

        TargetBufferFlags(int flags) {
            mFlags = flags;
        }

        static int flags(EnumSet<TargetBufferFlags> flags) {
            int result = 0;
            for (TargetBufferFlags flag : flags) {
                result |= flag.mFlags;
            }
            return result;
        }
    }

    View(long nativeObject) {
        mNativeObject = nativeObject;
    }

    @NonNull
    @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
    public static View wrap(long nativeObject) {
        return new View(nativeObject);
    }

    /**
     * Sets the View's name.
     *
     * <p>Only useful for debugging.</p>
     *
     * @param name Pointer to the View's name. The string is copied.
     */
    public void setName(@NonNull String name) {
        nSetName(getNativeObject(), name);
    }

    /**
     * Returns the View's name
     *
     * @return <p>a pointer owned by the View instance to the View's name.</p>
     *
     * <p>@attention Do <i>not</i> free the pointer or modify its content.</p>
     */
    @Nullable
    public String getName() {
        return nGetName(getNativeObject());
    }

    /**
     * Set this View instance's Scene.
     *
     * <p>There is no reference-counting.
     *  If a Scene is destroyed before it is dissociated from a View, it will be automatically
     *  dissociated from that View (setting the View's Scene to nullptr).</p>
     *
     * @param scene Associate the specified Scene to this View. A Scene can be associated to
     *              several View instances.
     *              {@code scene} can be nullptr to dissociate the currently set Scene
     *              from this View.
     *              The View doesn't take ownership of the Scene pointer (which
     *              acts as a reference).
     */
    public void setScene(@Nullable Scene scene) {
        mScene = scene;
        nSetScene(getNativeObject(), scene != null ? scene.getNativeObject() : 0);
    }

    /**
     * Returns the Scene currently associated with this View.
     *
     * @return A pointer to the Scene associated to this View. nullptr if no Scene is set.
     */
    @Nullable
    public Scene getScene() {
        return mScene;
    }

    /**
     * Specifies an offscreen render target to render into.
     *
     * <p>By default, the view's associated render target is nullptr, which corresponds to the
     * SwapChain associated with the engine.</p>
     *
     * <p>A view with a custom render target cannot rely on Renderer::ClearOptions, which only apply
     * to the SwapChain. Such view can use a Skybox instead.</p>
     *
     * @param renderTarget Render target associated with view, or nullptr for the swap chain.
     */
    public void setRenderTarget(@Nullable RenderTarget renderTarget) {
        mRenderTarget = renderTarget;
        nSetRenderTarget(getNativeObject(), renderTarget != null ? renderTarget.getNativeObject() : 0);
    }

    /**
     * Gets the offscreen render target associated with this view.
     *
     * <p>Returns nullptr if the render target is the swap chain (which is default).</p>
     *
     * @see #setRenderTarget
     */
    @Nullable
    public RenderTarget getRenderTarget() {
        return mRenderTarget;
    }

    /**
     * Sets the rectangular region to render to.
     *
     * <p>The viewport specifies where the content of the View (i.e. the Scene) is rendered in
     * the render target. The Render target is automatically clipped to the Viewport.</p>
     *
     * @param viewport The Viewport to render the Scene into. The Viewport is a value-type, it is
     *                  therefore copied. The parameter can be discarded after this call returns.
     */
    public void setViewport(@NonNull Viewport viewport) {
        mViewport = viewport;
        nSetViewport(getNativeObject(), viewport.getLeft(), viewport.getBottom(), viewport.getWidth(), viewport.getHeight());
    }

    /**
     * Returns the rectangular region that gets rendered to.
     *
     * @return A constant reference to View's viewport.
     */
    @NonNull
    public Viewport getViewport() {
        if (mViewport == null) {
            mViewport = new Viewport();
        }
        return mViewport;
    }

    /**
     * Sets this View's Camera.
     *
     * <p>There is no reference-counting.
     *  Make sure to dissociate a Camera from all Views before destroying it.</p>
     *
     * @param camera Associate the specified Camera to this View. A Camera can be associated to
     *                  several View instances.
     *                  {@code camera} can be nullptr to dissociate the currently set Camera from this
     *                  View.
     *                  The View doesn't take ownership of the Camera pointer (which
     *                  acts as a reference).
     *                  If the camera isn't set, Renderer::render() will result in a no-op.
     */
    public void setCamera(@Nullable Camera camera) {
        mCamera = camera;
        nSetCamera(getNativeObject(), camera != null ? camera.getNativeObject() : 0);
    }

    /**
     * Returns whether a Camera is set.
     *
     * @return true if a camera is set.
     *
     * @see #setCamera
     */
    public boolean hasCamera() {
        return nHasCamera(getNativeObject());
    }

    /**
     * Returns the Camera currently associated with this View.
     *
     * <p>Undefined behavior if hasCamera() is false.</p>
     *
     * @return A reference to the Camera associated to this View if hasCamera() is true.
     *
     * @see #hasCamera
     */
    @Nullable
    public Camera getCamera() {
        return mCamera;
    }

    /**
     * Sets whether a channel must clear the depth buffer before all primitives are rendered.
     *
     * <p>Channel depth clear is off by default for all channels.
     * This is orthogonal to Renderer::setClearOptions().</p>
     *
     * @param channel between 0 and 7
     * @param enabled true to enable clear, false to disable
     */
    public void setChannelDepthClearEnabled(@IntRange(from = 0) int channel, boolean enabled) {
        nSetChannelDepthClearEnabled(getNativeObject(), channel, enabled);
    }

    /**
     * @param channel between 0 and 7
     *
     * @return true if this channel has depth clear enabled.
     */
    public boolean isChannelDepthClearEnabled(@IntRange(from = 0) int channel) {
        return nIsChannelDepthClearEnabled(getNativeObject(), channel);
    }

    /**
     * Sets the blending mode used to draw the view into the SwapChain.
     *
     * @param blendMode either BlendMode::OPAQUE or BlendMode::TRANSLUCENT
     *
     * @see #getBlendMode
     */
    public void setBlendMode(@NonNull BlendMode blendMode) {
        nSetBlendMode(getNativeObject(), blendMode.toFilamentNative());
    }

    /**
     * @return blending mode set by setBlendMode
     *
     * @see #setBlendMode
     */
    public BlendMode getBlendMode() {
        return EnumCache.sBlendModeValues[nGetBlendMode(getNativeObject())];
    }

    /**
     * Sets which layers are visible.
     *
     * <p>Renderable objects can have one or several layers associated to them. Layers are
     * represented with an 8-bits bitmask, where each bit corresponds to a layer.</p>
     *
     * <p>This call sets which of those layers are visible. Renderables in invisible layers won't be
     * rendered.</p>
     *
     * <p>By default, only layer 0 (bitmask 0x01) is visible.
     * @note This is a convenient way to quickly show or hide sets of Renderable objects.</p>
     *
     * @param select a bitmask specifying which layer to set or clear using {@code values}.
     * @param values a bitmask where each bit sets the visibility of the corresponding layer
     *                  (1: visible, 0: invisible), only layers in {@code select} are affected.
     *
     * @see RenderableManager#setLayerMask
     */
    public void setVisibleLayers(@IntRange(from = 0) int select, @IntRange(from = 0) int values) {
        nSetVisibleLayers(getNativeObject(), select, values);
    }

    /**
     * Helper function to enable or disable a visibility layer.
     *
     * @param layer layer between 0 and 7 to enable or disable
     * @param enabled true to enable the layer, false to disable it
     *
     * @see RenderableManager#setLayerMask
     */
    public void setLayerEnabled(@IntRange(from = 0) int layer, boolean enabled) {
        nSetLayerEnabled(getNativeObject(), layer, enabled);
    }

    /**
     * Get the visible layers.
     *
     * @see View#setVisibleLayers
     */
    @IntRange(from = 0)
    public int getVisibleLayers() {
        return nGetVisibleLayers(getNativeObject());
    }

    /**
     * Enables or disables shadow mapping.
     *
     * <p>Enabled by default.</p>
     *
     * @param enabled true enables shadow mapping, false disables it.
     *
     * @see LightManager.Builder#castShadows
     * @see RenderableManager.Builder#receiveShadows
     * @see RenderableManager.Builder#castShadows
     */
    public void setShadowingEnabled(boolean enabled) {
        nSetShadowingEnabled(getNativeObject(), enabled);
    }

    /** @return whether shadowing is enabled */
    public boolean isShadowingEnabled() {
        return nIsShadowingEnabled(getNativeObject());
    }

    /**
     * Enables or disables screen space refraction.
     *
     * <p>Enabled by default.</p>
     *
     * @param enabled true enables screen space refraction, false disables it.
     */
    public void setScreenSpaceRefractionEnabled(boolean enabled) {
        nSetScreenSpaceRefractionEnabled(getNativeObject(), enabled);
    }

    /** @return whether screen space refraction is enabled */
    public boolean isScreenSpaceRefractionEnabled() {
        return nIsScreenSpaceRefractionEnabled(getNativeObject());
    }

    /**
     * Sets how many samples are to be used for MSAA in the post-process stage.
     *
     * <p>Default is 1 and disables MSAA.
     * Note that post-processing is disabled at FL0. If the feature level is
     * set to 0, values passed to this function are ignored.</p>
     *
     * <p>Antialiasing can also be performed in the post-processing stage, generally at lower
     *       cost. See setAntiAliasing.</p>
     *
     * @deprecated use setMultiSampleAntiAliasingOptions instead
     *
     * @see #setAntiAliasing
     */
    public void setSampleCount() {
        setSampleCount(1);
    }

    /**
     * Sets how many samples are to be used for MSAA in the post-process stage.
     *
     * <p>Default is 1 and disables MSAA.
     * Note that post-processing is disabled at FL0. If the feature level is
     * set to 0, values passed to this function are ignored.</p>
     *
     * <p>Antialiasing can also be performed in the post-processing stage, generally at lower
     *       cost. See setAntiAliasing.</p>
     *
     * @param count number of samples to use for multi-sampled antialiasing.
     *              0: treated as 1
     *              1: no antialiasing
     *              n: sample count. Effective sample could be different depending on the
     *                 GPU capabilities.
     *
     * @deprecated use setMultiSampleAntiAliasingOptions instead
     *
     * @see #setAntiAliasing
     */
    public void setSampleCount(@IntRange(from = 0) int count) {
        nSetSampleCount(getNativeObject(), count);
    }

    /**
     * Returns the sample count set by setSampleCount().
     *
     * <p>Effective sample count could be different.
     * A value of 0 or 1 means MSAA is disabled.</p>
     *
     * @return value set by setSampleCount().
     *
     * @deprecated use getMultiSampleAntiAliasingOptions instead
     */
    @IntRange(from = 0)
    public int getSampleCount() {
        return nGetSampleCount(getNativeObject());
    }

    /**
     * Enables or disables antialiasing in the post-processing stage.
     *
     * <p>Enabled by default.
     * MSAA can be enabled in addition, see setSampleCount().</p>
     *
     * <p>For MSAA antialiasing, see setSamplerCount().</p>
     *
     * @param type FXAA for enabling, NONE for disabling antialiasing.
     *
     * @see #setSampleCount
     */
    public void setAntiAliasing(@NonNull AntiAliasing type) {
        nSetAntiAliasing(getNativeObject(), type.toFilamentNative());
    }

    /**
     * Queries whether antialiasing is enabled during the post-processing stage.
     *
     * <p>To query
     * whether MSAA is enabled, see getSampleCount().</p>
     *
     * @return The post-processing antialiasing method.
     */
    public AntiAliasing getAntiAliasing() {
        return EnumCache.sAntiAliasingValues[nGetAntiAliasing(getNativeObject())];
    }

    /**
     * Enables or disable temporal antialiasing (TAA).
     *
     * <p>Disabled by default.</p>
     *
     * @param options temporal antialiasing options
     */
    public void setTemporalAntiAliasingOptions(@NonNull TemporalAntiAliasingOptions options) {
        mTemporalAntiAliasingOptions = options;
        nSetTemporalAntiAliasingOptions(getNativeObject(), options.filterWidth, options.feedback, options.lodBias, options.sharpness, options.enabled, options.upscaling, options.filterHistory, options.filterInput, options.useYCoCg, options.hdr, options.boxType.toFilamentNative(), options.boxClipping.toFilamentNative(), options.jitterPattern.toFilamentNative(), options.varianceGamma, options.preventFlickering, options.historyReprojection);
    }

    /**
     * Returns temporal antialiasing options.
     *
     * @return temporal antialiasing options
     */
    @NonNull
    public TemporalAntiAliasingOptions getTemporalAntiAliasingOptions() {
        if (mTemporalAntiAliasingOptions == null) {
            mTemporalAntiAliasingOptions = new TemporalAntiAliasingOptions();
        }
        return mTemporalAntiAliasingOptions;
    }

    /**
     * Enables or disable screen-space reflections.
     *
     * <p>Disabled by default.</p>
     *
     * @param options screen-space reflections options
     */
    public void setScreenSpaceReflectionsOptions(@NonNull ScreenSpaceReflectionsOptions options) {
        mScreenSpaceReflectionsOptions = options;
        nSetScreenSpaceReflectionsOptions(getNativeObject(), options.thickness, options.bias, options.maxDistance, options.stride, options.enabled);
    }

    /**
     * Returns screen-space reflections options.
     *
     * @return screen-space reflections options
     */
    @NonNull
    public ScreenSpaceReflectionsOptions getScreenSpaceReflectionsOptions() {
        if (mScreenSpaceReflectionsOptions == null) {
            mScreenSpaceReflectionsOptions = new ScreenSpaceReflectionsOptions();
        }
        return mScreenSpaceReflectionsOptions;
    }

    /**
     * Enables or disable screen-space guard band.
     *
     * <p>Disabled by default.</p>
     *
     * @param options guard band options
     */
    public void setGuardBandOptions(@NonNull GuardBandOptions options) {
        mGuardBandOptions = options;
        nSetGuardBandOptions(getNativeObject(), options.enabled);
    }

    /**
     * Returns screen-space guard band options.
     *
     * @return guard band options
     */
    @NonNull
    public GuardBandOptions getGuardBandOptions() {
        if (mGuardBandOptions == null) {
            mGuardBandOptions = new GuardBandOptions();
        }
        return mGuardBandOptions;
    }

    /**
     * Enables or disable multi-sample antialiasing (MSAA).
     *
     * <p>Disabled by default.
     * Note that MSAA is a post-processing effect, and post-processing is disabled at FL0.
     * If the feature level is set to 0, values passed to this function are ignored.</p>
     *
     * @param options multi-sample antialiasing options
     */
    public void setMultiSampleAntiAliasingOptions(@NonNull MultiSampleAntiAliasingOptions options) {
        mMultiSampleAntiAliasingOptions = options;
        nSetMultiSampleAntiAliasingOptions(getNativeObject(), options.enabled, options.sampleCount, options.customResolve);
    }

    /**
     * Returns multi-sample antialiasing options.
     *
     * @return multi-sample antialiasing options
     */
    @NonNull
    public MultiSampleAntiAliasingOptions getMultiSampleAntiAliasingOptions() {
        if (mMultiSampleAntiAliasingOptions == null) {
            mMultiSampleAntiAliasingOptions = new MultiSampleAntiAliasingOptions();
        }
        return mMultiSampleAntiAliasingOptions;
    }

    /**
     * Sets this View's color grading transforms.
     *
     * <p>There is no reference-counting.
     *  Make sure to dissociate a ColorGrading from all Views before destroying it.</p>
     *
     * @param colorGrading Associate the specified ColorGrading to this View. A ColorGrading can be
     *                     associated to several View instances.
     *                     {@code colorGrading} can be nullptr to dissociate the currently set
     *                     ColorGrading from this View. Doing so will revert to the use of the
     *                     default color grading transforms.
     *                     The View doesn't take ownership of the ColorGrading pointer (which
     *                     acts as a reference).
     */
    public void setColorGrading(@Nullable ColorGrading colorGrading) {
        mColorGrading = colorGrading;
        nSetColorGrading(getNativeObject(), colorGrading != null ? colorGrading.getNativeObject() : 0);
    }

    /**
     * Returns the color grading transforms currently associated to this view.
     *
     * @return A pointer to the ColorGrading associated to this View.
     */
    @Nullable
    public ColorGrading getColorGrading() {
        return mColorGrading;
    }

    /**
     * Sets ambient occlusion options.
     *
     * @param options Options for ambient occlusion.
     */
    public void setAmbientOcclusionOptions(@NonNull AmbientOcclusionOptions options) {
        mAmbientOcclusionOptions = options;
        nSetAmbientOcclusionOptions(getNativeObject(), options.aoType.toFilamentNative(), options.radius, options.power, options.bias, options.resolution, options.intensity, options.bilateralThreshold, options.quality.toFilamentNative(), options.lowPassFilter.toFilamentNative(), options.upsampling.toFilamentNative(), options.enabled, options.bentNormals, options.minHorizonAngleRad, options.ssctLightConeRad, options.ssctShadowDistance, options.ssctContactDistanceMax, options.ssctIntensity, options.ssctLightDirection[0], options.ssctLightDirection[1], options.ssctLightDirection[2], options.ssctDepthBias, options.ssctDepthSlopeBias, options.ssctSampleCount, options.ssctRayCount, options.ssctEnabled, options.gtaoSampleSliceCount, options.gtaoSampleStepsPerSlice, options.gtaoThicknessHeuristic, options.gtaoUseVisibilityBitmasks, options.gtaoConstThickness, options.gtaoLinearThickness);
    }

    /**
     * Gets the ambient occlusion options.
     *
     * @return ambient occlusion options currently set.
     */
    @NonNull
    public AmbientOcclusionOptions getAmbientOcclusionOptions() {
        if (mAmbientOcclusionOptions == null) {
            mAmbientOcclusionOptions = new AmbientOcclusionOptions();
        }
        return mAmbientOcclusionOptions;
    }

    /**
     * Enables or disables bloom in the post-processing stage.
     *
     * <p>Disabled by default.</p>
     *
     * @param options options. Values may be silently clamped to valid ranges.
     */
    public void setBloomOptions(@NonNull BloomOptions options) {
        mBloomOptions = options;
        nSetBloomOptions(getNativeObject(), options.dirt != null ? options.dirt.getNativeObject() : 0, options.dirtStrength, options.strength, options.resolution, options.levels, options.blendMode.toFilamentNative(), options.threshold, options.enabled, options.highlight, options.quality.toFilamentNative(), options.lensFlare, options.starburst, options.chromaticAberration, options.ghostCount, options.ghostSpacing, options.ghostThreshold, options.haloThickness, options.haloRadius, options.haloThreshold);
    }

    /**
     * Queries the bloom options.
     *
     * @return the current bloom options for this view.
     */
    @NonNull
    public BloomOptions getBloomOptions() {
        if (mBloomOptions == null) {
            mBloomOptions = new BloomOptions();
        }
        return mBloomOptions;
    }

    /**
     * Enables or disables fog.
     *
     * <p>Disabled by default.</p>
     *
     * @param options options
     */
    public void setFogOptions(@NonNull FogOptions options) {
        mFogOptions = options;
        nSetFogOptions(getNativeObject(), options.distance, options.cutOffDistance, options.maximumOpacity, options.height, options.heightFalloff, options.color[0], options.color[1], options.color[2], options.density, options.inScatteringStart, options.inScatteringSize, options.fogColorFromIbl, options.skyColor != null ? options.skyColor.getNativeObject() : 0, options.enabled);
    }

    /**
     * Queries the fog options.
     *
     * @return the current fog options for this view.
     */
    @NonNull
    public FogOptions getFogOptions() {
        if (mFogOptions == null) {
            mFogOptions = new FogOptions();
        }
        return mFogOptions;
    }

    /**
     * Enables or disables Depth of Field.
     *
     * <p>Disabled by default.</p>
     *
     * @param options options
     */
    public void setDepthOfFieldOptions(@NonNull DepthOfFieldOptions options) {
        mDepthOfFieldOptions = options;
        nSetDepthOfFieldOptions(getNativeObject(), options.cocScale, options.cocAspectRatio, options.maxApertureDiameter, options.enabled, options.filter.toFilamentNative(), options.nativeResolution, options.foregroundRingCount, options.backgroundRingCount, options.fastGatherRingCount, options.maxForegroundCOC, options.maxBackgroundCOC);
    }

    /**
     * Queries the depth of field options.
     *
     * @return the current depth of field options for this view.
     */
    @NonNull
    public DepthOfFieldOptions getDepthOfFieldOptions() {
        if (mDepthOfFieldOptions == null) {
            mDepthOfFieldOptions = new DepthOfFieldOptions();
        }
        return mDepthOfFieldOptions;
    }

    /**
     * Enables or disables the vignetted effect in the post-processing stage.
     *
     * <p>Disabled by default.</p>
     *
     * @param options options
     */
    public void setVignetteOptions(@NonNull VignetteOptions options) {
        mVignetteOptions = options;
        nSetVignetteOptions(getNativeObject(), options.midPoint, options.roundness, options.feather, options.color[0], options.color[1], options.color[2], options.color[3], options.enabled);
    }

    /**
     * Queries the vignette options.
     *
     * @return the current vignette options for this view.
     */
    @NonNull
    public VignetteOptions getVignetteOptions() {
        if (mVignetteOptions == null) {
            mVignetteOptions = new VignetteOptions();
        }
        return mVignetteOptions;
    }

    /**
     * Enables or disables dithering in the post-processing stage.
     *
     * <p>Enabled by default.</p>
     *
     * @param dithering dithering type
     */
    public void setDithering(@NonNull Dithering dithering) {
        nSetDithering(getNativeObject(), dithering.toFilamentNative());
    }

    /**
     * Queries whether dithering is enabled during the post-processing stage.
     *
     * @return the current dithering type for this view.
     */
    public Dithering getDithering() {
        return EnumCache.sDitheringValues[nGetDithering(getNativeObject())];
    }

    /**
     * Sets the dynamic resolution options for this view.
     *
     * <p>Dynamic resolution options
     * controls whether dynamic resolution is enabled, and if it is, how it behaves.</p>
     *
     * @param options The dynamic resolution options to use on this view
     */
    public void setDynamicResolutionOptions(@NonNull DynamicResolutionOptions options) {
        mDynamicResolutionOptions = options;
        nSetDynamicResolutionOptions(getNativeObject(), options.minScale, options.maxScale, options.sharpness, options.enabled, options.homogeneousScaling, options.quality.toFilamentNative());
    }

    /**
     * Returns the dynamic resolution options associated with this view.
     *
     * @return value set by setDynamicResolutionOptions().
     */
    @NonNull
    public DynamicResolutionOptions getDynamicResolutionOptions() {
        if (mDynamicResolutionOptions == null) {
            mDynamicResolutionOptions = new DynamicResolutionOptions();
        }
        return mDynamicResolutionOptions;
    }

    /**
     * Returns the last dynamic resolution scale factor used by this view.
     *
     * <p>This value is updated
     * when Renderer::render(View*) is called</p>
     *
     * @return a float2 where x is the horizontal and y the vertical scale factor.
     *
     * @see Renderer#render
     */
    @NonNull @Size(min = 2)
    public float[] getLastDynamicResolutionScale(@Nullable @Size(min = 2) float[] out) {
        out = Asserts.assertFloat2(out);
        nGetLastDynamicResolutionScale(getNativeObject(), out);
        return out;
    }

    /**
     * Sets the rendering quality for this view.
     *
     * <p>Refer to RenderQuality for more
     * information about the different settings available.</p>
     *
     * @param renderQuality The render quality to use on this view
     */
    public void setRenderQuality(@NonNull RenderQuality renderQuality) {
        mRenderQuality = renderQuality;
        nSetRenderQuality(getNativeObject(), renderQuality.hdrColorBuffer.toFilamentNative());
    }

    /**
     * Returns the render quality used by this view.
     *
     * @return value set by setRenderQuality().
     */
    @NonNull
    public RenderQuality getRenderQuality() {
        if (mRenderQuality == null) {
            mRenderQuality = new RenderQuality();
        }
        return mRenderQuality;
    }

    /**
     * Sets options relative to dynamic lighting for this view.
     *
     * @param zLightNear Distance from the camera where the lights are expected to shine.
     *                   This parameter can affect performance and is useful because depending
     *                   on the scene, lights that shine close to the camera may not be
     *                   visible -- in this case, using a larger value can improve performance.
     *                   e.g. when standing and looking straight, several meters of the ground
     *                   isn't visible and if lights are expected to shine there, there is no
     *                   point using a short zLightNear. This value is clamped between
     *                   the camera near and far plane. (Default 5m).
     * @param zLightFar <p>Distance from the camera after which lights are not expected to be visible.
     *                  Similarly to zLightNear, setting this value properly can improve
     *                  performance.  This value is clamped between the camera near and far plane.
     *                  (Default 100m).</p>
     *
     * <p>Together zLightNear and zLightFar must be chosen so that the visible influence of lights
     * is spread between these two values.</p>
     */
    public void setDynamicLightingOptions(float zLightNear, float zLightFar) {
        nSetDynamicLightingOptions(getNativeObject(), zLightNear, zLightFar);
    }

    /**
     * Sets the grid size for grid-based world origin snapping.
     *
     * <p>The world origin used for rendering will snap to a grid of this size.
     * This avoids recomputing all transforms every frame when the camera moves within a grid cell.</p>
     *
     * <p>Hysteresis is applied automatically to avoid rapid snapping near edges.</p>
     *
     * @param size The size of the grid cell in world units. If set to 0 or negative,
     *             the grid size is automatically calculated based on the camera frustum.
     */
    public void setGridSize(double size) {
        nSetGridSize(getNativeObject(), size);
    }

    /**
     * Returns the grid size used for grid-based world origin snapping.
     *
     * @return The grid size in world units. A value of 0 or negative means automatic calculation is enabled.
     */
    public double getGridSize() {
        return nGetGridSize(getNativeObject());
    }

    /**
     * Returns the effective grid size used for grid-based world origin snapping.
     *
     * <p>If grid size was set to 0 or negative, this returns the automatically calculated size.</p>
     *
     * @return The effective grid size in world units.
     */
    public double getEffectiveGridSize() {
        return nGetEffectiveGridSize(getNativeObject());
    }

    public void setShadowType(@NonNull ShadowType shadow) {
        nSetShadowType(getNativeObject(), shadow.toFilamentNative());
    }

    /**
     * Returns the shadow mapping technique used by this View.
     *
     * @return value set by setShadowType().
     */
    public ShadowType getShadowType() {
        return EnumCache.sShadowTypeValues[nGetShadowType(getNativeObject())];
    }

    /**
     * Sets VSM shadowing options that apply across the entire View.
     *
     * <p>Additional light-specific VSM options can be set with LightManager::setShadowOptions.</p>
     *
     * <p>Only applicable when shadow type is set to ShadowType::VSM.</p>
     *
     * <p>This API is still experimental and subject to change.</p>
     *
     * @param options Options for shadowing.
     *
     * @see #setShadowType
     */
    public void setVsmShadowOptions(@NonNull VsmShadowOptions options) {
        mVsmShadowOptions = options;
        nSetVsmShadowOptions(getNativeObject(), options.anisotropy, options.mipmapping, options.msaaSamples, options.highPrecision, options.minVarianceScale, options.lightBleedReduction);
    }

    /**
     * Returns the VSM shadowing options associated with this View.
     *
     * @return value set by setVsmShadowOptions().
     */
    @NonNull
    public VsmShadowOptions getVsmShadowOptions() {
        if (mVsmShadowOptions == null) {
            mVsmShadowOptions = new VsmShadowOptions();
        }
        return mVsmShadowOptions;
    }

    /**
     * Sets soft shadowing options that apply across the entire View.
     *
     * <p>Additional light-specific soft shadow parameters can be set with LightManager::setShadowOptions.</p>
     *
     * <p>Only applicable when shadow type is set to ShadowType::PCSS.</p>
     *
     * <p>This API is still experimental and subject to change.</p>
     *
     * @param options Options for shadowing.
     *
     * @see #setShadowType
     */
    public void setSoftShadowOptions(@NonNull SoftShadowOptions options) {
        mSoftShadowOptions = options;
        nSetSoftShadowOptions(getNativeObject(), options.penumbraScale, options.penumbraRatioScale, options.maxPenumbraRatio, options.maxSearchRadius);
    }

    /**
     * Returns the soft shadowing options associated with this View.
     *
     * @return value set by setSoftShadowOptions().
     */
    @NonNull
    public SoftShadowOptions getSoftShadowOptions() {
        if (mSoftShadowOptions == null) {
            mSoftShadowOptions = new SoftShadowOptions();
        }
        return mSoftShadowOptions;
    }

    /**
     * Enables or disables post-processing. Enabled by default.
     *
     * <p>Post-processing includes:</p>
     *
     * <ul>
     *   <li>Depth-of-field</li>
     *   <li>Bloom</li>
     *   <li>Vignetting</li>
     *   <li>Temporal Anti-aliasing (TAA)</li>
     *   <li>Color grading & gamma encoding</li>
     *   <li>Dithering</li>
     *   <li>FXAA</li>
     *   <li>Dynamic scaling
     * Disabling post-processing forgoes color correctness as well as some antialiasing techniques
     * and should only be used for debugging, UI overlays or when using custom render targets
     * (see RenderTarget).</li>
     * </ul>
     *
     * @param enabled true enables post-processing, false disables it.
     *
     * @see #setBloomOptions
     * @see #setColorGrading
     * @see #setAntiAliasing
     * @see #setDithering
     * @see #setSampleCount
     */
    public void setPostProcessingEnabled(boolean enabled) {
        nSetPostProcessingEnabled(getNativeObject(), enabled);
    }

    /**
     * Returns true if post-processing is enabled.
     *
     * <p>See setPostProcessingEnabled() for more info.</p>
     */
    public boolean isPostProcessingEnabled() {
        return nIsPostProcessingEnabled(getNativeObject());
    }

    /**
     * Inverts the winding order of front faces.
     *
     * <p>By default, front faces use a counter-clockwise
     * winding order. When the winding order is inverted, front faces are faces with a clockwise
     * winding order.</p>
     *
     * <p>Changing the winding order will directly affect the culling mode in materials
     * (see Material::getCullingMode()).</p>
     *
     * <p>Inverting the winding order of front faces is useful when rendering mirrored reflections
     * (water, mirror surfaces, front camera in AR, etc.).</p>
     *
     * @param inverted True to invert front faces, false otherwise.
     */
    public void setFrontFaceWindingInverted(boolean inverted) {
        nSetFrontFaceWindingInverted(getNativeObject(), inverted);
    }

    /**
     * Returns true if the winding order of front faces is inverted.
     *
     * <p>See setFrontFaceWindingInverted() for more information.</p>
     */
    public boolean isFrontFaceWindingInverted() {
        return nIsFrontFaceWindingInverted(getNativeObject());
    }

    /**
     * Enables or disables transparent picking.
     *
     * <p>Disabled by default.</p>
     *
     * <p>When transparent picking is enabled, View::pick() will pick from both
     * transparent and opaque renderables. When disabled, View::pick() will only
     * pick from opaque renderables.</p>
     *
     * <p>Transparent picking will create an extra pass for rendering depth
     *       from both transparent and opaque renderables.</p>
     *
     * @param enabled true enables transparent picking, false disables it.
     */
    public void setTransparentPickingEnabled(boolean enabled) {
        nSetTransparentPickingEnabled(getNativeObject(), enabled);
    }

    /**
     * Returns true if transparent picking is enabled.
     *
     * <p>See setTransparentPickingEnabled() for more information.</p>
     */
    public boolean isTransparentPickingEnabled() {
        return nIsTransparentPickingEnabled(getNativeObject());
    }

    /**
     * Enables use of the stencil buffer.
     *
     * <p>The stencil buffer is an 8-bit, per-fragment unsigned integer stored alongside the depth
     * buffer. The stencil buffer is cleared at the beginning of a frame and discarded after the
     * color pass.</p>
     *
     * <p>Each fragment's stencil value is set during rasterization by specifying stencil operations on
     * a Material. The stencil buffer can be used as a mask for later rendering by setting a
     * Material's stencil comparison function and reference value. Fragments that don't pass the
     * stencil test are then discarded.</p>
     *
     * <p>If post-processing is disabled, then the SwapChain must have the CONFIG_HAS_STENCIL_BUFFER
     * flag set in order to use the stencil buffer.</p>
     *
     * <p>A renderable's priority (see RenderableManager::setPriority) is useful to control the order
     * in which primitives are drawn.</p>
     *
     * @param enabled True to enable the stencil buffer, false disables it (default)
     */
    public void setStencilBufferEnabled(boolean enabled) {
        nSetStencilBufferEnabled(getNativeObject(), enabled);
    }

    /**
     * Returns true if the stencil buffer is enabled.
     *
     * <p>See setStencilBufferEnabled() for more information.</p>
     */
    public boolean isStencilBufferEnabled() {
        return nIsStencilBufferEnabled(getNativeObject());
    }

    /**
     * Sets the stereoscopic rendering options for this view.
     *
     * <p>Currently, only one type of stereoscopic rendering is supported: side-by-side.
     * Side-by-side stereo rendering splits the viewport into two halves: a left and right half.
     * Eye 0 will render to the left half, while Eye 1 will render into the right half.</p>
     *
     * <p>Currently, the following features are not supported with stereoscopic rendering:</p>
     *
     * <ul>
     *   <li>post-processing</li>
     *   <li>shadowing</li>
     *   <li>punctual lights
     * Stereo rendering depends on device and platform support. To check if stereo rendering is
     * supported, use Engine::isStereoSupported(). If stereo rendering is not supported, then the
     * stereoscopic options have no effect.</li>
     * </ul>
     *
     * @param options The stereoscopic options to use on this view
     */
    public void setStereoscopicOptions(@NonNull StereoscopicOptions options) {
        mStereoscopicOptions = options;
        nSetStereoscopicOptions(getNativeObject(), options.enabled);
    }

    /**
     * Returns the stereoscopic options associated with this View.
     *
     * @return value set by setStereoscopicOptions().
     */
    @NonNull
    public StereoscopicOptions getStereoscopicOptions() {
        if (mStereoscopicOptions == null) {
            mStereoscopicOptions = new StereoscopicOptions();
        }
        return mStereoscopicOptions;
    }

    /** debugging: allows to entirely disable frustum culling. (culling enabled by default). */
    public void setFrustumCullingEnabled(boolean culling) {
        nSetFrustumCullingEnabled(getNativeObject(), culling);
    }

    /** debugging: returns whether frustum culling is enabled. */
    public boolean isFrustumCullingEnabled() {
        return nIsFrustumCullingEnabled(getNativeObject());
    }

    /**
     * debugging: sets the Camera used for rendering.
     *
     * <p>It may be different from the culling camera.</p>
     */
    public void setDebugCamera(@Nullable Camera camera) {
        nSetDebugCamera(getNativeObject(), camera != null ? camera.getNativeObject() : 0);
    }

    /**
     * Set the value of material global variables.
     *
     * <p>There are up-to four such variable each of
     * type float4. These variables can be read in a user Material with
     * {@code getMaterialGlobal{0|1|2|3}()}. All variable start with a default value of { 0, 0, 0, 1 }</p>
     *
     * @param index index of the variable to set between 0 and 3.
     * @param valuex (x component) new value for the variable.
     * @param valuey (y component) new value for the variable.
     * @param valuez (z component) new value for the variable.
     * @param valuew (w component) new value for the variable.
     *
     * @see #getMaterialGlobal
     */
    public void setMaterialGlobal(@IntRange(from = 0) int index, float valuex, float valuey, float valuez, float valuew) {
        nSetMaterialGlobal(getNativeObject(), index, valuex, valuey, valuez, valuew);
    }

    /**
     * Set the value of material global variables.
     *
     * <p>There are up-to four such variable each of
     * type float4. These variables can be read in a user Material with
     * {@code getMaterialGlobal{0|1|2|3}()}. All variable start with a default value of { 0, 0, 0, 1 }</p>
     *
     * @param index index of the variable to set between 0 and 3.
     * @param value new value for the variable.
     *
     * @see #getMaterialGlobal
     */
    public void setMaterialGlobal(@IntRange(from = 0) int index, @NonNull @Size(min = 4) float[] value) {
        setMaterialGlobal(index, value[0], value[1], value[2], value[3]);
    }

    /**
     * Get the value of the material global variables.
     *
     * <p>All variable start with a default value of { 0, 0, 0, 1 }</p>
     *
     * @param index index of the variable to set between 0 and 3.
     *
     * @return current value of the variable.
     *
     * @see #setMaterialGlobal
     */
    @NonNull @Size(min = 4)
    public float[] getMaterialGlobal(@IntRange(from = 0) int index, @Nullable @Size(min = 4) float[] out) {
        out = Asserts.assertFloat4(out);
        nGetMaterialGlobal(getNativeObject(), index, out);
        return out;
    }

    /**
     * Get an Entity representing the large scale fog object.
     *
     * <p>This entity is always inherited by the View's Scene.</p>
     *
     * <p>It is for example possible to create a TransformManager component with this
     * Entity and apply a transformation globally on the fog.</p>
     *
     * @return an Entity representing the large scale fog object.
     */
    @Entity
    public int getFogEntity() {
        return nGetFogEntity(getNativeObject());
    }

    /**
     * Returns the most recent number of visible renderables for the current Scene as calculated the last time Renderer::render() was called with this View and Scene.
     *
     * <p>Returns -1 if the cache is invalid (e.g. before the first render call, or if the scene
     * was detached).</p>
     *
     * @return the number of visible renderables, or -1 if no value is available.
     */
    public int getVisibleRenderableCount() {
        return nGetVisibleRenderableCount(getNativeObject());
    }

    /**
     * When certain temporal features are used (e.g.: TAA or Screen-space reflections), the view keeps a history of previous frame renders associated with the Renderer the view was last used with.
     *
     * <p>When switching Renderer, it may be necessary to clear that history by calling
     * this method. Similarly, if the whole content of the screen change, like when a cut-scene
     * starts, clearing the history might be needed to avoid artifacts due to the previous frame
     * being very different.</p>
     */
    public void clearFrameHistory(@NonNull Engine engine) {
        nClearFrameHistory(getNativeObject(), engine.getNativeObject());
    }

    /**
     * Activates or deactivates ambient occlusion.
     *
     * @param ambientOcclusion Type of ambient occlusion to use.
     *
     * @deprecated use setAmbientOcclusionOptions() instead
     *
     * @see #setAmbientOcclusionOptions
     */
    public void setAmbientOcclusion(@NonNull AmbientOcclusion ambientOcclusion) {
        nSetAmbientOcclusion(getNativeObject(), ambientOcclusion.toFilamentNative());
    }

    /**
     * Queries the type of ambient occlusion active for this View.
     *
     * @return ambient occlusion type.
     *
     * @deprecated use getAmbientOcclusionOptions() instead
     *
     * @see #getAmbientOcclusionOptions
     */
    public AmbientOcclusion getAmbientOcclusion() {
        return EnumCache.sAmbientOcclusionValues[nGetAmbientOcclusion(getNativeObject())];
    }

    public long getNativeObject() {
        if (mNativeObject == 0) {
            throw new IllegalStateException("Calling method on destroyed View");
        }
        return mNativeObject;
    }

    void clearNativeObject() {
        mNativeObject = 0;
    }
    /**
     * @deprecated Use {@link #setColorGrading(ColorGrading)}
     */
    @Deprecated
    public void setToneMapping(@NonNull ToneMapping type) {
    }

    /**
     * @deprecated Use {@link #getColorGrading()}. This always returns {@link ToneMapping#ACES}
     */
    @Deprecated
    @NonNull
    public ToneMapping getToneMapping() {
        return ToneMapping.ACES;
    }

    /**
     * An interface to implement a custom class to receive results of picking queries.
     */
    public interface OnPickCallback {
        /**
         * onPick() is called by the specified Handler in {@link View#pick} when the picking query
         * result is available.
         * @param result An instance of {@link PickingQueryResult}.
         */
        void onPick(@NonNull PickingQueryResult result);
    }

    /**
     * Creates a picking query. Multiple queries can be created (e.g.: multi-touch).
     * Picking queries are all executed when {@link Renderer#render} is called on this View.
     * The provided callback is guaranteed to be called at some point in the future.
     *
     * <p>Typically it takes a couple frames to receive the result of a picking query.</p>
     *
     * @param x        Horizontal coordinate to query in the viewport with origin on the left.
     * @param y        Vertical coordinate to query on the viewport with origin at the bottom.
     * @param handler  An {@link java.util.concurrent.Executor Executor}.
     *                 On Android this can also be a {@link android.os.Handler Handler}.
     * @param callback User callback executed by <code>handler</code> when the picking query
     *                 result is available.
     */
    public void pick(int x, int y,
            @Nullable Object handler, @Nullable OnPickCallback callback) {
        InternalOnPickCallback internalCallback = new InternalOnPickCallback(callback);
        nPick(getNativeObject(), x, y, handler, internalCallback);
    }

    @UsedByNative("View.cpp")
    private static class InternalOnPickCallback implements Runnable {
        private final OnPickCallback mUserCallback;
        private final PickingQueryResult mPickingQueryResult = new PickingQueryResult();

        @UsedByNative("View.cpp")
        @Entity
        int mRenderable;

        @UsedByNative("View.cpp")
        float mDepth;

        @UsedByNative("View.cpp")
        float mFragCoordsX;
        @UsedByNative("View.cpp")
        float mFragCoordsY;
        @UsedByNative("View.cpp")
        float mFragCoordsZ;

        public InternalOnPickCallback(OnPickCallback mUserCallback) {
            this.mUserCallback = mUserCallback;
        }

        @Override
        public void run() {
            mPickingQueryResult.renderable = mRenderable;
            mPickingQueryResult.depth = mDepth;
            mPickingQueryResult.fragCoords[0] = mFragCoordsX;
            mPickingQueryResult.fragCoords[1] = mFragCoordsY;
            mPickingQueryResult.fragCoords[2] = mFragCoordsZ;
            if (mUserCallback != null) {
                mUserCallback.onPick(mPickingQueryResult);
            }
        }
    }

    /**
     * Dynamic resolution can be used to either reach a desired target frame rate by lowering the resolution of a View, or to increase the quality when the rendering is faster than the target frame rate.
     *
     * <p>This structure can be used to specify the minimum scale factor used when
     * lowering the resolution of a View, and the maximum scale factor used when
     * increasing the resolution for higher quality rendering. The scale factors
     * can be controlled on each X and Y axis independently. By default, all scale
     * factors are set to 1.0.</p>
     *
     * <ul>
     * <li>enabled:   enable or disables dynamic resolution on a View</li>
     *
     * <li>homogeneousScaling: by default the system scales the major axis first. Set this to true
     *                     to force homogeneous scaling.</li>
     *
     * <li>minScale:  the minimum scale in X and Y this View should use</li>
     *
     * <li>maxScale:  the maximum scale in X and Y this View should use</li>
     *
     * <li>quality:   upscaling quality.
     *            LOW: 1 bilinear tap, Medium: 4 bilinear taps, High: 9 bilinear taps (tent)</li>
     * </ul>
     *
     * <p>Note:
     * Dynamic resolution is only supported on platforms where the time to render
     * a frame can be measured accurately. On platforms where this is not supported,
     * Dynamic Resolution can't be enabled unless <code>minScale == maxScale</code>.</p>
     *
     * @see Renderer.FrameRateOptions
     */
    public static class DynamicResolutionOptions {
        /** minimum scale factors in x and y */
        public float minScale = 0.5f;
        /** maximum scale factors in x and y */
        public float maxScale = 1.0f;
        /** sharpness when QualityLevel::MEDIUM or higher is used [0 (disabled), 1 (sharpest)] */
        public float sharpness = 0.9f;
        /** enable or disable dynamic resolution */
        public boolean enabled = false;
        /** set to true to force homogeneous scaling */
        public boolean homogeneousScaling = false;
        /**
         * Upscaling quality <ul> <li>LOW:    bilinear filtered blit.
         *
         * <p>Fastest, poor quality</li>
         * <li>MEDIUM: Qualcomm Snapdragon Game Super Resolution (SGSR) 1.0</li>
         * <li>HIGH:   AMD FidelityFX FSR1 w/ mobile optimizations</li>
         * <li>ULTRA:  AMD FidelityFX FSR1</li>
         * </ul>
         *      FSR1 and SGSR require a well anti-aliased (MSAA or TAA), noise free scene.
         *      Avoid FXAA and dithering.</p>
         *
         * <p>The default upscaling quality is set to LOW.</p>
         *
         * <p>caveat: currently, <code>quality</code> is always set to LOW if the View is TRANSLUCENT.</p>
         */
        @NonNull
        public QualityLevel quality = QualityLevel.LOW;
    }

    /**
     * Options to control the bloom effect
     *
     * <ul>
     * <li>enabled:     Enable or disable the bloom post-processing effect. Disabled by default.</li>
     *
     * <li>levels:      Number of successive blurs to achieve the blur effect, the minimum is 3 and the
     *              maximum is 12. This value together with resolution influences the spread of the
     *              blur effect. This value can be silently reduced to accommodate the original
     *              image size.</li>
     *
     * <li>resolution:  Resolution of bloom's minor axis. The minimum value is 2^levels and the
     *              the maximum is lower of the original resolution and 4096. This parameter is
     *              silently clamped to the minimum and maximum.
     *              It is highly recommended that this value be smaller than the target resolution
     *              after dynamic resolution is applied (horizontally and vertically).</li>
     *
     * <li>strength:    how much of the bloom is added to the original image. Between 0 and 1.</li>
     *
     * <li>blendMode:   Whether the bloom effect is purely additive (false) or mixed with the original
     *              image (true).</li>
     *
     * <li>threshold:   When enabled, a threshold at 1.0 is applied on the source image, this is
     *              useful for artistic reasons and is usually needed when a dirt texture is used.</li>
     *
     * <li>dirt:        A dirt/scratch/smudges texture (that can be RGB), which gets added to the
     *              bloom effect. Smudges are visible where bloom occurs. Threshold must be
     *              enabled for the dirt effect to work properly.</li>
     *
     * <li>dirtStrength: Strength of the dirt texture.</li>
     * </ul>
     */
    public static class BloomOptions {
        public enum BlendMode {
            /** Bloom is modulated by the strength parameter and added to the scene */
            ADD,
            /** Bloom is interpolated with the scene using the strength parameter */
            INTERPOLATE;

            public int toFilamentNative() { return ordinal(); }
        }

        /** user provided dirt texture */
        @Nullable
        public Texture dirt = null;
        /** strength of the dirt texture */
        public float dirtStrength = 0.2f;
        /** bloom's strength between 0.0 and 1.0 */
        public float strength = 0.10f;
        /** resolution of vertical axis (2^levels to 2048) */
        public int resolution = 384;
        /** number of blur levels (1 to 11) */
        public int levels = 6;
        /** how the bloom effect is applied */
        @NonNull
        public BloomOptions.BlendMode blendMode = BloomOptions.BlendMode.ADD;
        /** whether to threshold the source */
        public boolean threshold = true;
        /** enable or disable bloom */
        public boolean enabled = false;
        /** limit highlights to this value before bloom [10, +inf] */
        public float highlight = 1000.0f;
        /**
         * Bloom quality level.
         *
         * <ul>
         * <li>LOW (default): use a more optimized down-sampling filter, however there can be artifacts
         *      with dynamic resolution, this can be alleviated by using the homogenous mode.</li>
         * <li>MEDIUM: Good balance between quality and performance.</li>
         * <li>HIGH: In this mode the bloom resolution is automatically increased to avoid artifacts.
         *      This mode can be significantly slower on mobile, especially at high resolution.
         *      This mode greatly improves the anamorphic bloom.</li>
         * </ul>
         */
        @NonNull
        public QualityLevel quality = QualityLevel.LOW;
        /** enable screen-space lens flare */
        public boolean lensFlare = false;
        /** enable starburst effect on lens flare */
        public boolean starburst = true;
        /** amount of chromatic aberration */
        public float chromaticAberration = 0.005f;
        /** number of flare "ghosts" */
        public int ghostCount = 4;
        /** spacing of the ghost in screen units [0, 1[ */
        public float ghostSpacing = 0.6f;
        /** hdr threshold for the ghosts */
        public float ghostThreshold = 10.0f;
        /** thickness of halo in vertical screen units, 0 to disable */
        public float haloThickness = 0.1f;
        /** radius of halo in vertical screen units [0, 0.5] */
        public float haloRadius = 0.4f;
        /** hdr threshold for the halo */
        public float haloThreshold = 10.0f;
    }

    /**
     * Options to control large-scale fog in the scene.
     *
     * <p>Materials can enable the <code>linearFog</code> property,
     * which uses a simplified, linear equation for fog calculation; in this mode, the heightFalloff
     * is ignored as well as the mipmap selection in IBL or skyColor mode.</p>
     */
    public static class FogOptions {
        /** Distance in world units [m] from the camera to where the fog starts ( >= 0.0 ) */
        public float distance = 0.0f;
        /**
         * Distance in world units [m] after which the fog calculation is disabled.
         *
         * <p>This can be used to exclude the skybox, which is desirable if it already contains clouds or
         * fog. The default value is +infinity which applies the fog to everything.</p>
         *
         * <p>Note: The SkyBox is typically at a distance of 1e19 in world space (depending on the near
         * plane distance and projection used though).</p>
         */
        public float cutOffDistance = Float.POSITIVE_INFINITY;
        /**
         * fog's maximum opacity between 0 and 1.
         *
         * <p>Ignored in <code>linearFog</code> mode.</p>
         */
        public float maximumOpacity = 1.0f;
        /**
         * Fog's floor in world units [m].
         *
         * <p>This sets the "sea level".</p>
         */
        public float height = 0.0f;
        /**
         * How fast the fog dissipates with the altitude. heightFalloff has a unit of [1/m].
         *
         * <p>It can be expressed as 1/H, where H is the altitude change in world units [m] that causes a
         * factor 2.78 (e) change in fog density.</p>
         *
         * <p>A falloff of 0 means the fog density is constant everywhere and may result is slightly
         * faster computations.</p>
         *
         * <p>In <code>linearFog</code> mode, only use to compute the slope of the linear equation. Completely
         * ignored if set to 0.</p>
         */
        public float heightFalloff = 1.0f;
        /**
         * Fog's color is used for ambient light in-scattering, a good value is to use the average of the ambient light, possibly tinted towards blue for outdoors environments.
         *
         * <p>Color component's values should be between 0 and 1, values
         * above one are allowed but could create a non energy-conservative fog (this is dependant
         * on the IBL's intensity as well).</p>
         *
         * <p>We assume that our fog has no absorption and therefore all the light it scatters out
         * becomes ambient light in-scattering and has lost all directionality, i.e.: scattering is
         * isotropic. This somewhat simulates Rayleigh scattering.</p>
         *
         * <p>This value is used as a tint instead, when fogColorFromIbl is enabled.</p>
         *
         * @see #fogColorFromIbl
         */
        @NonNull @Size(min = 3)
        public float[] color = {1.0f, 1.0f, 1.0f};
        /**
         * Extinction factor in [1/m] at an altitude 'height'.
         *
         * <p>The extinction factor controls how much
         * light is absorbed and out-scattered per unit of distance. Each unit of extinction reduces
         * the incoming light to 37% of its original value.</p>
         *
         * <p>Note: The extinction factor is related to the fog density, it's usually some constant K times
         * the density at sea level (more specifically at fog height). The constant K depends on
         * the composition of the fog/atmosphere.</p>
         *
         * <p>For historical reason this parameter is called <code>density</code>.</p>
         *
         * <p>In <code>linearFog</code> mode this is the slope of the linear equation if heightFalloff is set to 0.
         * Otherwise, heightFalloff affects the slope calculation such that it matches the slope of
         * the standard equation at the camera height.</p>
         */
        public float density = 0.1f;
        /**
         * Distance in world units [m] from the camera where the Sun in-scattering starts.
         *
         * <p>Ignored in <code>linearFog</code> mode.</p>
         */
        public float inScatteringStart = 0.0f;
        /**
         * Very inaccurately simulates the Sun's in-scattering.
         *
         * <p>That is, the light from the sun that
         * is scattered (by the fog) towards the camera.
         * Size of the Sun in-scattering (>0 to activate). Good values are >> 1 (e.g. ~10 - 100).
         * Smaller values result is a larger scattering size.
         * Ignored in <code>linearFog</code> mode.</p>
         */
        public float inScatteringSize = -1.0f;
        /**
         * The fog color will be sampled from the IBL in the view direction and tinted by <code>color</code>.
         *
         * <p>Depending on the scene this can produce very convincing results.</p>
         *
         * <p>This simulates a more anisotropic phase-function.</p>
         *
         * <p><code>fogColorFromIbl</code> is ignored when skyTexture is specified.</p>
         *
         * @see #skyColor
         */
        public boolean fogColorFromIbl = false;
        /**
         * skyTexture must be a mipmapped cubemap.
         *
         * <p>When provided, the fog color will be sampled from
         * this texture, higher resolution mip levels will be used for objects at the far clip plane,
         * and lower resolution mip levels for objects closer to the camera. The skyTexture should
         * typically be heavily blurred; a typical way to produce this texture is to blur the base
         * level with a strong gaussian filter or even an irradiance filter and then generate mip
         * levels as usual. How blurred the base level is somewhat of an artistic decision.</p>
         *
         * <p>This simulates a more anisotropic phase-function.</p>
         *
         * <p><code>fogColorFromIbl</code> is ignored when skyTexture is specified.</p>
         *
         * <p>In <code>linearFog</code> mode mipmap level 0 is always used.</p>
         *
         * @see Texture
         * @see #fogColorFromIbl
         */
        @Nullable
        public Texture skyColor = null;
        /** Enable or disable large-scale fog */
        public boolean enabled = false;
    }

    /**
     * Options to control Depth of Field (DoF) effect in the scene.
     *
     * <p>cocScale can be used to set the depth of field blur independently of the camera
     * aperture, e.g. for artistic reasons. This can be achieved by setting:
     *      cocScale = cameraAperture / desiredDoFAperture</p>
     *
     * @see Camera
     */
    public static class DepthOfFieldOptions {
        public enum Filter {
            NONE,
            UNUSED,
            MEDIAN;

            public int toFilamentNative() { return ordinal(); }
        }

        /** circle of confusion scale factor (amount of blur) */
        public float cocScale = 1.0f;
        /** width/height aspect ratio of the circle of confusion (simulate anamorphic lenses) */
        public float cocAspectRatio = 1.0f;
        /** maximum aperture diameter in meters (zero to disable rotation) */
        public float maxApertureDiameter = 0.01f;
        /** enable or disable depth of field effect */
        public boolean enabled = false;
        /** filter to use for filling gaps in the kernel */
        @NonNull
        public DepthOfFieldOptions.Filter filter = DepthOfFieldOptions.Filter.MEDIAN;
        /** perform DoF processing at native resolution */
        public boolean nativeResolution = false;
        /**
         * Number of of rings used by the gather kernels.
         *
         * <p>The number of rings affects quality
         * and performance. The actual number of sample per pixel is defined
         * as (ringCount * 2 - 1)^2. Here are a few commonly used values:
         * <ul>
         *       <li>3 rings :   25 ( 5x 5 grid)</li>
         *       <li>4 rings :   49 ( 7x 7 grid)</li>
         *       <li>5 rings :   81 ( 9x 9 grid)</li>
         *      <li>17 rings : 1089 (33x33 grid)</li>
         * </ul></p>
         *
         * <p>With a maximum circle-of-confusion of 32, it is never necessary to use more than 17 rings.</p>
         *
         * <p>Usually all three settings below are set to the same value, however, it is often
         * acceptable to use a lower ring count for the "fast tiles", which improves performance.
         * Fast tiles are regions of the screen where every pixels have a similar
         * circle-of-confusion radius.</p>
         *
         * <p>A value of 0 means default, which is 5 on desktop and 3 on mobile.</p>
         *
         * <p>number of kernel rings for foreground tiles</p>
         *
         * @see #backgroundRingCount
         * @see #fastGatherRingCount
         */
        public int foregroundRingCount = 0;
        /** number of kernel rings for background tiles */
        public int backgroundRingCount = 0;
        /** number of kernel rings for fast tiles */
        public int fastGatherRingCount = 0;
        /**
         * maximum circle-of-confusion in pixels for the foreground, must be in [0, 32] range.
         *
         * <p>A value of 0 means default, which is 32 on desktop and 24 on mobile.</p>
         */
        public int maxForegroundCOC = 0;
        /**
         * maximum circle-of-confusion in pixels for the background, must be in [0, 32] range.
         *
         * <p>A value of 0 means default, which is 32 on desktop and 24 on mobile.</p>
         */
        public int maxBackgroundCOC = 0;
    }

    /** Options to control the vignetting effect. */
    public static class VignetteOptions {
        /** high values restrict the vignette closer to the corners, between 0 and 1 */
        public float midPoint = 0.5f;
        /** controls the shape of the vignette, from a rounded rectangle (0.0), to an oval (0.5), to a circle (1.0) */
        public float roundness = 0.5f;
        /** softening amount of the vignette effect, between 0 and 1 */
        public float feather = 0.5f;
        /** color of the vignette effect, alpha is currently ignored */
        @NonNull @Size(min = 4)
        public float[] color = {0.0f, 0.0f, 0.0f, 1.0f};
        /** enables or disables the vignette effect */
        public boolean enabled = false;
    }

    /**
     * Structure used to set the precision of the color buffer and related quality settings.
     *
     * @see #setRenderQuality
     * @see #getRenderQuality
     */
    public static class RenderQuality {
        /**
         * Sets the quality of the HDR color buffer.
         *
         * <p>A quality of HIGH or ULTRA means using an RGB16F or RGBA16F color buffer. This means
         * colors in the LDR range (0..1) have a 10 bit precision. A quality of LOW or MEDIUM means
         * using an R11G11B10F opaque color buffer or an RGBA16F transparent color buffer. With
         * R11G11B10F colors in the LDR range have a precision of either 6 bits (red and green
         * channels) or 5 bits (blue channel).</p>
         */
        @NonNull
        public QualityLevel hdrColorBuffer = QualityLevel.HIGH;
    }

    /**
     * Options for screen space Ambient Occlusion (SSAO) and Screen Space Cone Tracing (SSCT)
     *
     * @see #setAmbientOcclusionOptions
     */
    public static class AmbientOcclusionOptions {
        public enum AmbientOcclusionType {
            /** use Scalable Ambient Occlusion */
            SAO,
            /** use Ground Truth-Based Ambient Occlusion */
            GTAO;

            public int toFilamentNative() { return ordinal(); }
        }

        /** Type of ambient occlusion algorithm. */
        @NonNull
        public AmbientOcclusionOptions.AmbientOcclusionType aoType = AmbientOcclusionOptions.AmbientOcclusionType.SAO;
        /** Ambient Occlusion radius in meters, between 0 and ~10. */
        public float radius = 0.3f;
        /**
         * Controls ambient occlusion's contrast.
         *
         * <p>Must be positive.</p>
         */
        public float power = 1.0f;
        /**
         * Self-occlusion bias in meters.
         *
         * <p>Use to avoid self-occlusion.
         * Between 0 and a few mm. No effect when aoType set to GTAO</p>
         */
        public float bias = 0.0005f;
        /**
         * How each dimension of the AO buffer is scaled.
         *
         * <p>Must be either 0.5 or 1.0.</p>
         */
        public float resolution = 0.5f;
        /** Strength of the Ambient Occlusion effect. */
        public float intensity = 1.0f;
        /** depth distance that constitute an edge for filtering */
        public float bilateralThreshold = 0.05f;
        /** affects # of samples used for AO and params for filtering */
        @NonNull
        public QualityLevel quality = QualityLevel.LOW;
        /**
         * affects AO smoothness.
         *
         * <p>Recommend setting to HIGH when aoType set to GTAO.</p>
         */
        @NonNull
        public QualityLevel lowPassFilter = QualityLevel.MEDIUM;
        /** affects AO buffer upsampling quality */
        @NonNull
        public QualityLevel upsampling = QualityLevel.LOW;
        /** enables or disables screen-space ambient occlusion */
        public boolean enabled = false;
        /** enables bent normals computation from AO, and specular AO */
        public boolean bentNormals = false;
        /**
         * min angle in radian to consider.
         *
         * <p>No effect when aoType set to GTAO.</p>
         */
        public float minHorizonAngleRad = 0.0f;
        /** full cone angle in radian, between 0 and pi/2 */
        public float ssctLightConeRad = 1.0f;
        /** how far shadows can be cast */
        public float ssctShadowDistance = 0.3f;
        /** max distance for contact */
        public float ssctContactDistanceMax = 1.0f;
        /** intensity */
        public float ssctIntensity = 0.8f;
        /** light direction */
        @NonNull @Size(min = 3)
        public float[] ssctLightDirection = {0f, -1f, 0f};
        /** depth bias in world units (mitigate self shadowing) */
        public float ssctDepthBias = 0.01f;
        /** depth slope bias (mitigate self shadowing) */
        public float ssctDepthSlopeBias = 0.01f;
        /** tracing sample count, between 1 and 255 */
        public int ssctSampleCount = 4;
        /** <h1>of rays to trace, between 1 and 255</h1> */
        public int ssctRayCount = 1;
        /** enables or disables SSCT */
        public boolean ssctEnabled = false;
        /**
         * <h1>of slices.</h1>
         *
         * <p>Higher value makes less noise.</p>
         */
        public int gtaoSampleSliceCount = 4;
        /**
         * <h1>of steps the radius is divided into for integration.</h1>
         *
         * <p>Higher value makes less bias.</p>
         */
        public int gtaoSampleStepsPerSlice = 3;
        /**
         * thickness heuristic, should be closed to 0.
         *
         * <p>No effect when useVisibilityBitmasks sets to true.</p>
         */
        public float gtaoThicknessHeuristic = 0.004f;
        /**
         * Enables or disables visibility bitmasks mode.
         *
         * <p>Notes that bent normal doesn't work under this mode.
         * Caution: Changing this option at runtime is very expensive as it may trigger a shader re-compilation.</p>
         */
        public boolean gtaoUseVisibilityBitmasks = false;
        /**
         * constant thickness value of objects on the screen in world space.
         *
         * <p>Only take effect when useVisibilityBitmasks is set to true.</p>
         */
        public float gtaoConstThickness = 0.5f;
        /**
         * Increase thickness with distance to maintain detail on distant surfaces.
         *
         * <p>Caution: Changing this option at runtime is very expensive as it may trigger a shader re-compilation.</p>
         */
        public boolean gtaoLinearThickness = false;
    }

    /**
     * Options for Temporal Anti-aliasing (TAA) Most TAA parameters are extremely costly to change, as they will trigger the TAA post-process shaders to be recompiled.
     *
     * <p>These options should be changed or set during initialization.
     * {@code filterWidth}, {@code feedback} and {@code jitterPattern}, however, can be changed at any time.</p>
     *
     * <p><code>feedback</code> of 0.1 effectively accumulates a maximum of 19 samples in steady state.
     * see "A Survey of Temporal Antialiasing Techniques" by Lei Yang and all for more information.</p>
     *
     * @see #setTemporalAntiAliasingOptions
     */
    public static class TemporalAntiAliasingOptions {
        public enum BoxType {
            /** use an AABB neighborhood */
            AABB,
            /** use both AABB and variance */
            AABB_VARIANCE;

            public int toFilamentNative() { return ordinal(); }
        }

        public enum BoxClipping {
            /** Accurate box clipping */
            ACCURATE,
            /** clamping */
            CLAMP,
            /** no rejections (use for debugging) */
            NONE;

            public int toFilamentNative() { return ordinal(); }
        }

        public enum JitterPattern {
            /** 4-samples, rotated grid sampling */
            RGSS_X4,
            /** 4-samples, uniform grid in helix sequence */
            UNIFORM_HELIX_X4,
            /** 8-samples of halton 2,3 */
            HALTON_23_X8,
            /** 16-samples of halton 2,3 */
            HALTON_23_X16,
            /** 32-samples of halton 2,3 */
            HALTON_23_X32;

            public int toFilamentNative() { return ordinal(); }
        }

        /** @deprecated has no effect. */
        @Deprecated
        public float filterWidth = 1.0f;
        /** history feedback, between 0 (maximum temporal AA) and 1 (no temporal AA). */
        public float feedback = 0.12f;
        /** texturing lod bias (typically -1 or -2) */
        public float lodBias = -1.0f;
        /** post-TAA sharpen, especially useful when upscaling is true. */
        public float sharpness = 0.0f;
        /** enables or disables temporal anti-aliasing */
        public boolean enabled = false;
        /**
         * Upscaling factor.
         *
         * <p>Disables Dynamic Resolution. [BETA]</p>
         */
        public float upscaling = 1.0f;
        /** whether to filter the history buffer */
        public boolean filterHistory = true;
        /** whether to apply the reconstruction filter to the input */
        public boolean filterInput = true;
        /** whether to use the YcoCg color-space for history rejection */
        public boolean useYCoCg = false;
        /** set to true for HDR content */
        public boolean hdr = true;
        /** type of color gamut box */
        @NonNull
        public TemporalAntiAliasingOptions.BoxType boxType = TemporalAntiAliasingOptions.BoxType.AABB;
        /** clipping algorithm */
        @NonNull
        public TemporalAntiAliasingOptions.BoxClipping boxClipping = TemporalAntiAliasingOptions.BoxClipping.ACCURATE;
        /** Jitter Pattern */
        @NonNull
        public TemporalAntiAliasingOptions.JitterPattern jitterPattern = TemporalAntiAliasingOptions.JitterPattern.HALTON_23_X16;
        /** High values increases ghosting artefact, lower values increases jittering, range [0.75, 1.25] */
        public float varianceGamma = 1.0f;
        /** adjust the feedback dynamically to reduce flickering */
        public boolean preventFlickering = false;
        /** whether to apply history reprojection (debug option) */
        public boolean historyReprojection = true;
    }

    /**
     * Options for Multi-Sample Anti-aliasing (MSAA)
     *
     * @see #setMultiSampleAntiAliasingOptions
     */
    public static class MultiSampleAntiAliasingOptions {
        /** enables or disables msaa */
        public boolean enabled = false;
        /**
         * sampleCount number of samples to use for multi-sampled anti-aliasing.<br>              0: treated as 1              1: no anti-aliasing              n: sample count.
         *
         * <p>Effective sample could be different depending on the
         *                 GPU capabilities.</p>
         */
        public int sampleCount = 4;
        /** custom resolve improves quality for HDR scenes, but may impact performance. */
        public boolean customResolve = false;
    }

    /**
     * View-level options for VSM Shadowing.
     *
     * <p><b>Warning:</b> This API is still experimental and subject to change.</p>
     *
     * @see #setVsmShadowOptions
     */
    public static class VsmShadowOptions {
        /**
         * Sets the number of anisotropic samples to use when sampling a VSM shadow map.
         *
         * <p>If greater
         * than 0, mipmaps will automatically be generated each frame for all lights.</p>
         *
         * <p>The number of anisotropic samples = 2 ^ vsmAnisotropy.</p>
         */
        public int anisotropy = 0;
        /** Whether to generate mipmaps for all VSM shadow maps. */
        public boolean mipmapping = false;
        /**
         * The number of MSAA samples to use when rendering VSM shadow maps.
         *
         * <p>Must be a power-of-two and greater than or equal to 1. A value of 1 effectively turns
         * off MSAA.
         * Higher values may not be available depending on the underlying hardware.</p>
         */
        public int msaaSamples = 1;
        /**
         * Whether to use a 32-bits or 16-bits texture format for VSM shadow maps.
         *
         * <p>32-bits
         * precision is rarely needed, but it does reduce light leaks as well as "fading"
         * of the shadows in some situations. Setting highPrecision to true for a single
         * shadow map will double the memory usage of all shadow maps.
         * This may not be supported on all mobile devices.</p>
         */
        public boolean highPrecision = false;
        /** @deprecated has no effect. */
        @Deprecated
        public float minVarianceScale = 0.5f;
        /** VSM light bleeding reduction amount, between 0 and 1. */
        public float lightBleedReduction = 0.15f;
    }

    /**
     * View-level options for PCSS Shadowing.
     *
     * <p><b>Warning:</b> This API is still experimental and subject to change.</p>
     *
     * @see #setSoftShadowOptions
     */
    public static class SoftShadowOptions {
        /**
         * Sets a global scale factor applied to the final penumbra size of all PCSS shadows.
         *
         * <p>This parameter acts as an artistic modifier, uniformly scaling the overall softness
         * of shadows across the entire scene without altering the physical angular size of
         * the light sources.</p>
         *
         * <p>The final scale applied to a shadow is calculated by modulating this global
         * value with the light's individual penumbraScale (global * local). This allows
         * art directors to shift the global mood (e.g., making all shadows 20% softer)
         * while preserving the relative contrast between different lights.</p>
         *
         * <p>The global penumbra scale multiplier. Default is 1.0 (physically based).</p>
         *
         * @see LightManager.ShadowOptions#penumbraScale
         */
        public float penumbraScale = 1.0f;
        /**
         * Sets a global scale factor applied to the PCSS geometric ratio before failsafe clamping.
         *
         * <p>This parameter controls the "contact shadow contrast" or the rate at which shadows
         * transition from sharp to soft. By scaling the geometric ratio, you can create
         * highly dramatic, cinematic shadows that blur rapidly as they move away from the
         * contact point, completely independently of the light's overall physical size.</p>
         *
         * <ul>
         *   <li>Values > 1.0 cause the shadow to accelerate toward its maximum softness faster.</li>
         *   <li>Values < 1.0 cause the shadow to stay sharper for a longer distance.
         * The final ratio scale applied is calculated by modulating this global value with
         * the light's individual penumbraRatioScale (global * local).
         * The global penumbra ratio scale multiplier. Default is 1.0.</li>
         * </ul>
         *
         * @see LightManager.ShadowOptions#penumbraRatioScale
         */
        public float penumbraRatioScale = 1.0f;
        /**
         * Sets the global default maximum geometric ratio applied to Percentage-Closer Soft Shadows (PCSS).
         *
         * <p>In PCSS, the physical width of a shadow's penumbra is determined by the ratio:
         * (distance_to_receiver - distance_to_blocker) / distance_to_blocker</p>
         *
         * <p>Standard shadow maps store a single depth layer (2.5D). When evaluating complex,
         * overlapping occluders (e.g., foliage, layered floating geometry), the shadow map
         * cannot resolve volumetric depth. This limitation can trick the blocker search into
         * returning an artificially close depth value, driving the denominator toward zero.
         * The resulting explosion in penumbra size causes unnatural, massive "ghost" shadows.</p>
         *
         * <p>maxPenumbraRatio applies a smooth, asymptotic squash to the geometric ratio, acting
         * as both a mathematical failsafe and an artistic control. It guarantees the penumbra
         * will gracefully stop expanding before it destroys the visual coherence of the scene.</p>
         *
         * <p>This global value acts as the baseline for all lights. Individual lights can explicitly
         * override this default via the LightManager API to handle specific geometric artifacts
         * without affecting the rest of the scene.</p>
         *
         * <ul>
         *   <li>A lower value (e.g., 2.0) creates generally sharper, highly stable
         * shadows that aggressively suppress 2.5D layered occlusion artifacts.</li>
         *   <li>A higher value (e.g., 5.0+) allows for physically accurate, widely
         * expanding soft shadows, but increases susceptibility to ghosting.</li>
         * </ul>
         *
         * @see LightManager.ShadowOptions#maxPenumbraRatio
         */
        public float maxPenumbraRatio = 10.0f;
        /**
         * Sets the global default maximum world-space radius used during the PCSS blocker search.
         *
         * <p>In PCSS, the shadow algorithm searches a region of the shadow map to find the
         * average depth of occluders. For lights with a large angular size (or objects
         * very far from the light), this search region can become massive.</p>
         *
         * <ul>
         *   <li>If the search region expands too much, it may inadvertently overlap distinct
         * foreground geometry (like a streetlight fixture) or climb vertical surfaces
         * (like a pole), causing the shadow to detach from the contact point and appear
         * to float.
         * maxSearchRadius limits the physical footprint of this search. This global value acts
         * as the baseline for all lights. Individual lights can explicitly override this default
         * via the LightManager API to clamp the search footprint for specific geometric setups
         * without affecting the rest of the scene.
         * The maximum search radius in world-space meters:</li>
         *   <li>A smaller value (e.g., 0.05 to 0.1) tightly anchors shadows to their
         * contact points and prevents artifacts near complex light fixtures.</li>
         *   <li>A larger value provides more physically accurate blocker averaging for
         * massive area lights but increases the risk of floating geometry.</li>
         * </ul>
         *
         * @see LightManager.ShadowOptions#maxSearchRadius
         */
        public float maxSearchRadius = 1.0f;
    }

    /**
     * Options for Screen-space Reflections.
     *
     * @see #setScreenSpaceReflectionsOptions
     */
    public static class ScreenSpaceReflectionsOptions {
        /** ray thickness, in world units */
        public float thickness = 0.1f;
        /** bias, in world units, to prevent self-intersections */
        public float bias = 0.01f;
        /** maximum distance, in world units, to raycast */
        public float maxDistance = 3.0f;
        /** stride, in texels, for samples along the ray. */
        public float stride = 2.0f;
        public boolean enabled = false;
    }

    /**
     * Options for the  screen-space guard band.
     *
     * <p>A guard band can be enabled to avoid some artifacts towards the edge of the screen when
     * using screen-space effects such as SSAO. Enabling the guard band reduces performance slightly.
     * Currently the guard band can only be enabled or disabled.</p>
     */
    public static class GuardBandOptions {
        public boolean enabled = false;
    }

    /** Options for stereoscopic (multi-eye) rendering. */
    public static class StereoscopicOptions {
        public boolean enabled = false;
    }

    /** Result of a picking query */
    public static class PickingQueryResult {
        @Entity
        public int renderable;
        /** RenderableManager Entity at the queried coordinates */
        public float depth;
        /**
         * screen space coordinates in GL convention, this can be used to compute the view or world space position of the picking hit.
         *
         * <p>For e.g.:
         *   clip_space_position  = (fragCoords.xy / viewport.wh, fragCoords.z) * 2.0 - 1.0
         *   view_space_position  = inverse(projection) * clip_space_position
         *   world_space_position = model * view_space_position</p>
         *
         * <p>The viewport, projection and model matrices can be obtained from Camera. Because
         * pick() has some latency, it might be more accurate to obtain these values at the
         * time the View::pick() call is made.</p>
         *
         * <p>Note: if the Engine is running at FEATURE_LEVEL_0, the precision or {@code depth} and
         *       {@code fragCoords.z} is only 8-bits.</p>
         */
        @NonNull @Size(min = 3)
        public float[] fragCoords = new float[3];
    }


    private static native void nSetName(long nativeView, @NonNull String name);
    @Nullable
    private static native String nGetName(long nativeView);
    private static native void nSetScene(long nativeView, long nativeScene);
    private static native void nSetRenderTarget(long nativeView, long nativeRenderTarget);
    private static native void nSetViewport(long nativeView, int viewportLeft, int viewportBottom, int viewportWidth, int viewportHeight);
    private static native void nSetCamera(long nativeView, long nativeCamera);
    private static native boolean nHasCamera(long nativeView);
    private static native void nSetChannelDepthClearEnabled(long nativeView, @IntRange(from = 0) int channel, boolean enabled);
    private static native boolean nIsChannelDepthClearEnabled(long nativeView, @IntRange(from = 0) int channel);
    private static native void nSetBlendMode(long nativeView, int blendMode);
    private static native int nGetBlendMode(long nativeView);
    private static native void nSetVisibleLayers(long nativeView, @IntRange(from = 0) int select, @IntRange(from = 0) int values);
    private static native void nSetLayerEnabled(long nativeView, @IntRange(from = 0) int layer, boolean enabled);
    @IntRange(from = 0)
    private static native int nGetVisibleLayers(long nativeView);
    private static native void nSetShadowingEnabled(long nativeView, boolean enabled);
    private static native boolean nIsShadowingEnabled(long nativeView);
    private static native void nSetScreenSpaceRefractionEnabled(long nativeView, boolean enabled);
    private static native boolean nIsScreenSpaceRefractionEnabled(long nativeView);
    private static native void nSetSampleCount(long nativeView, @IntRange(from = 0) int count);
    @IntRange(from = 0)
    private static native int nGetSampleCount(long nativeView);
    private static native void nSetAntiAliasing(long nativeView, int type);
    private static native int nGetAntiAliasing(long nativeView);
    private static native void nSetTemporalAntiAliasingOptions(long nativeView, float filterWidth, float feedback, float lodBias, float sharpness, boolean enabled, float upscaling, boolean filterHistory, boolean filterInput, boolean useYCoCg, boolean hdr, int boxType, int boxClipping, int jitterPattern, float varianceGamma, boolean preventFlickering, boolean historyReprojection);
    private static native void nSetScreenSpaceReflectionsOptions(long nativeView, float thickness, float bias, float maxDistance, float stride, boolean enabled);
    private static native void nSetGuardBandOptions(long nativeView, boolean enabled);
    private static native void nSetMultiSampleAntiAliasingOptions(long nativeView, boolean enabled, int sampleCount, boolean customResolve);
    private static native void nSetColorGrading(long nativeView, long nativeColorGrading);
    private static native void nSetAmbientOcclusionOptions(long nativeView, int aoType, float radius, float power, float bias, float resolution, float intensity, float bilateralThreshold, int quality, int lowPassFilter, int upsampling, boolean enabled, boolean bentNormals, float minHorizonAngleRad, float ssctLightConeRad, float ssctShadowDistance, float ssctContactDistanceMax, float ssctIntensity, float ssctLightDirectionX, float ssctLightDirectionY, float ssctLightDirectionZ, float ssctDepthBias, float ssctDepthSlopeBias, int ssctSampleCount, int ssctRayCount, boolean ssctEnabled, int gtaoSampleSliceCount, int gtaoSampleStepsPerSlice, float gtaoThicknessHeuristic, boolean gtaoUseVisibilityBitmasks, float gtaoConstThickness, boolean gtaoLinearThickness);
    private static native void nSetBloomOptions(long nativeView, long nativeDirt, float dirtStrength, float strength, int resolution, int levels, int blendMode, boolean threshold, boolean enabled, float highlight, int quality, boolean lensFlare, boolean starburst, float chromaticAberration, int ghostCount, float ghostSpacing, float ghostThreshold, float haloThickness, float haloRadius, float haloThreshold);
    private static native void nSetFogOptions(long nativeView, float distance, float cutOffDistance, float maximumOpacity, float height, float heightFalloff, float colorX, float colorY, float colorZ, float density, float inScatteringStart, float inScatteringSize, boolean fogColorFromIbl, long nativeSkyColor, boolean enabled);
    private static native void nSetDepthOfFieldOptions(long nativeView, float cocScale, float cocAspectRatio, float maxApertureDiameter, boolean enabled, int filter, boolean nativeResolution, int foregroundRingCount, int backgroundRingCount, int fastGatherRingCount, int maxForegroundCOC, int maxBackgroundCOC);
    private static native void nSetVignetteOptions(long nativeView, float midPoint, float roundness, float feather, float colorX, float colorY, float colorZ, float colorW, boolean enabled);
    private static native void nSetDithering(long nativeView, int dithering);
    private static native int nGetDithering(long nativeView);
    private static native void nSetDynamicResolutionOptions(long nativeView, float minScale, float maxScale, float sharpness, boolean enabled, boolean homogeneousScaling, int quality);
    private static native void nGetLastDynamicResolutionScale(long nativeView, @Size(min = 2) float[] out);
    private static native void nSetRenderQuality(long nativeView, int hdrColorBuffer);
    private static native void nSetDynamicLightingOptions(long nativeView, float zLightNear, float zLightFar);
    private static native void nSetGridSize(long nativeView, double size);
    private static native double nGetGridSize(long nativeView);
    private static native double nGetEffectiveGridSize(long nativeView);
    private static native void nSetShadowType(long nativeView, int shadow);
    private static native int nGetShadowType(long nativeView);
    private static native void nSetVsmShadowOptions(long nativeView, int anisotropy, boolean mipmapping, int msaaSamples, boolean highPrecision, float minVarianceScale, float lightBleedReduction);
    private static native void nSetSoftShadowOptions(long nativeView, float penumbraScale, float penumbraRatioScale, float maxPenumbraRatio, float maxSearchRadius);
    private static native void nSetPostProcessingEnabled(long nativeView, boolean enabled);
    private static native boolean nIsPostProcessingEnabled(long nativeView);
    private static native void nSetFrontFaceWindingInverted(long nativeView, boolean inverted);
    private static native boolean nIsFrontFaceWindingInverted(long nativeView);
    private static native void nSetTransparentPickingEnabled(long nativeView, boolean enabled);
    private static native boolean nIsTransparentPickingEnabled(long nativeView);
    private static native void nSetStencilBufferEnabled(long nativeView, boolean enabled);
    private static native boolean nIsStencilBufferEnabled(long nativeView);
    private static native void nSetStereoscopicOptions(long nativeView, boolean enabled);
    private static native void nSetFrustumCullingEnabled(long nativeView, boolean culling);
    private static native boolean nIsFrustumCullingEnabled(long nativeView);
    private static native void nSetDebugCamera(long nativeView, long nativeCamera);
    private static native void nSetMaterialGlobal(long nativeView, @IntRange(from = 0) int index, float valuex, float valuey, float valuez, float valuew);
    private static native void nGetMaterialGlobal(long nativeView, @IntRange(from = 0) int index, @Size(min = 4) float[] out);
    @Entity
    private static native int nGetFogEntity(long nativeView);
    private static native int nGetVisibleRenderableCount(long nativeView);
    private static native void nClearFrameHistory(long nativeView, long nativeEngine);
    private static native void nSetAmbientOcclusion(long nativeView, int ambientOcclusion);
    private static native int nGetAmbientOcclusion(long nativeView);
    private static native void nPick(long nativeView, int x, int y, @Nullable Object handler, @NonNull InternalOnPickCallback internalCallback);
}

// THIS FILE IS GENERATED BY APIGEN AND MUST NOT BE HAND-MODIFIED.
