name: Npm Deploy

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to deploy (e.g., v1.42.2)'
        required: true
        default: 'v1.42.2'

permissions:
  contents: read

jobs:
  npm-deploy:
    name: npm-deploy
    runs-on: macos-14
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ github.event.inputs.release_tag }}
          persist-credentials: false
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Run build script
        run: |
          cd build/web && printf "y" | ./build.sh release
      - name: Deploy to npm
        run: |
          cd out/cmake-wasm-release/web/filament-js
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

