name: Verify Release Notes

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled]

jobs:
  verify-release-notes:
    name: Verify Release Notes
    runs-on: ubuntu-latest
    steps:
      # We *only* need to check out the .github/ directory.
      # The verify RELEASE_NOTES script uses the GitHub API to verify that RELEASE_NOTES was
      # modified.
      - name: Check out action
        uses: Bhacaz/checkout-files@73e17cfbe8d7e0c6b2672b20cb05a718e20d18d4
        with:
          files: .github
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify release notes
        uses: ./.github/actions/verify-release-notes
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          release-notes-file: 'NEW_RELEASE_NOTES.md'
