name: Verify Release Notes

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled]

jobs:
  verify-release-notes:
    name: Verify Release Notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          sparse-checkout: |
            .github
      - name: Verify release notes
        uses: ./.github/actions/verify-release-notes
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          release-notes-file: 'NEW_RELEASE_NOTES.md'
