name: Windows

on:
  push:
    branches:
      - main
      - release
      - rc/**

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Run build script
        run: |
          build\windows\build-github.bat continuous
        shell: cmd
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: filament-windows
          path: out/filament-windows.tgz
