name: Windows

on:
  push:
    branches:
      - main
      - release
      - rc/**

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-2019-32core

    steps:
      - uses: actions/checkout@v4.1.6
      - name: Run build script
        run: |
          build\windows\build-github.bat continuous
        shell: cmd
      - uses: actions/upload-artifact@v4
        with:
          name: filament-windows
          path: out/filament-windows.tgz
